### ISSUE TITLE
Building/installing from source

### ISSUE THREAD

**Issue by Avi-D-coder** [fannheyward/coc-rust-analyzer#10]
`:CocInstall https://github.com/fannheyward/coc-rust-analyzer` does not generate `index.js` and `yarn install` errors with:
```
index.js  4.02 KiB       0  [emitted]  main
Entrypoint main = index.js
[0] ./src/index.ts 400 bytes {0} [built] [failed] [1 error]

ERROR in ./src/index.ts 8:38
Module parse failed: Unexpected token (8:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { Server } from './server';
| 
> export async function activate(context: ExtensionContext): Promise<void> {
|   const run = Server.prepare();
|   if (!run) {
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 2.
error Command failed with exit code 1.
```

**Comment by fannheyward** [comment]
Why would like to install from source instead of `:CocInstall coc-rust-analyzer`?

**Comment by Avi-D-coder** [comment]
I prefer installing everything I can from source.

**Comment by fannheyward** [comment]
Fix with https://github.com/fannheyward/coc-rust-analyzer/commit/8aaa1cb6b2d47f58e7e8593e34b282fb5f6a3310, try again.

**Comment by Avi-D-coder** [comment]
`yarn install` worked, but `:CocInstall` did not.

**Comment by fannheyward** [comment]
According to coc.nvim https://github.com/neoclide/coc.nvim/blob/master/src/model/extension.ts#L88,  `CocInstall` will check `dependencies`, but coc-rust-analyzer's dependencies is empty, that means will not execute `npm install`.

coc-rust-analyzer uses webpack to bundle the extension to a single file, this can speedup the installation and loading. FYI: https://code.visualstudio.com/api/working-with-extensions/bundling-extension
