### ISSUE TITLE
Notifications no longer show for "indexing", "cargo check", etc.

### ISSUE THREAD

**Issue by alexjg** [fannheyward/coc-rust-analyzer#1002]
**What's the output of `:CocInfo`**
```
## versions

vim version: NVIM v0.7.0
node version: v18.3.0
coc.nvim version: 0.0.81-2522eee5 2022-06-14 19:03:29 +0800
coc.nvim directory: /home/alex/.config/nvim/bundle/coc.nvim
term: xterm-256color
platform: linux
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

```
rust-analyzer 0.0.0 (427061da1 2022-06-19) 
```

I don't know if it's intentional but since `080a650ecfc37946b08f9ea110b79160e16d29d8` most of the notifications for things like "cargo check" and "indexing" don't show. To me this is a problem because most of the projects I work on take a while to `cargo check`, so I save a file and then spend a bunch of time where I don't know if rust analyzer has finished checking or not.

Was hiding these notifications intentional? If so I can just maintain a fork for myself, I just want to check first :slightly_smiling_face: ,

**Comment by fannheyward** [comment]
Yes, 080a650ecfc37946b08f9ea110b79160e16d29d8 hides the notifications that message was empty. This may not be a good way to ignore notifications.

**Comment by fannheyward** [comment]
Try v0.64.1

**Comment by alexjg** [comment]
That does the trick. What was the problem it was intending to fix? I notice that there are a few notifications that just say "loading". Maybe we could specifically whitelist the "cargo check" notification?
