### ISSUE TITLE
support socks5 proxy

### ISSUE THREAD

**Issue by sify21** [fannheyward/coc-rust-analyzer#1003]
I'm in China with restricted internet. Without proxy the plugin can fetch update information but the download would fail. If I set `https_proxy=socks5://...`, it won't prompt me with new release information

**Comment by fannheyward** [comment]
Try v0.65.0

**Comment by fannheyward** [comment]
v0.65.1 removed socks5 proxy support because proxy-agent uses vm2 that would cause another issue. Try to convert socks5 proxy to HTTP proxy.

**Comment by sify21** [comment]
Thanks for the tips! I found this tool helpful https://github.com/KaranGauswami/socks-to-http-proxy
