### ISSUE TITLE
Feature request: Command "runCurrent"

### ISSUE THREAD

**Issue by NoahTheDuke** [fannheyward/coc-rust-analyzer#1020]
**What's the output of `:CocInfo`**
```
## versions

vim version: NVIM v0.7.2
node version: v16.15.0
coc.nvim version: 0.0.81-2522eee5 2022-06-14 19:03:29 +0800
coc.nvim directory: /home/noah/.local/share/nvim/site/pack/packer/start/coc.nvim
term: xterm-256color
platform: linux
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**
```
rust-analyzer 0.3.1131-standalone (897a7ec4b 2022-07-17)
```

`:CocCommand rust-analyzer.run` is great, but I would love a command that runs the test directly under my cursor. That way, I can bind it to a shortcut and just run `<leader>tc` without any additional inputs.

Thanks so much, this is an excellent plugin.

**Comment by fannheyward** [comment]
I've add `testCurrent` command in v0.66.0

**Comment by NoahTheDuke** [comment]
Thank you so much!
