### ISSUE TITLE
Inlay: Where are the second inlay hints coming from?

### ISSUE THREAD

**Issue by Iniesta8** [fannheyward/coc-rust-analyzer#1030]
Hi,

since updating my plugins, I've noticed duplicate inlay hints when editing rust files.

The inlay hints look as follows:

![Screenshot from 2022-08-12 12-02-25](https://user-images.githubusercontent.com/4173026/184341336-5f193588-ed21-40b1-a0d8-d2117bb16a61.png)

Where are the extra inlay hints coming from (the ones without the little leading triangle)? If I completely disable the inlay hints with `"rust-analyzer.inlayHints.enable" = false`, there is still such a hint in every line.
I have tried other `rust-analyzer.inlayHints` settings, but without success.

It's coc related, for sure. If I deactivate coc, no hints are shown at all.

What am I missing?

**Comment by fannheyward** [comment]
Both coc and coc-rust-analyzer added inlay hints, I'll fix this later.

**Comment by fannheyward** [comment]
v0.66.0 has fixed this.

**Comment by Iniesta8** [comment]
Fixed. Thank you!
