### ISSUE TITLE
[Question]: How to change `inlayHints` separator

### ISSUE THREAD

**Issue by lmburns** [fannheyward/coc-rust-analyzer#1035]
Previously I was able to change the separator of the inlay hints with the following configuration options:

```json
"rust-analyzer.inlayHints.typeHintsSeparator": "淪",
"rust-analyzer.inlayHints.chainingHintsSeparator": "‣"
```

I see that these were taken out in `c4ddd9e`. The separator now is a colon (`:`). Is this option configurable anymore? I also looked through `coc.nvim` and didn't find an option to change the separator. I could be missing this though.

**Comment by fannheyward** [comment]
Yes, the new inlay hints implements in coc.nvim side didn't has separator configurations now. We will improve this in coc https://github.com/neoclide/coc.nvim/issues/4074.

**Comment by oblitum** [comment]
This appears to have been implemented on coc.nvim's side now, but if configured (`inlayHint.typeSeparator`, etc), they come on top of the already existing coc-rust-analyzer colons (`:`), so this creates a lot of separator duplication, and makes inlay hints make no sense at all.

**Comment by oblitum** [comment]
Oh, to remove the extra colons one have to set `rust-analyzer.inlayHints.renderColons` to `false` now.
