### ISSUE TITLE
No diagnostics feedback

### ISSUE THREAD

**Issue by paulvt** [fannheyward/coc-rust-analyzer#1066]
When I edit source files, I get completion, inlay hints, etc. but no diagnostics while there are issues in the files (as shown by `cargo check`).
I tried downgrading rust-analyzer to older versions, but that did not help.
Also, If I run `rust-analyzer diagnostics .` in the project, I _do_ get the diagnostics errors/warnings.

 I also unset any rust-analyzer options I had in `coc-settings.json` to no avail.

Maybe I can/will try a bisect on the coc-rust-analyzer plugin to see if older versions still do work and when it broke, if this happened. TBC!

**What's the output of `:CocInfo`**

```
## versions

vim version: NVIM v0.7.2
node version: v18.7.0
coc.nvim version: 0.0.82-93852e6c 2022-09-30 21:54:52 +0800
coc.nvim directory: /home/paul/.local/share/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-10-06T21:50:16.827 INFO (pid:129039) [services] - registered service "highlight"
2022-10-06T21:50:16.838 INFO (pid:129039) [plugin] - coc.nvim initialized with node: v18.7.0 after 130ms
2022-10-06T21:50:16.970 INFO (pid:129039) [services] - registered service "rust-analyzer"
2022-10-06T21:50:17.075 INFO (pid:129039) [services] - LanguageClient highlight server state change: starting => running
2022-10-06T21:50:19.419 INFO (pid:129039) [attach] - receive notification: showInfo []
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

```
[coc.nvim] rust-analyzer 0.3.1229-standalone
```

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**

```
+ coc-rust-analyzer 0.68.4 ~/.config/coc/extensions/node_modules/coc-rust-analyzer                                                                                                                                                  
```

**Comment by paulvt** [comment]
I went back to v0.67.0, and then it also doesn't work. This is surprising, as going a few versions back for rust-analyzer itself also didn't help. Very confusing!

**Comment by paulvt** [comment]
Ok, it seems that I had some crates in the project/shared target dir that couldn't be build due to incompatibility issues, like:
```
error[E0514]: found crate `cfg_if` compiled by an incompatible version of rustc
   --> /.../.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.17/src/lib.rs:331:1
    |
331 | extern crate cfg_if;
    | ^^^^^^^^^^^^^^^^^^^^
    |
    = note: the following crate versions were found:
            crate `cfg_if` compiled by rustc 1.65.0-beta.1 (2a65764f2 2022-09-19): /.../.cache/cargo-target/debug/deps/libcfg_if-483f5a2788925099.rmeta
    = help: please recompile that crate using this compiler (rustc 1.65.0-beta.2 (e5da98475 2022-09-24)) (consider running `cargo clean` first)
```
and this error goes... nowhere, making rust-analyzer run by coc-rust-analyzer fail in the diagnostics department.
I don't know why running it via the CLI works.

So, I guess the error was in my setup. I am still confused why there was no feedback about this whatsoever in Neovim.
Let me know if you want me to file an issue for that?

**Comment by 3nt3** [comment]
Should this really be closed?

**Comment by paulvt** [comment]
I mean, it is working for me again; it was kind of user error, but the no feedback might be a different issue that should be opened?
