### ISSUE TITLE
toggleInlayHintsCommand removal workaround?

### ISSUE THREAD

**Issue by Chase-Lambert** [fannheyward/coc-rust-analyzer#1077]
rust-analyzer has removed the toggleInlayHints function as discussed here: https://github.com/rust-lang/rust-analyzer/pull/13215

I find that unfortunate as I really like to keep my editor "clean" when possible and find them way too noisy to have on all the time but quite useful on certain occasions. In the discussion linked above, they are talking about possible workarounds for folks to use but it all seems to be VS Code specific. 

Can you think of a way I can get this toggle inlay hints thing working again with a keyboard shortcut?

**What's the output of `:CocInfo`**
ERROR (pid:9871) [node-client] - Error on notification "runCommand": Command: rust-analyzer.toggleInlayHints not found Error

**What's the output of `:CocCommand rust-analyzer.serverVersion`**
[coc.nvim] rust-analyzer 0.3.1266-standalone

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**
 coc-rust-analyzer 0.69.4

**Comment by fannheyward** [comment]
Use `:CocCommand document.toggleInlayHint`, check `:h coc-inlayHint`.

**Comment by Chase-Lambert** [comment]
Thanks for the quick response. It has to be invoked on a per buffer basis and doesn't work if I try and set `"inlayHint.enable" = false` in the config in order to make the "off" position the default so not quite what I was hoping for but it's something.

**Comment by Chase-Lambert** [comment]
For the record in case anyone stumbles upon this you want to set `"inlayHint.display": false` in your `coc-settings.json` (not "inlayHint.enable"). Then in your overall config you can set a keyboard shortcut to run `:CocCommand document.toggleInlayHint` to get back to that sweet hidden by default but available on command functionality some of us need and crave. haha
