### ISSUE TITLE
Apologies if Not Actionable Here

### ISSUE THREAD

**Issue by coffeebe4code** [fannheyward/coc-rust-analyzer#1086]
**What's the output of `:CocCommand rust-analyzer.serverVersion`**
`[coc.nvim] rust-analyzer 0.3.1317-standalone (21e61bee8 2022-12-10)`

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**
`0.70`

Prettier and eslint appear to be enabled on .rs files, I have no idea why or if they are affecting this.

I type
```rust
let com = Command::new("cd");
```
Then after going back to Normal mode the screen visually updates to show.
```rust
let com: Command = Command::new(program: "cd");
```

I dislike this, especially considering these are not real inserts. "Command" and "program" which were inserted are visual only, using w or attempting to select them does not work.

Unfortunately, I just installed rust on this machine, and updated vim. which required me to change my vimrc for completion highlighting. Although, I doubt that would effect this.

Do you have any idea how to disable this?

**Comment by fannheyward** [comment]
I think I got your point. It's not Prettier or eslint enabled for Rust file. `: Command` and `program: ` are inlayHint. You can disable them with `inlayHint.enable`, check `:h coc-inlayHint` for more.
