### ISSUE TITLE
Autocomplete?

### ISSUE THREAD

**Issue by cantevenread** [fannheyward/coc-rust-analyzer#1087]
How do I autocomplete the suggestions ive tried tab/enter/insert and nothing seems to work.

Also The menu that the coc-rust-analyzer gives is a bit too bright how can I darken it?

I use vim

**Comment by fannheyward** [comment]
You need to setup mappings for `<tab>` and `<cr>`, checkout coc.nvim's README or `:h coc-completion-example`.
