### ISSUE TITLE
rust analyzer fail to start 

### ISSUE THREAD

**Issue by darzok0914** [fannheyward/coc-rust-analyzer#1098]
this is a follow up of https://github.com/fannheyward/coc-rust-analyzer/issues/1094 as it has been closed but the issue remains. 

When I open a rust file I get the message:

```sh
[coc.nvim] rust analyzer failed to start, run :CoCCommand reload.workspace to reload
```
So I still think that I need to build from source however I still have the issue described in the previous issue

I also wanted to thank you for your work, help and contribution to the community

**Comment by fannheyward** [comment]
Thank you for your report.

Can you help me to run `node -e "console.log(process.arch, process.platform)"` in your Linux? Maybe coc-rust-analyzer download invalid rust-analyzer for you.

You can also build from source or download rust-analyzer from https://github.com/rust-lang/rust-analyzer/releases, and set `rust-analyzer.server.path` to it.

**Comment by darzok0914** [comment]
hi, 

```sh
 ➜ ~ node -e "console.log(process.arch, process.platform)"
arm64 linux 
```

I already tried to build from source, that was the issue I reported in my 1st ticket

**Comment by oren0e** [comment]
Was this issue solved? I get the same error now

**Comment by fannheyward** [comment]
@oren0e what's your rust-analyzer version?

**Comment by oren0e** [comment]
well, I know I have it, but in the command line this `rust-analyzer --version` does not work. I know I have it because I see it in `rustup component list`

**Comment by fannheyward** [comment]
@oren0e it's langserver issue, your rust-analyzer failed to start. We need more info about how do you install rust-analyzer? coc-rust-analyzer will download it from GitHub to `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer`, does it exists? what's the output of `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --version`?

**Comment by fannheyward** [comment]
@oren0e the output is updated, you're using the latest rust-analyzer release. This means rust-analyzer is working.

coc-rust-analyzer displayed `rust-analyzer failed to start` is because rust-analyzer response `experimental/serverStatus` with errors.

Try `"rust-analyzer.trace.server": "verbose"`, restart to open a rust file, then `:CocCommand workspace.showOutput rust-analyzer` open the logs, search `serverStatus`, you should get something like this:

```
[Trace - 17:18:11.550] Received notification 'experimental/serverStatus'.
Params: {
    "health": "ok",
    "quiescent": true,
    "message": null
}
```

**Comment by oren0e** [comment]
Thanks, it now works without issues. I think what solved it is that I specifically ran again `rustup component add rust-analyzer`
