### ISSUE TITLE
Error message on first download/install

### ISSUE THREAD

**Issue by oblitum** [fannheyward/coc-rust-analyzer#110]
I get `[coc.nvim]: Unable to execute '/home/francisco/.config/coc/extensions/coc-rust-analyzer-data/ra_lsp_server --version'` after it first downloads the latest release. `rust-analyzer` isn't loaded after install, reopening nvim fix the problem.

**Comment by fannheyward** [comment]
Every time when RA client starts, `coc-rust-analyzer` will check out `ra_lsp_server --version` to make sure `ra_lsp_server` is executable. So there is no difference whether it's started for the first time or not.  https://github.com/fannheyward/coc-rust-analyzer/blob/master/src/client.ts#L29

I tested several times and this error message doesn't come every time. I'm using `spawnSync` to run `ra_lsp_server --version` in a child process, don't known if this is the problem. I'll continue to dig it.

**Comment by oblitum** [comment]
Got it. You mean it's not related with it happening on first install for me, that it actually happens randomly.

**Comment by fannheyward** [comment]
I've removed this check, looks like spawn process will cause more problems, #113 . I'll find another solution to make sure `ra_lsp_server` is executable before client starts.
