### ISSUE TITLE
import_coc4.window.onDidChangeActiveTextEditor is not a function

### ISSUE THREAD

**Issue by zkcrescent** [fannheyward/coc-rust-analyzer#1101]
**What's the output of `:CocInfo`**
vim version: NVIM v0.7.0-dev+677-g523f03b50
node version: v18.11.0
coc.nvim version: 0.0.80-a1688fc341
platform: darwin

**What's the output of `:CocCommand rust-analyzer.serverVersion`**
 Error on "runCommand": Command: rust-analyzer.serverVersion not found

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**

coc-rust-analyzer 0.71.1 ~/.config/coc/extensions/node_modules/coc-rust-analyzer

**Comment by zkcrescent** [comment]
btw, coc-settings.json: {
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "vue"
    ],
    "eslint.filetypes": [
        "javascript",
        "vue"
    ],
    "eslint.autoFixOnSave": true,
    "languageserver": {
        "go": {
            "command": "gopls",
            "rootPatterns": [
                "go.mod"
            ],
            "trace.server": "verbose",
            "filetypes": [
                "go"
            ]
        }
    },
    "yaml.schemas": {
        "kubernetes": [
            "/*.yaml"
        ]
    }
}

**Comment by fannheyward** [comment]
> coc.nvim version: 0.0.80-a1688fc341

Upgrade your coc.nvim, you're using an very old release.

**Comment by zkcrescent** [comment]
when I upgrade my coc.nvim, I'm encountering new problems. at INSERT mode, when I tap `tab`, It shown`Unknown function: <SNR>144_check_back_space` 

![image](https://user-images.githubusercontent.com/14883259/212267550-199f25ed-2599-4f25-b1cc-233e2f4b65d6.png)

**Comment by fannheyward** [comment]
Looks like your `tab` mapping uses `CheckBackspace`.

**Comment by zkcrescent** [comment]
Get it. Thanks for your help
