### ISSUE TITLE
[coc.nvim] Error on activate extension coc-rust-analyzer: import_coc4.window.onDidChangeActiveTextEditor is not a function

### ISSUE THREAD

**Issue by anta40** [fannheyward/coc-rust-analyzer#1103]
This happened after uninstalling coc-rls and installing coc-rust-analyzer
```
:CocUninstall coc-rls
:CocInstall coc-rust-analyzer
```

FYI, I have the latest `rust-analyzer` in `/opt`, and I already had that in `PATH`. I'm using MacOS Monterey 12.6.3

**What's the output of `:CocInfo`**
```
vim version: NVIM v0.8.2
node version: v19.5.0
coc.nvim version: 0.0.80-077e470cd5
coc.nvim directory: /Users/andre/.local/share/nvim/site/pack/coc/start/coc.nvim
term: WezTerm
platform: darwin

```
**What's the output of `:CocCommand rust-analyzer.serverVersion`**
`[coc.nvim]: Error on "runCommand": Command: rust-analyzer.serverVersion not found`

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**
`0.71.1`

**Comment by fannheyward** [comment]
> coc.nvim version: 0.0.80-077e470cd5

Upgrade your coc.nvim to latest release.
