### ISSUE TITLE
Auto save check (cargo) wrongly modified my code

### ISSUE THREAD

**Issue by jinzhongjia** [fannheyward/coc-rust-analyzer#1113]
**What's the output of `:CocInfo`**

```
## versions

vim version: NVIM v0.8.3
node version: v19.6.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /home/jin/.local/share/nvim/lazy/coc.nvim
term: xterm-256color
platform: linux
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

version:`0.3.1386-standalone`

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**

version:`0.72.0`

I just input `:w` to save my file, then cargo check run. It change my file wrongly.

I didn't know why? My `coc-setting.json` here is:

```json
{
  "codeLens.enable": true,
  "colors.enable": true,
  "diagnostic.virtualText": true,
  "links.highlight": true,
  "list.alignColumns": true,
  "list.floatPreview": true,
  "snippet.highlight": true,
  "coc.preferences.enableLinkedEditing": true,
  "coc.preferences.extensionUpdateCheck": "daily",
  "coc.preferences.silentAutoupdate": true,
  "Lua.diagnostics.globals": ["vim"],
  "sumneko-lua.enableNvimLuaDev": true,
  "Lua.runtime.version": "LuaJIT",
  "coc.preferences.formatOnSave": true,
  "explorer.icon.enableNerdfont": true,
  "languageserver": {},
  "cSpell.userWords": [
    "Autoupdate",
    "Nvim",
    "gonic",
    "prac",
    "sumneko",
    "vite"
  ]
}
```

![Peek 2023-02-03 21-25](https://user-images.githubusercontent.com/41784264/216615430-be63e390-d8b0-404a-a039-d182f6753787.gif)

**Comment by jinzhongjia** [comment]
and the `prac` is the project root directory

**Comment by gibfahn** [comment]
+1, as far as I can tell what happens is that when coc is running `cargo build` to compile, it writes the name of the current module in the second line of the current file, it seems like the progress bar / list of modules is written to the second line whenever you write a file.

I've been seeing this for maybe a week or two, not sure which update caused it.

**Comment by fannheyward** [comment]
Can't reproduce, `rust-analyzer 0.3.1394-standalone (0b32b65ca 2023-02-05)`

1. `cargo new d1`
2. `cd d1`
3. `nvim src/main.rs`, change to your sample code
4. `:w`, no content changed

<img width="373" alt="截屏2023-02-06 18 00 32" src="https://user-images.githubusercontent.com/345274/216942228-7d7e3823-9964-436e-b20e-94956f2f1b4a.png">

> coc is running cargo build to compile

coc didn't run any `cargo` actions, rust-analyzer did this.

**Comment by gibfahn** [comment]
Okay, so I tried the same steps and got:

```rust
fn main() {
d1
}
```

so must be some setup specific to nvim/coc/rust-analyzer. Will try to work out what causes it.

**Comment by fannheyward** [comment]
Do you have any another rust vim plugins?

**Comment by obreitwi** [comment]
I have the same issue (second line getting replaced by crate name on post-write `cargo check`).
Only custom configuration I have is
```
  "rust-analyzer.checkOnSave.command": "clippy"
```
But removing that does not eliminate the error.

The only other rust-related plugin is `rust-lang/rust.vim` but disabling that also does not resolve the issue.

FWIW, full vim config is [HERE](https://github.com/obreitwi/dot_vim/blob/master/vimrc).
Once I have some more time I'll investigate further.

**Comment by fannheyward** [comment]
`nvim -u mini.vimrc`, still can't reproduce.

```vim
set nocompatible
set runtimepath^=~/.local/share/nvim/plugged/coc.nvim
set runtimepath^=~/src/coc-rust-analyzer
filetype plugin indent on
syntax on
set hidden
```

```
vim version: NVIM v0.9.0-dev-3534+gf9826e1df-dirty
node version: v19.6.0
coc.nvim version: 0.0.82-8c0d3ef9 2023-02-03 14:32:12 +0300
coc.nvim directory: /Users/fannheyward/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

**Comment by gibfahn** [comment]
I managed to reproduce by adding `set foldmethod=expr`, so using this vimrc:

```vim
set nocompatible
set runtimepath^=~/.local/share/nvim/site/pack/packer/start/coc.nvim
set runtimepath^=~/.config/coc/extensions/node_modules/coc-rust-analyzer
filetype plugin indent on
syntax on
set hidden
set foldmethod=expr
```

(had to bisect my vimrc to find it 😁 )

**Comment by fannheyward** [comment]
@gibfahn `rust-analyzer.checkOnSave.overrideCommand` has been renamed to `rust-analyzer.check.overrideCommand`.

I do have `set foldmethod=expr` in my vimrc https://github.com/fannheyward/init.vim/blob/623d197bbdea3230fb329e574d69a23f2bc5f381/init.vim#L59

Tested with 

```json
  "rust-analyzer.check.overrideCommand": [
    "cargo",
    "clippy",
    "--workspace",
    "--message-format=json",
    "--all-targets"
  ],
```

no `nightly` in my project, still can't reproduce this, after `:w`, `cargo clippy` runs and notifications, no code changes.

**Comment by obreitwi** [comment]
Nice find @gibfahn, I also have `foldmethod=expr` with `foldexpr=nvim_treesitter#foldexpr()`.

Setting `foldmethod=manual` serves as a workaround to prevent the second line from being modified.

**Comment by fannheyward** [comment]
> foldexpr=nvim_treesitter#foldexpr()

Maybe nvim-treesitter related?

**Comment by obreitwi** [comment]
> Maybe nvim-treesitter related?

Yes, definitely, but some weird interaction. Disabling either `coc-rust-analyzer` or `nvim-treesitter` will "resolve" the problem, same as setting a manual `foldmethod`. Will investigate further…

**Comment by gibfahn** [comment]
>rust-analyzer.checkOnSave.overrideCommand has been renamed to rust-analyzer.check.overrideCommand.
> no nightly in my project

Okay, tried stable, and using the updated command name, and can still reproduce even with this:

```jsonc
// /Users/gib/tmp/nuke/coc-settings.json
{
  "rust-analyzer.check.overrideCommand": [
    "cargo",
    "clippy",
    "--workspace",
    "--message-format=json",
    "--all-targets"
  ]
}
```

>still can't reproduce this, after :w, cargo clippy runs and notifications, no code changes.

You're saying you can't reproduce with the minimal coc-settings and vimrc I attached? Here's a complete script that reproduces for me:

```shell
tempdir=$(mktemp -dt coc-rust-analyzer-test)
cd "$tempdir"

git clone --depth=1 --branch release https://github.com/neoclide/coc.nvim
git clone --depth=1 https://github.com/fannheyward/coc-rust-analyzer

echo "
set nocompatible
set runtimepath^=$tempdir/coc.nvim
set runtimepath^=$tempdir/coc-rust-analyzer
filetype plugin indent on
syntax on
set hidden

set foldmethod=expr
let g:coc_config_home = '$tempdir'
" > "$tempdir"/mini.vimrc

echo "
{
    "rust-analyzer.checkOnSave.overrideCommand": [
    "cargo",
    "+nightly",
    "clippy",
    "--workspace",
    "--message-format=json",
    "--all-targets"
  ],
}
" > "$tempdir"/coc-settings.json

cargo new d1
cd d1
nvim -u "$tempdir"/mini.vimrc src/main.rs
```

As far as I know that's hermetic. I'm also running on a Mac, using nvim v0.8.3 (latest brew version).

**Comment by gibfahn** [comment]
>>>I also have foldmethod=expr with foldexpr=nvim_treesitter#foldexpr().
>>Maybe nvim-treesitter related?
>Yes, definitely

I have that set in my main init.lua too, but I don't think that's related, as I'm not including that in the `mini.vimrc` I'm using above.

**Comment by obreitwi** [comment]
> @obreitwi I'd be interested to know if the above shell script reproduces for you too.

To make things even more weird: I _cannot_ reproduce the issue with your minimal config. Due to limited time, I am still trying to boil my config down to a minimal viable set.

So far I can tell:
* It does indeed not seem to be connected to treesitter in particular:
    * Setting `foldmethod=manual` resolves the issue (no replacing of the second line by crate name on save).
    * Disabling treesitter but setting `foldmethod=expr` also triggers the issue → `treesitter` does not seem to be the issue.
* It is not related to a specific issue in `coc-settings.json` (removing `coc-settings.json`/rust-analyzer-specific options does not resolve the issue).
* `set verbose=200` and `verbosefile` before saving with `fdm=manual` / `fdm=expr` and comparing the resulting log files does not reveal any interesting log lines that indicate where the changed line originates from.
    * Due to the large amount of log lines I only compared via `comm -2 -3 <(sort <nvim_broken.log | uniq) <(sort <nvim_working.log | uniq)` and skimming the results for interesting candidates containing the crate name.
    * The only command with the crate name seems to be `calling coc#window#set_var(1008, 'message', 'CRATE NAME')`
      But that also appears in the working case and seems to set the message in popup box.

Will keep investigating further.

**Comment by obreitwi** [comment]
Another observation: If the `foldmethod` is set to `expr` globally, `setlocal foldmethod=manual` does _not_ resolve the issue either.

**Comment by jinzhongjia** [comment]
Weird, I reinstalled my system and now everything works without any changes

**Comment by obreitwi** [comment]
Unfortunately, clearing my vim repo and installing all plugins anew did not do the trick :/

**Comment by fannheyward** [comment]
@obreitwi try minimal vimrc, something like :

```vim
set nocompatible
set runtimepath^=~/.local/share/nvim/plugged/coc.nvim
set runtimepath^=~/.config/coc/extensions/node_modules/coc-rust-analyzer
filetype plugin indent on
syntax on
set hidden
```

**Comment by obreitwi** [comment]
@fannheyward I did try the minimal config @gibfahn [suggested](https://github.com/fannheyward/coc-rust-analyzer/issues/1113#issuecomment-1426327796) but this actually did _not_ reproduce the issue for me.

Will continue tonight to work from the minimal example towards my config.

**Comment by obreitwi** [comment]
Now I can reproduce it: After meticulously deleting block after block until my vimrc resembled @gibfahn's `mini.vim` but I still could not reproduce it.

The issue was I needed to execute `yarn install --frozen-lockfile` within both `coc.nvim` and `coc-rust-analyzer`. Afterwards I am able to reproduce the issue with the following `mini.vim`:
```vim
set nocompatible
set runtimepath^=/tmp/coc-rust-analyzer-test.tbLdqU/coc.nvim
set runtimepath^=/tmp/coc-rust-analyzer-test.tbLdqU/coc-rust-analyzer
filetype off

set foldmethod=expr
let g:coc_config_home = '/tmp/coc-rust-analyzer-test.tbLdqU'
```

**Comment by gibfahn** [comment]
I worked around this by removing `set foldmethod=expr` and replacing it with these autocommands:

```viml
    autocmd FileType * setlocal foldmethod=expr  " YAML files should be folded by indent.
    autocmd FileType yaml,rust,json,python setlocal foldmethod=indent  " Some files should be folded by indent.
```

**Comment by kalloc** [comment]
I have the same problem, and thanks a lot @gibfahn, you save my time.

**Comment by fannheyward** [comment]
Reproduced with nvim 0.8.3, but not nvim 0.9.0 nightly. https://github.com/neoclide/coc.nvim/issues/4511

Another solution by now: change `notification.statusLineProgress` to `true`, don't use floating notification window for progress.

Still woking on this.

**Comment by gibfahn** [comment]
> Reproduced with nvim 0.8.3, but not nvim 0.9.0 nightly

Confirmed that latest neovim nightly resolves this and https://github.com/fannheyward/coc-rust-analyzer/issues/1112. For macOS I did a `brew unlink neovim && brew install --head neovim` and that resolved the issue.

**Comment by fannheyward** [comment]
Closed with https://github.com/neoclide/coc.nvim/issues/4511
