### ISSUE TITLE
 How to stop running checks on startup

### ISSUE THREAD

**Issue by hunter1992** [fannheyward/coc-rust-analyzer#1115]
**What's the output of `:CocInfo`**
versions                                                                                 
vim version: VIM - Vi IMproved 9.0 9001182     
node version: v19.5.0                          
coc.nvim version: 0.0.82-b7375d5f 2023-01-30  05:09:03 +0800                                
coc.nvim directory: /home/zhm/.vim/plugged/coc.nvim                                           
term: dumb                             
platform: linux

**What's the output of `:CocCommand rust-analyzer.serverVersion`**
[coc.nvim] rust-analyzer 1.69.0-nightly (11d96b5 2023-02-01)

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**
coc-rust-analyzer 0.72.0 ~/.config/coc/extensions/node_modules/coc-rust-analyzer

I like using coc-rust-analyzer in vim, it makes me feel happy to write rust code. Thanks the contributers very much! 

I have set option “rust-analyzer.checkOnSave.enable” to false， but when I open a .rs file with vim, the "cargo check" progress bar still running, which causes a rapid increase in CPU load. 

I want to know how to prevent coc-rust-analyzer from running cargo check automatically at the moment the file is opened

**Comment by fannheyward** [comment]
Needs rust-analyzer provides a configuration to disable `cargo check` from startup. I don't know rust-analyzer has this or not by now.
