### ISSUE TITLE
Diagnostics do not work on other files or in other windows.

### ISSUE THREAD

**Issue by ElcomJ** [fannheyward/coc-rust-analyzer#1124]
Recently I've been noticing this `problem`, which occurs when I need to work with `several files` or `several windows` at the same time.

Whenever I open a file and modify it, the `diagnostics` work normally, but if I close this file and open another, it `stops` working. The same happens if I work with several windows, only in the first window that I opened that the diagnostics work.

I will leave two videos below with the error occurring with the two occasions:

**Multiple files in one window:**

https://user-images.githubusercontent.com/37147897/225023639-a5b9d88f-4b09-4069-bb37-f82d631ba630.mp4

**Multiple files in multiple windows:**

https://user-images.githubusercontent.com/37147897/225023886-d32b9d5a-7090-41b0-8aad-a49144b87294.mp4

PS: I already tested using clangd, and there it works normally, the error only occurs in rust-analyzer.

**Comment by fannheyward** [comment]
Can't reproduce, maybe something broken with your rust-analyzer, what's your `rust-analyzer --version`?

**Comment by ElcomJ** [comment]
My version of `rust-analyser` is the most current one, because I have installed the one that the extension itself `suggests installing` when it doesn't have bin, and whenever it recommends a new update I install it through `coc-rust-analyser`.

Could the problem be coming from the `rust-analyser` which is installed by **coc-rust-analyser** ?

**Comment by fannheyward** [comment]
Have no idea about this, set `"rust-analyzer.trace.server": "verbose"` in your coc-settings.json, then check `:CocCommand workspace.showOutput rust-analyzer`.

**Comment by ElcomJ** [comment]
@fannheyward The output was more than **3000** lines, I will be attaching a document with it so I don't post it here.

I did the same action as for the videos of multiple files on one screen.

**File below**:

[Output_coc_rust_analyzer.pdf](https://github.com/fannheyward/coc-rust-analyzer/files/10980620/Output_coc_rust_analyzer.pdf)
