### ISSUE TITLE
Leaks processes that are spawned continously

### ISSUE THREAD

**Issue by hasufell** [fannheyward/coc-rust-analyzer#113]
I don't know what's going on here, but some random node process keeps spawning `ra_lsp_server` to the point that my OOM killer triggers. When disabling this plugin, my computer works again.

**Comment by fannheyward** [comment]
Thank you for your feedback, every time when RA client starts, coc-rust-analyzer will check out `ra_lsp_server --version` to make sure ra_lsp_server is executable. I'm using `spawnSync` to run this check, and maybe this will cause processes leaks. I've removed this check.
