### ISSUE TITLE
Is `rust-analyzer.cargo.extraArgs` supported?

### ISSUE THREAD

**Issue by xanderdunn** [fannheyward/coc-rust-analyzer#1134]
rust-analyzer shows a config flag `rust-analyzer.cargo.extraArgs` introduced [here](https://github.com/rust-lang/rust-analyzer/commit/c3864eb5114d91d8f2cca05d5dcd349c6bea9009). But I do not see it mentioned in coc-rust-analyzer's README. Is it supported? 

See rust-lang/rust-analyzer#14328. This is probably necessary to fix my problem in #1133, because it is a build script that is attempting to build a feature that is not supported on the current platform.

**Comment by fannheyward** [comment]
Yes, will improve README.

https://github.com/fannheyward/coc-rust-analyzer/blob/1af167f989da53a862f15fe851ab4e939bf9dc22/package.json#L253-L260
