### ISSUE TITLE
rust-analyzer.upgrade gives "Error: ETXTBSY: text file is busy on"

### ISSUE THREAD

**Issue by oblitum** [fannheyward/coc-rust-analyzer#115]
With a rust file open and trying to upgrade to last release I get on `:CocCommand rust-analyzer.upgrade`:

```
[coc.nvim] error: Uncaught exception: Error: ETXTBSY: text file is busy, open '/home/francisco/.config/coc/extensions/coc-rust-analyzer-data/ra_lsp_server'
```

Then the downloading status keep spinning and doesn't go away.

**Comment by fannheyward** [comment]
Hello @oblitum , what's your OS platform? Windows or Linux or macOS? Looks like this is caused by writing to a currently executing binary `ra_lsp_server`. I've tested on macOS, it's ok to write to a running binary. Maybe I need `unlink` first https://stackoverflow.com/questions/1712033/replacing-a-running-executable-in-linux

**Comment by oblitum** [comment]
My OS is Linux. I've rarely seen these kind of issue in Linux, is common in Windows.

**Comment by fannheyward** [comment]
Yes, unix-like system can write to a running binary. But on Windows, we need more work https://www.codeproject.com/Answers/1160467/Download-and-replace-running-EXE#answer4

**Comment by fannheyward** [comment]
Or, maybe we can _stop_ the server first, then download and replace the binary file, and start server again.

**Comment by oblitum** [comment]
Looks like the best approach.

**Comment by fannheyward** [comment]
@oblitum please try again `rust-analyzer.upgrade`, server will be stopped before upgraded.

**Comment by oblitum** [comment]
@fannheyward nice, I tried, it works. But just a warning, it works if you have just one [neo]vim instance open. While I was trying to update I got the same error, and noticed that I had a rust-analyzer process running, which was due to a neovim instance I forgot open in a tmux pane.

**Comment by oblitum** [comment]
This is still happening for me for quite a while again and I've been silently ignoring and restarting neovim.
