### ISSUE TITLE
keep asking: "Rust Analyzer has a new release"

### ISSUE THREAD

**Issue by chaosma** [fannheyward/coc-rust-analyzer#1159]
Every time I opened a ".rs" file, it will pop out "Rust Analyzer has a new release", no matter which choice I chose.

**What had been tried**
* The command `:CocUpdate` said
```
 coc-rust-analyzer Current version 0.73.0 is up to date.
```

* also tried to uninstall and install coc-rust-anlayzer

**Possible cause**

From the github release page of `rust-analyzer`, the latest stable version is [2023-07-03](https://github.com/rust-lang/rust-analyzer/releases/tag/2023-07-03)

I guess the cause is that the npmjs registry is not updated with the github release. But I don't know how to fix it.

**What's the output of `:CocInfo`**

<img width="889" alt="Screenshot 2023-07-04 at 4 42 14 PM" src="https://github.com/fannheyward/coc-rust-analyzer/assets/3767044/237ad3eb-2ed8-4a8b-a0a8-0d3dd1e3f453">

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

```
[coc.nvim] rust-analyzer 0.3.1566-standalone (4a2ceeff0 2023-06-25)
```

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**
```
coc-rust-analyzer 0.73.0 ~/.config/coc/extensions/node_modules/coc-rust-analyzer
```

**Comment by fannheyward** [comment]
> rust-analyzer 0.3.1566-standalone (4a2ceeff0 2023-06-25)

coc-rust-analyzer will check and download rust-analyzer from GitHub release, you're using an outdated release. You can choose to download the latest release, or `CocCommand rust-analyzer.upgrade` to upgrade it manually, or set `rust-analyzer.updates.prompt` to `neverDownload` to disable this.

**Comment by fannheyward** [comment]
> rust-analyzer 0.3.1566-standalone (4a2ceeff0 2023-06-25)

coc-rust-analyzer will check and download rust-analyzer from GitHub release, you're using an outdated release. You can choose to download the latest release, or `CocCommand rust-analyzer.upgrade` to upgrade it manually, or set `rust-analyzer.updates.prompt` to `neverDownload` to disable this.

**Comment by chaosma** [comment]
> > rust-analyzer 0.3.1566-standalone (4a2ceeff0 2023-06-25)
> 
> coc-rust-analyzer will check and download rust-analyzer from GitHub release, you're using an outdated release. You can choose to download the latest release, or `CocCommand rust-analyzer.upgrade` to upgrade it manually, or set `rust-analyzer.updates.prompt` to `neverDownload` to disable this.

After `CocCommand rust-analyzer.upgrade` or set `rust-analyzer.updates.prompt` to `neverDownload` in $HOME/.config/coc/coc-settings.json, the prompt will continue to show up as before

**Comment by fannheyward** [comment]
Screenshot please

**Comment by chaosma** [comment]
<img width="931" alt="Screenshot 2023-07-10 at 8 38 23 PM" src="https://github.com/fannheyward/coc-rust-analyzer/assets/3767044/3e3bc447-41ec-4f89-adf2-5f4645ff2cab">

This prompt shows up every time.

**Comment by fannheyward** [comment]
>  in $HOME/.config/coc/coc-settings.json

Do you have changed `:h coc_config_home`? By default this should be `~/.config/nvim/coc-settings.json`.

**Comment by chaosma** [comment]
It turned out I never setup the coc_config_home. After I set it up in .vimrc, the neverDownload will block the prompt. Thanks for your help!

Although, it would be better to update to the latest version, I will keep it block until there is a solution to make "CocCommand rust-analyzer.upgrade" work.

**Comment by fannheyward** [comment]
Do you have `~/.config/coc/memos.json` file? coc-rust-analyzer will save the release tag to it. Search `coc-rust-analyzer` in the file.

coc-rust-analyzer checks update by the release tag, you got prompt because you're using an outdated release.

**Comment by chaosma** [comment]
Yes, I have the `memos.json`. And it looked something like:

```
 "coc-rust-analyzer|global": {
    "release": "2023-06-25"
  },
```

I have changed it to "2023-07-03", but it still pops up the prompt.
