### ISSUE TITLE
The rust-analyzer can not load workspace from nvim or vim. The software kept prompting me to reload.

### ISSUE THREAD

**Issue by Student-operating** [fannheyward/coc-rust-analyzer#1178]
I tried to write rust project with nvim and coc-rust-analyzer in Ubuntu, but it got the following error, I left CocInfo and error, hoping to solve this problem and use RA properly. 

If you can see this information and have some ideas, please help me, thank you.
![image](https://github.com/fannheyward/coc-rust-analyzer/assets/76213951/52eb0ab9-e6d1-4060-926c-7a7bc833a757)

![image](https://github.com/fannheyward/coc-rust-analyzer/assets/76213951/29aecf57-8424-41af-bea3-7fb6ce25edfd)

**Comment by Student-operating** [comment]
Here is my version
![image](https://github.com/fannheyward/coc-rust-analyzer/assets/76213951/0cfb707c-970a-42dd-be4f-a74d813dc4fd)

**Comment by fannheyward** [comment]
> rust-analyzer failed to start

rust-analyzer's issue, RA returns error server status, the client, coc/coc-rust-analyzer warns you to reload.

Have you set `rust-analyzer.server.path` in your coc-settings.json? coc-rust-analyzer will download RA to `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer`, check this RA's version.

**Comment by Student-operating** [comment]
I set up `rust-analyzer.server.path` in `coc-settings.json`, which points to the rust-analyzer I installed via `cargo install rust-analyzer`.
![image](https://github.com/fannheyward/coc-rust-analyzer/assets/76213951/fbe73ce8-9bb1-44f2-b060-bbe0deabd4cf)

**Comment by Student-operating** [comment]
I will ` rust - analyzer. The server. The path ` the Settings to delete or change to ` ~ /. Config/coc/extensions/coc - rust - analyzer - data/rust - analyzer ` didn't solve the problem, I am very confusing, I didn't set it when I used it in the past.
