### ISSUE TITLE
startup is a little slow

### ISSUE THREAD

**Issue by arashatt** [fannheyward/coc-rust-analyzer#1179]
Does coc-rust-analyzer have to do some Indexing every time I start neovim?
it's a little bit slow process and frustrating, I don't want that.

It does also some fethcing and getting something from github though I added some line in the configuration file so that it doesn't check update in startup:
```

⚠   1    {    "rust-analyzer.updates.checkOnStartup": {
    2     "type": "boolean",
    3     "default": false,
    4     "markdownDescription": "Auto-check rust-analyzer updates on startup"
    5   
    6         }
    7   }    

```
to be more specific, I don't want to see this in srartup:
![image](https://github.com/fannheyward/coc-rust-analyzer/assets/55944526/1d041e78-b1a4-4c35-8cd6-c794909114d3)

**Comment by fannheyward** [comment]
rust-analyzer needs more time to start and index your project, coc-rust-analyzer can't do nothing about the startup speed.

> I don't want to see this in srartup

You can disable the notifications window with `disabledProgressSources`, but this did not improve startup speed.

```
  "notification.disabledProgressSources": [
    "language-client-rust-analyzer"
  ],
```
