### ISSUE TITLE
Ubuntu22.04云主机UEFI版，源码安装vim9和coc.nvim后，用coc命令安装该插件后，发现rust插件不能正常运行

### ISSUE THREAD

**Issue by yygfu** [fannheyward/coc-rust-analyzer#1204]
[coc.nvim] Rust Analyzer Language Server client: couldn't create connection to server.
[coc.nvim] Pending response rejected since connection got disposed                                                  
[coc.nvim] Rust Analyzer Language Server client: couldn't create connection to server.
[coc.nvim]: Unhandled response error -32097 from language server: Pending response rejected since connection got disposed
[coc.nvim] Server rust-analyzer failed to start: Error: Pending response rejected since connection got disposed
[coc.nvim] Rust Analyzer Language Server client: couldn't create connection to server.
[coc.nvim] Pending response rejected since connection got disposed
[coc.nvim] Pending response rejected since connection got disposed
[coc.nvim] Rust Analyzer Language Server client: couldn't create connection to server.
[coc.nvim]: The "rust-analyzer" server crashed 4 times in the last 3 minutes. The server will not be restarted.
[coc.nvim] Pending response rejected since connection got disposed
[coc.nvim] Connection to server got closed. Server will not be restarted.
[coc.nvim] Rust Analyzer Language Server client: couldn't create connection to server

**Comment by fannheyward** [comment]
> couldn't create connection to server

Make sure `rust-analyzer` is installed successfully, run something like `rust-analyzer --help` to check.
