### ISSUE TITLE
codelens run, how to make the split configurable?

### ISSUE THREAD

**Issue by ssh352** [fannheyward/coc-rust-analyzer#1235]
<img width="452" alt="Screenshot 2024-03-05 at 11 15 15 PM" src="https://github.com/fannheyward/coc-rust-analyzer/assets/41779116/1a97c36c-f770-45f6-aad4-
481e83e9b065">

I press shortcut keys to Run: 

<img width="848" alt="Screenshot 2024-03-05 at 11 15 45 PM" src="https://github.com/fannheyward/coc-rust-analyzer/assets/41779116/faa63c5a-b58c-445f-a58f-6714c8dad12d">

However I couldn't `ctrl-w =` to make the split equal height, could you advise why?

also Is it possible to make the split a vertical instead of horizontal split?

Is it possible to set the default height or width of the split? Thanks!

**Comment by fannheyward** [comment]
No configurations yet, the terminal window can only horizontal split. https://github.com/fannheyward/coc-rust-analyzer/issues/745

You can use something like `autocmd User CocTerminalOpen :resize 20` to resize the terminal when it opens.

**Comment by ssh352** [comment]
> You can use something like `autocmd User CocTerminalOpen :resize 20` to resize the terminal when it opens.

It works, thanks, do you know why `ctrl-w =` doesn't work for the coc opened split?  what's special about the coc opened split?

**Comment by fannheyward** [comment]
>  why ctrl-w = doesn't work

Maybe it's a terminal buffer? not a normal buffer? have no idea about this.

**Comment by ssh352** [comment]
> > why ctrl-w = doesn't work
> 
> Maybe it's a terminal buffer? not a normal buffer? have no idea about this.

`:8split|term`, then `ctrl-w =` works. So it is not because of the terminal buffer. Thanks anyways!
