### ISSUE TITLE
backslash generated  if we use extract into a function OR  fill struct fields etc OR implement missing members

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#1238]
**What's the output of `:CocInfo`**

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**

**Comment by GopherJ** [comment]
code generate while using `impl missing member action`


![image](https://github.com/fannheyward/coc-rust-analyzer/assets/33961674/5040f485-1432-40cf-bce6-5c6a6826aec5)

`

**Comment by fannheyward** [comment]
https://github.com/fannheyward/coc-rust-analyzer/issues/1228
