### ISSUE TITLE
implement missing members sometimes generated anti slashes before }

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#1246]
**What's the output of `:CocInfo`**

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**

**Comment by fannheyward** [comment]
Same https://github.com/fannheyward/coc-rust-analyzer/issues/1238 ？

**Comment by GopherJ** [comment]
oh yeah, I still have this issue sorry but I forgot that I already created one before

**Comment by GopherJ** [comment]
I think it's fixed, will try, great thanks!!

**Comment by GopherJ** [comment]
confirm it's fixed, thanks!
