### ISSUE TITLE
[Breaking Change]: Using Rust Analyzer GitHub release by default

### ISSUE THREAD

**Issue by fannheyward** [fannheyward/coc-rust-analyzer#126]
According https://github.com/rust-analyzer/rust-analyzer/issues/2988#issuecomment-582823051

> With the proposal, the default is effectively "use rust-analyzer from ~/.cargo/bin". I strongly feel that the default should be "use bundled rust-analyzer". Without any options, we should suggest downloading the thing **even** there is a ra_lsp_server in PATH.

`coc-rust-analyzer` will use Rust Analyzer GitHub releases by default. **`ra_lsp_server` in `PATH` will be ignored**. When no RA server found in extension root, extension will guide you to download from GitHub:

<img width="772" alt="Screen Shot 2020-02-07 at 15 29 02" src="https://user-images.githubusercontent.com/345274/74009624-945da380-49be-11ea-82e3-0fd312dde3ed.png">

Input `1` to download. You can always use `:CocCommand rust-analyzer.upgrade` to upgrade. `coc-rust-analyzer` also can do auto update check:

<img width="722" alt="Screen Shot 2020-02-07 at 15 40 35" src="https://user-images.githubusercontent.com/345274/74010327-3205a280-49c0-11ea-8007-632c996e5d98.png">

You can also use `rust-analyzer.raLspServerPath` to set a custom server path, this will be used first.

**Comment by nwtnni** [comment]
Just a quick note here for visibility: you now have to set [`rust-analyzer.serverPath`](https://github.com/fannheyward/coc-rust-analyzer/blob/0ba1ac00bc49e679a987d1b157de7acf531768cd/src/ctx.ts#L96) instead of `rust-analyzer.raLspServerPath` to override the auto-update.
