### ISSUE TITLE
CPU 100% and freeze when too many syntax error

### ISSUE THREAD

**Issue by lambdalisue** [fannheyward/coc-rust-analyzer#127]
First of all, thank you for your great coc plugin 🎉  Well, I'm not 100% sure if it's caused by the coc-rust-analyzer but it seems syntax error cause 100% CPU usage and freezes like below.

<img width="255" alt="Alacritty 2020-02-08 00-10-00" src="https://user-images.githubusercontent.com/546312/74040740-a879c300-4a07-11ea-8d22-f10f3c0748dd.png">

Once Neovim becomes enter this situation, I had to kill it by `kill {PID}`.

### Procedure

1. Save the following file
2. Move cursor after `process::`
3. Insert `{` then escape insert mode and wait
4. Freeze 🍨 

```rust
use std::process::Command;

fn main() {
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
    let a = "a";
}
```

**Comment by fannheyward** [comment]
Can't reproduce, please provide a mini vimrc to reproduce this issue.

**Comment by fannheyward** [comment]
The error sign is not coc's, are you using ALE or anything like with coc together?

**Comment by lambdalisue** [comment]
Oh, sorry. I'll try to make a mini vimrc and re-open it if I could make it.
