### ISSUE TITLE
expectedName can be different if cargo name contains - while RA returns _

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#1271]
saying that the crate name is `ab-c`, expectedName can be `ab-c` but RA will return `ab_c`

https://github.com/fannheyward/coc-rust-analyzer/blob/420eb49216d4c7f109899e25b66f772f11698816/src/commands.ts#L410

**Comment by GopherJ** [comment]
btw this happens in test item

**Comment by fannheyward** [comment]
> but RA will return ab_c

Looks like it's RA's issue.
