### ISSUE TITLE
Triggering assists

### ISSUE THREAD

**Issue by iakshay** [fannheyward/coc-rust-analyzer#128]
Hi, Thanks for creating the extension! Are the assists [mentioned here](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/assists.md) supported in Neovim?

I've tried the examples mentioned on the page, but don't see any completion suggestions to trigger the assists.

**Comment by fannheyward** [comment]
Yes, assists will be triggered by `codeAction`. For example:

```
struct Point {
    x: u32,
    y: u32,
}
```

Put your cursor on x/y, and trigger codeAction. I'm using this mapping: `nmap <silent> ga <Plug>(coc-codeaction)`, so `ga` on normal mode, available actions will list:

<img width="725" alt="Screen Shot 2020-02-10 at 09 37 56" src="https://user-images.githubusercontent.com/345274/74115224-0a455300-4be9-11ea-83c4-bec99bafadf6.png">

Input 2 for `#[derive]`, or 3 for implement.

**Comment by fannheyward** [comment]
You can also use `call CocAction('codeAction')` without mappings.

**Comment by xoac** [comment]
You can also type `:CocAction` and this will work too. 

I fund that [`add_custom_impl`](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/assists.md#add_custom_impl) doesn't work. But it's probably rust-analzer problem in last release.
