### ISSUE TITLE
Fails to extract `rust-analyzer` on Windows

### ISSUE THREAD

**Issue by TonalidadeHidrica** [fannheyward/coc-rust-analyzer#1281]
Thanks for your fast fix in #1280 .  Now the zip flie is downloaded successfully, but unfortunately it is not extracted correctly on my machine.   The extracted files `rust-analyzer.exe` and `rust_analyzer.pdb` are both empty (siez is zero bytes).  It might be related to these issues, but I could not figure out how to fix it.   Is it only me?

- https://github.com/cthackers/adm-zip/issues/538
- https://github.com/cthackers/adm-zip/issues/337
  - (but renaming the filename to have extension `.zip` did not help; also the modification suggested in the issue seems already applied)

(By the way, by the modification line 186 `statusItem.hide()` in `downloader.ts` will no longer be executed on Windows, showing persistent message, JFYI)

**Comment by fannheyward** [comment]
Looks like adm-zip@0.5.13+ is broken, downgrade to adm-zip@0.5.12, try v0.79.1.

**Comment by TonalidadeHidrica** [comment]
It worked, thanks!
