### ISSUE TITLE
rust-analyzer cannot find Cargo.toml if rust project root is in a subdir relative to .git

### ISSUE THREAD

**Issue by Stephen-Seo** [fannheyward/coc-rust-analyzer#150]
I have a rust project set up in a subdir of a project using Git. `CocInfo` shows that rust-analyzer fails to find Cargo.toml after trying to find it in the git project root instead of the subdir that contains the rust project (and is also the current working directory; where I ran neovim from). If I run `git init` in the subdir and create a `.git` in the subdir where the rust project is, rust-analyzer then starts working.

EDIT: Wait.. should I have posted an issue in the `rust-analyzer` github page instead?

**Comment by fannheyward** [comment]
Fixed in 0.4.4, try `:CocUpdate` to upgrade.

**Comment by Stephen-Seo** [comment]
Wow, thanks for the quick fix. Seems to be working fine now.
