### ISSUE TITLE
cargo-watch + ALE slows down nvim

### ISSUE THREAD

**Issue by JeanMertz** [fannheyward/coc-rust-analyzer#16]
When I enable cargo-watch support (using the `clippy` command), _and_ I use `diagnostic.displayByAle`, it looks like something happens synchronously that makes the editor become really slow/unresponsive.

If I save a file that has 2 or 3 warnings, the cursor flashes several times as it's updating the status, and the editor is unresponsive during that time, so I can't move the cursor for a second or so.

Unfortunately I don't have a minimum reproducible example, but I'm posting it here instead of coc.nvim, because all the other extensions don't show this behaviour with ALE integration enabled.

**Comment by fannheyward** [comment]
Try to disable ale's lint. Looks like ale's lint and cargo-watch lint makes conflict.

**Comment by JeanMertz** [comment]
I already have. I’ve set `b:ale_linters = []`, but I will check again to make sure.

**Comment by oblitum** [comment]
If you disable ALE linting, then there's no reason to `displayByAle`.

**Comment by JeanMertz** [comment]
> If you disable ALE linting, then there's no reason to `displayByAle`.

`b:ale_linters = []` does not disable ALE linting, it disables the default lints in the current buffer for ALE.

I use this in my `ft=rust` buffers because I want to use coc-rust-analyzer as the linter itself, and use ALE as the tool that reports those lints to me. This allows for a consistent style of error reporting by ALE both in Rust with coc-rust-analyzer, and in other file types with the default ALE linters.

**Comment by oblitum** [comment]
Ah, ok. I've read "disable ale's lint" as is, not "disable ale's default linters".

**Comment by oblitum** [comment]
Have you tried this test with other languages? Maybe it's a problem in `displayByAle` in coc.nvim, not this extension.
