### ISSUE TITLE
Cargo watch “ask” is completely obnoxious

### ISSUE THREAD

**Issue by spease** [fannheyward/coc-rust-analyzer#17]
Every time I open up vim, there’s a pause, I begin typing...and then it asks me if I want to cargo-watch, which screws up the command I’m typing and immediately cancels the message so you can’t see what happened.

I’m currently in the process of figuring out how to switch this off via the config file. An example would go a long way, and I don’t think this “ask” method is a good default if it can’t immediately show up. At the very least, it should have an “always” or “never” option that updates the config for you.

Otherwise, very happy that I can now use Vista.vim and it seems to be working correctly with rust-analyzer. Thanks for the hard work!

**Comment by fannheyward** [comment]
Yes, it has a config `"rust-analyzer.enableCargoWatchOnStartup": "disabled"`. Glad to hear you like it.
