### ISSUE TITLE
Can I get chainingHints?

### ISSUE THREAD

**Issue by oblitum** [fannheyward/coc-rust-analyzer#177]
Can I get `chainingHints` like these?

- https://rust-analyzer.github.io/thisweek/2020/03/30/changelog-18.html

I think it would need `virtualText`, but I'm not sure whether it depends on global `codeLens.enable` or not.  fwiw, I don't wish to have global codelens, just the inlayHints.

**Comment by TimoFreiberg** [comment]
Any progress on this? Is there something I could help with?
I'd hope that all kinds of inlayHints would be supported (chaining hints, type hints and argument name hints, see attached picture)
![inlayHints](https://user-images.githubusercontent.com/5281645/80192591-b4911c00-8617-11ea-9a36-f0cad5c8f250.png)

**Comment by oblitum** [comment]
@TimoFreiberg See `:h nvim_buf_set_virtual_text()`, inlayHints that would go in the middle of text are not possible with NeoVim's virtual text, only those that go after normal text.

**Comment by TimoFreiberg** [comment]
Oh that's a shame! It looks there's a WIP PR to improve that, though :thinking: https://github.com/neovim/neovim/pull/9496

**Comment by fannheyward** [comment]
@oblitum @TimoFreiberg can you test #220 ?

**Comment by oblitum** [comment]
@fannheyward I'm testing it from `dev` branch and it's working nicely.

**Comment by oblitum** [comment]
@TimoFreiberg really thx for looking up that NeoVim issue, I'll give a bump showcasing this usecase there, since it seems stale for an year.

**Comment by TimoFreiberg** [comment]
Awesome!

![image](https://user-images.githubusercontent.com/5281645/80624910-aba3ae80-8a4c-11ea-972e-ffc2b0ed6576.png)

I guess my colortheme needs to be updated a bit :sweat_smile:

**Comment by oblitum** [comment]
@TimoFreiberg you just need to have `:h CocHintVirtualText` properly set, I think it's fine as now.

@fannheyward I think PR just needs a doc about the additional `CocRustChainingHint` highlight.

**Comment by oblitum** [comment]
> I created neoclide/coc.nvim#1829, I think there was something missing.

ah, ok.

**Comment by fannheyward** [comment]
Released v0.6.0
