### ISSUE TITLE
Jump to definition failed

### ISSUE THREAD

**Issue by YYTVicky** [fannheyward/coc-rust-analyzer#180]
My project is a large size project (>100k code of line). When I try to jump to definition, it always failed.

**Comment by fannheyward** [comment]
Can't reproduce, it' ok to use `coc-rust-analyzer` to do jumping/hoving etc with `rust-analyzer` codebase.

**Comment by liyiheng** [comment]
It's fast to jump to `std` and 3rd party crates, but extremely slow(20+ seconds) to jump to my own definition, even there are only several lines.  Is there anyone else got this?

**Comment by fannheyward** [comment]
Looks like it's RA issue, you can test your code with VSCode + RA.

**Comment by liyiheng** [comment]
VSCode +RA,  only the first time is slow. 

coc-rust-analyzer + vim, it's fast to jump to my own definition in another file, but slow when the definition is in current file.  

Tested with nvim, everything is going well.

**Comment by fannheyward** [comment]
I recommend to use nvim+coc.vnim.
