### ISSUE TITLE
[Breaking Changes] rust-analyzer 2020-04-06 renames many configuration options

### ISSUE THREAD

**Issue by fannheyward** [fannheyward/coc-rust-analyzer#184]
[rust-analyzer #3824](https://github.com/rust-analyzer/rust-analyzer/pull/3824/files?file-filters%5B%5D=.json&file-filters%5B%5D=.ts#diff-9234de0bfa99228a67ea76a4391c86f1)

- `rust-analyzer.featureFlags` removed
- `rust-analyzer.excludeGlobs` removed
- `rust-analyzer.useClientWatching` removed
- `rust-analyzer.cargo-watch.enable` -> `rust-analyzer.checkOnSave.enable`
- `rust-analyzer.cargo-watch.arguments` -> `rust-analyzer.checkOnSave.extraArgs`
- `rust-analyzer.cargo-watch.command` -> `rust-analyzer.checkOnSave.command`
- `rust-analyzer.cargo-watch.allTargets` -> `rust-analyzer.checkOnSave.allTargets`
- `rust-analyzer.cargoFeatures.noDefaultFeatures` -> `rust-analyzer.cargo.noDefaultFeatures`
- `rust-analyzer.cargoFeatures.allFeatures` -> `rust-analyzer.cargo.allFeatures`
- `rust-analyzer.cargoFeatures.features` -> `rust-analyzer.cargo.features`
- `rust-analyzer.cargoFeatures.loadOutDirsFromCheck` -> `rust-analyzer.cargo.loadOutDirsFromCheck`

**Comment by kevholder** [comment]
I am not using any custom config but getting this error:

```
## Output channel: rust-analyzer

[Error  - 2:00:49 PM] Connection to server is erroring. Shutting down server.
[Error  - 2:00:49 PM] Connection to server is erroring. Shutting down server.
[Error  - 2:00:49 PM] /Users/kevholder/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer exited with code: null


```

**Comment by kevholder** [comment]
`rm -rf /Users/kevholder/.config/coc/extensions/coc-rust-analyzer-data;` and in vim: `:CocUninstal coc-rust-analyzer` , `:CocInstall coc-rust-analyzer` fixed the problem.
