### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by vn-ki** [fannheyward/coc-rust-analyzer#185]
```
[coc.nvim] error: Uncaught exception: Error: ETXTBSY: text file is busy, open '/home/vn-ki/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer'
```

After this error appears, the download never finishes.

**Comment by fannheyward** [comment]
Are you have multiple `rust-analyzer` process running? Checkout https://github.com/fannheyward/coc-rust-analyzer/issues/115#issuecomment-580045291.
