### ISSUE TITLE
rust-analyzer.procMacro.enabled config item

### ISSUE THREAD

**Issue by JoshMcguigan** [fannheyward/coc-rust-analyzer#205]
https://github.com/rust-analyzer/rust-analyzer/pull/3958 adds a `rust-analyzer.procMacro.enabled` config item to enable proc macro expansion. It would be great if `coc-rust-analyzer` was aware of this config item.

Thanks for your work on `coc-rust-analyzer`!

**Comment by fannheyward** [comment]
This configuration has renamed to `rust-analyzer.procMacro.enable`, https://github.com/rust-analyzer/rust-analyzer/pull/4090. Fixed in v0.5.5.
