### ISSUE TITLE
diagnostics message is out of sync?

### ISSUE THREAD

**Issue by hackingcat** [fannheyward/coc-rust-analyzer#209]
The behavior takes place in coc-python.[#69](https://github.com/neoclide/coc-python/issues/154)

**Comment by fannheyward** [comment]
Can't reproduce. What's your RA version? You can check it with `CocCommand rust-analyzer.serverVersion`, and please make sure your coc.nvim is updated.

**Comment by Avi-D-coder** [comment]
This seems to be a more general issue.
I'm seeing out of diagnostics on with hie. I'm not using the hie extension. Something seems to have regressed in coc.

**Comment by hackingcat** [comment]
The version is 90f8378.I have upgraded coc.nvim to latest version.

**Comment by fannheyward** [comment]
Close by https://github.com/neoclide/coc.nvim/issues/1385, I'll take it a look.
