### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Ploppz** [fannheyward/coc-rust-analyzer#212]
Hey,
I hope you don't mind some questions here. I'm unsure in which repository I should ask.

- Can I configure coc or rust-analyzer to use Clippy?
- Is there any way to jump between errors in a file?
- Is there any way to let the location list (`:lopen`) show errors from more than just the current file, or to otherwise at least get an idea of which other files have errors?

**Comment by TimoFreiberg** [comment]
> Can I configure coc or rust-analyzer to use Clippy?
Yes, see https://github.com/fannheyward/coc-rust-analyzer#configurations. Add `    "rust-analyzer.checkOnSave.command": "clippy",` to your `~/.config/nvim/coc-settings.json`
> Is there any way to jump between errors in a file?
See https://github.com/neoclide/coc.nvim#example-vim-configuration, I think you mean the `<Plug>(coc-diagnostic-prev)` and `<Plug>(coc-diagnostic-next)` bindings
> Is there any way to let the location list (:lopen) show errors from more than just the current file, or to otherwise at least get an idea of which other files have errors?
I'm not sure about that one, but it seems like a coc.nvim issue

**Comment by fannheyward** [comment]
> let the location list (:lopen) show errors from more than just the current file

Try `CocList diagnostics`, or you can set `"coc.preferences.useQuickfixForLocations": true` to your coc-settings.json, and use quickfix list `:copen`.

**Comment by Ploppz** [comment]
Many thanks!
