### ISSUE TITLE
Rust-analyzer starting from scratch every time I open vim

### ISSUE THREAD

**Issue by Eijebong** [fannheyward/coc-rust-analyzer#214]
I'm not sure if this is a coc-r-a problem or a r-a problem.

My workflow is such that vim instances have pretty short lives. Every time I open a new instance, the whole project gets rechecked by rust-analyzer so it makes it kind of useless.

I'm not sure why it restarts from scratch every time (for every dependency) given that it's writing to the `target/` directory.

**Comment by oblitum** [comment]
This is a r-a problem, since the process is closed when [neo]vim exits, when it's started again, it's r-a responsibility to manage a cache or not (it may take time to load it too).
