### ISSUE TITLE
【show_documentation】 内容当中有 "*" 时，显示不正常

### ISSUE THREAD

**Issue by xiaopengli89** [fannheyward/coc-rust-analyzer#215]
https://github.com/neoclide/coc.nvim/issues/1811#issue-606742442

**Comment by fannheyward** [comment]
<img width="548" alt="截屏2020-04-26 09 27 09" src="https://user-images.githubusercontent.com/345274/80294881-1da39b80-87a0-11ea-9aad-dff0327241ec.png">
