### ISSUE TITLE
[Feature request/Regression] Extension no longer searches PATH for the server executable?

### ISSUE THREAD

**Issue by ArifRoktim** [fannheyward/coc-rust-analyzer#216]
When I used this plugin in the past, (back when the the server executable was still called `ra_lsp_server` and pre-compiled releases were not yet available) I remember that it used to search the `PATH` for the server executable. Some sleuthing shows that this capability was removed in 7d9a11b2bfff55cc88efe493dddd5716751d3035. I was wondering if this feature could be added back in.

The reason I'd like this feature is that it'd allow for better support for installation from other sources without having to touch `rust-analyzer.serverPath`:

- Building `rust-analyzer` from source with `cargo xtask install` places the binary under `~/.cargo/bin/rust-analyzer`
- Installing it via a package manager, like [AUR - rust-analyzer-bin](https://aur.archlinux.org/packages/rust-analyzer-bin/) places the binary under `/usr/bin/rust-analyzer`
- Users who download the pre-compiled release could place it under `~/.local/bin/` or whatever directory under their `PATH` that they normally use.

I'd be willing to open a PR if this is something you'd be willing to accept.

**Comment by fannheyward** [comment]
What's the problem of `rust-analyzer.serverPath`, or why don't you like to use `rust-analyzer.serverPath`? All your cases can be covered this.

The main reason I removed `$PATH` searching is that makes me often forget to update to use an old version of RA. For most users, like me, use the bundled binary with auto upgrade will make sure I'm using the latest stable version RA.

**Comment by ArifRoktim** [comment]
I was just too used to the way it used to work I guess. You're right, the new way is better.
