### ISSUE TITLE
No code autocomplete

### ISSUE THREAD

**Issue by ovidius72** [fannheyward/coc-rust-analyzer#221]
I'm trying to replace rls with rust-analyzer. I'm using coc and I've installed the extension coc-rust-analyzer. I've used rust-analyzer from the arch linux aur repository and the one downloaded by the extension but none of theme seems to work for me. There should be something wrong with my setup despite I'v followed the installation guide. 

With coc-rls i see this:
![rust-rls](https://user-images.githubusercontent.com/3592928/80631791-8d42b080-8a56-11ea-8974-d5e99202faf0.png)

but with coc-rust-analyzer (the rls extension removed) I only get the diagnostic but no completion suggestions:

![rust-analyzer](https://user-images.githubusercontent.com/3592928/80631917-c8dd7a80-8a56-11ea-97a4-6c663468a056.png)

I've tried to add these lines to coc-settings.json but with no luck.
```(json)
{
  "diagnostic.enableHighlightLineNumber": true,
  "rust-analyzer.diagnostics.enable": true,
  "rust-analyzer.procMacro.enable": true,
  "rust-analyzer.cargo.loadOutDirsFromCheck": true,
  "rust-analyzer.trace.server": "verbose",
....
}
```

Is it supposed to provide auto completion suggestions ?
Is there anything I'm missing in my config ? Thanks.

**Comment by oblitum** [comment]
@ovidius72 try to provide more detail taking coc.nvim issue template as a model: https://raw.githubusercontent.com/neoclide/coc.nvim/master/.github/ISSUE_TEMPLATE/bug_report.md. It's hard to have an idea without info.

**Comment by fannheyward** [comment]
Do you test with a single rust file or a project with Cargo.toml ?

**Comment by ovidius72** [comment]
It's a project with cargo.toml file.
I did more tests and found this.
I've created a file user.rs under the src directory. Working on that file auto completion does not work until you go in the main.rs file and import it with `mod user;`. Doing that I can see that everything work just fine. So it seems that it only works if you use that module in the main.rs file, otherwise not.
Can you please test if this is the same for you ? thanks

**Comment by fannheyward** [comment]
You can test your code with VSCode+rust-analyzer to make sure it works or not.

**Comment by ovidius72** [comment]
thanks @fannheyward It doesn't work in VSCode+ra . The same thing happens. I don't know if it is the wanted behavior but this has nothing to do with coc-rust-analyzer. If it is an issue, it is related to rust-analyzer itself.
Thanks.

**Comment by mcchrish** [comment]
Had the same issue after upgrading the rust-analyzer binary to 2020-04-27. So I manually download and replace the installed binary to https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-04-20 and now works again.

@fannheyward is there an option to let this plugin choose which version of rust-analyzer to install? That would be handy in cases like downgrading to some version specially since rust-analyzer is not yet stable.

**Comment by fannheyward** [comment]
The latest release is 2020-05-04, you can test the new release.

**Comment by ovidius72** [comment]
the problem is here I guess: https://github.com/rust-analyzer/rust-analyzer/issues/4177
