### ISSUE TITLE
Non-existent characters appear at the end of the line

### ISSUE THREAD

**Issue by liubaohai** [fannheyward/coc-rust-analyzer#226]
![image](https://user-images.githubusercontent.com/26271283/80862131-38e14000-8ca5-11ea-9b6d-658656f0cf24.png)

I don't know it is a bug or special feature. I just want to disable it.
My neovim version: v0.4.3

**Comment by fannheyward** [comment]
It’s method chaining hints, you can disable it by setting `rust-analyzer.inlayHints.chainingHints` to false.
