### ISSUE TITLE
Support Semantic Highlighting via vim-lsp-cxx-highlight plugin

### ISSUE THREAD

**Issue by sdroege** [fannheyward/coc-rust-analyzer#234]
See https://github.com/jackguo380/vim-lsp-cxx-highlight . For coc-clangd this works quite well so maybe that's a solution until coc supports semantic highlighting by itself.

**Comment by fannheyward** [comment]
Does vim-lsp-cxx-highlight support rust?

**Comment by sdroege** [comment]
No, but from what I understood the semantic highlighting LSP protocol extension should be language independent so it shouldn't matter? I might be wrong though.

**Comment by fannheyward** [comment]
Close for now, I'll add semantic highlighting to coc after LSP 3.16 released.
