### ISSUE TITLE
Rust Analyzer is not found

### ISSUE THREAD

**Issue by AndreVallestero** [fannheyward/coc-rust-analyzer#235]
Upon editing a rust file with neovim I get the message "Rust Analyzer is not found, download from GitHub release?". I compiled and installed `rust-analyzer-git` from the AUR and the binary is located in `/usr/bin/rust-analyzer`.

I'm working on an ARM based desktop so the binary releases of Rust Analyzer will not work on my system.

**Comment by anouarkappitou** [comment]
**coc-rust-analyzer** will try to download the latest version of rust-analyzer if it is not present in your system,  in order to use your compiled binary you need to specify the location to **coc-rust-analyzer**, you may need to add `rust-analyzer.serverPath`  to your **coc-settings.json**.
