### ISSUE TITLE
Inability to get coc-rust-analyzer to use my $PATH

### ISSUE THREAD

**Issue by brainplot** [fannheyward/coc-rust-analyzer#237]
Hi, I'm aware of the shift discussed in #126 but I would like `coc-rust-analyzer` to use the version of `rust-analyzer` in my `$PATH`. I version-control my neovim configuration and use it across various machines - some of them even Windows machines - so hardcoding the path in my `coc-settings.json` as below is very inconvenient:
```json
{
	"rust-analyzer.serverPath": "/usr/bin/rust-analyzer",
}
```
as the paths on all my machines don't always match. I always care to keep my machines up-to-date so the [issue linked there](https://github.com/rust-analyzer/rust-analyzer/issues/2988#issuecomment-582823051) doesn't really affect me, in my case.
I would just like to specify `"rust-analyzer.serverPath": "rust-analyzer"` and have coc pick up the version of `rust-analyzer` that's currently in my `$PATH`. Is that something that could be achieved or are there any other blockers?

Thanks for reading and for your work on this plugin!

**Comment by fannheyward** [comment]
`coc-rust-analyzer` used to be able to pick RA from $PATH, but I removed in #126, I prefer not to add this back. Similar issue: #216

**Comment by brainplot** [comment]
I'm aware of the rationale behind this decision but, as I mentioned above, I'm not asking to change the default behaviour of the plugin. I would like to specify `"rust-analyzer.serverPath": "rust-analyzer"` and have it pick it up from my `$PATH`. I would be explicitly opting in to such behaviour, acknowledging the consequences. I see nothing wrong with that. Right now the plugin is **_actively_** preventing me from doing that.
In the issue you linked (#216) you asked:

> What's the problem of `rust-analyzer.serverPath`, or why don't you like to use `rust-analyzer.serverPath`?

I think I provided a case where this behaviour is overly-restrictive and inflexible for a fairly common scenario (in my opinion, as I'm sure I'm not the only one who uses their vim configuration on multiple machines).
