### ISSUE TITLE
Rust-analyzer doesn't start, Exited with code: null

### ISSUE THREAD

**Issue by rsignavong** [fannheyward/coc-rust-analyzer#239]
Hello,

The Rust-analyzer worked a few days ago and new it doesn't start anymore.
It doesn't seem to come from Rust-analyzer because I have rebuild the rust-analyzer and the binary works.

I got the following error on `:CocInfo`

[Error  - 8:37:26 PM] ~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer exited with code: null

I have uninstalled and reinstalled the extensions but that doesn't fix the issue.

**Comment by CarsonHoffman** [comment]
I'm able to reproduce this on macOS. When I download the latest binary of rust-analyzer from the Releases page, I'm prompted that the binary is from an unidentified developer, and I get a "Killed" message running it. I'm able to go into settings and manually allow it for the official rust-analyzer, however it does not appear in the same settings pane when attempting to run via coc-rust-analyzer, so I'm not sure if there's any way to manually allow it.

FWIW, I'm on Catalina Beta 10.15.5. I don't see any issues related to this in rust-analyzer (though it appears to be an upstream issue), so there might be a chance that this is related (I think there would be more issues if it affected the whole macOS or even the whole Catalina base).

**Comment by rsignavong** [comment]
This is the rust-analyzer version : rust-analyzer 6a48a94

**Comment by fannheyward** [comment]
What's your coc.nvim version? You can get it from `:CocInfo`.

**Comment by rsignavong** [comment]
vim version: VIM - Vi IMproved 8.2 8020700
node version: v13.11.0
coc.nvim version: 0.0.78-fd9e7d3972
term: dumb
platform: darwin

**Comment by fannheyward** [comment]
It's coc.nvim issue, has fixed on coc.nvim master branch. Upgrade to latest and try again. https://github.com/neoclide/coc.nvim/issues/1886

**Comment by rsignavong** [comment]
Thank you for the fix, Rust analyzer works now, but there is still the same error message exited : null.

There are other errors but I think it's not related.

```
[Error  - 2:23:45 PM] ~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer exited with code: null
[Error  - 2:23:47 PM] Request textDocument/documentHighlight failed.
  Message: content modified
  Code: -32801 
[ERROR rust_analyzer::main_loop] overly long loop turn: 152.985157ms
```
