### ISSUE TITLE
"Rust Analyzer is not found", with correct minimal coc-settings.json

### ISSUE THREAD

**Issue by damienstanton** [fannheyward/coc-rust-analyzer#240]
Env:
- macOS `10.15.4`
- nvim `v0.5.0-503-g9816173fb`, also tried `0.4.3 stable` from homebrew, same issue.
- coc.nvim `release` branch
- `rust-analyzer` compiled myself and located at `$HOME/bin`
- I have a relatively minimal [`init.vim`](https://github.com/damienstanton/dotfiles/blob/main/vim/init.vim)

`coc-settings.json`:

```javascript
{
    "rust-analyzer.serverPath": "/Users/damien/bin/rust-analyzer"
}
```
The rust-analyzer plugin does not seem to be reading the settings file correctly. Each time I open a Rust file, I am prompted with:

```console
Rust Analyzer is not found, download from GitHub release?:
1. Yes
2. Cancel
Type number and <Enter> or click with mouse (empty cancels):
```
If I pick `1`, a new binary is downloaded, but the plugin never launches. Autocomplete, `gd`, etc. all do not work. Tailing the output of [a logging wrapper](https://www.reddit.com/r/rust/comments/g9mtgg/neovim_coc_rustanalyzer_not_working/) (thanks @burntsushi) around`rust-analyzer` shows it is never called by the plugin.

Am I missing anything? How can I better debug why the plugin doesn't respect the coc-settings config?

**Comment by rsignavong** [comment]
It works for me.
I've cloned the rust-analyzer's repository and then switch to `release` branch, then I build it with `cd ~/LanguageServers/rust-analyzer && cargo xtask install --server`.
I see the rust-analyzer binary inside `~/.cargo/bin`

Then my `:CocConfig` is just this.

```
{
  "coc.preferences.formatOnSaveFiletypes": [
    ...
    "rust",
    ...
  ],
  "diagnostic.errorSign": "✘",
  "diagnostic.infoSign": "i",
  "languageserver": {
    ...
    "rust": {
      "command": "rust-analyzer",
      "filetypes": ["rust"],
      "rootPatterns": ["Cargo.toml"]
    }
  }
}
```

**Comment by fannheyward** [comment]
@rsignavong your config is not related `coc-rust-analyzer`.

**Comment by fannheyward** [comment]
@damienstanton can't reproduce, I tested `"rust-analyzer.serverPath": "/Users/fannheyward/bin/rust-analyzer"` and it works.

What's your coc-rust-analyzer version? You can get it by `:CocList extensions` filter with rust.

**Comment by rsignavong** [comment]
> @rsignavong your config is not related `coc-rust-analyzer`.

Ok I see I was using rust-analyzer without the extension.
Good to me, I've changed my settings to this one
```
{
  "coc.preferences.formatOnSaveFiletypes": [
    ...
    "rust",
    ...
  ],
  "diagnostic.errorSign": "✘",
  "diagnostic.infoSign": "i",
  "languageserver": {
    ... // remove rust config
  },
  "rust-analyzer.serverPath": "~/.cargo/bin/rust-analyzer"
}

and it works fine too, now I don't have the exited null error in `:CocInfo`.
I have this log now
```
## Output channel: Rust Analyzer Language Server Trace
```

No more errors 👍

**Comment by damienstanton** [comment]
@fannheyward the output for the extension version is
```console
coc-rust-analyzer 0.6.2 ~/.config/coc/extensions/node_modules/coc-rust-analyzer
```

**Comment by fannheyward** [comment]
Try to upgrade your coc.nvim to latest.

**Comment by fannheyward** [comment]
Does `which /Users/damien/bin/rust-analyzer` works on your side? If you are using `rust-analyzer.serverPath`, coc-rust-analyzer will check it whether exists by which.

**Comment by damienstanton** [comment]
@fannheyward it looks like this is a usage/documentation issue in coc.nvim itself. Once I set my init.vim config to point to the latest release tag instead of the release branch, e.g.

```vim
 Plug 'neoclide/coc.nvim', {'tag': 'v0.0.78'}
" instead of
 Plug 'neoclide/coc.nvim', {'branch': 'release'}
```
and then reinstalled all my plugins and reinstalled coc-rust-analyzer plugin, everything now works and it correctly finds and uses my `rust-analyzer` binary.

**Comment by fannheyward** [comment]
You should use release branch.

**Comment by damienstanton** [comment]
@fannheyward, release branch for me was pulling 0.6.2 for some reason, which is why I switched to the tag. In any case, the issue's definitely just not having the most recent version. Thanks for your help!

**Comment by semanser** [comment]
I had the same issue. This `coc-settings.json` works for me:

```json
"languageserver": {
    "rust": {
      "command": "rust-analyzer",
      "filetypes": ["rust"],
      "rootPatterns": ["Cargo.toml"]
    }
  }
```

**Comment by cowboy-bebug** [comment]
Fixed mine just now with this:
```
:PlugUpgrade
:PlugUpdate
:CocInstall coc-rust-analyzer
```
Sorry for necro 😅

**Comment by pavva91** [comment]
I had the same issue. I'm on arch linux, tried to install from:
 - ` pacman -S rust-analyzer `

and add the path in the coc config:
`"rust-analyzer.serverPath": "/usr/bin/rust-analyzer"`
but didn't work, same exact error. Removed the system pacman binary rust-analyzer.
Fixed by compiling myself rust-analyzer:

- `git clone https://github.com/rust-lang/rust-analyzer`
- `cd rust-analyzer`
- `cargo xtask install --server`
Update the path in coc config:
`"rust-analyzer.serverPath": "~/.cargo/bin/rust-analyzer"`
