### ISSUE TITLE
Request textDocument/documentHighlight failed

### ISSUE THREAD

**Issue by rsignavong** [fannheyward/coc-rust-analyzer#241]
Hello,

The Highlight doesn't work anymore.
I got the following error on `:CocInfo`.

```
[Error  - 2:31:02 PM] Request textDocument/documentHighlight failed.
  Message: content modified
  Code: -32801 
```

vim version: VIM - Vi IMproved 8.2 8020700
node version: v13.11.0
coc.nvim version: 0.0.78-5af5a806e2
term: dumb
platform: darwin
rust-analyzer eb892d7

**Comment by fannheyward** [comment]
What's your coc-rust-analyzer version? Are you using 0.6.2?

**Comment by rsignavong** [comment]
Yes it's working now, I was not using the coc rust analyzer extension.
There is no more errors and I can't reproduce.
Thank you! 👍
