### ISSUE TITLE
How to restore previous onEnter functionality

### ISSUE THREAD

**Issue by anelson** [fannheyward/coc-rust-analyzer#246]
I'm having a problem with the latest rust-analyzer which I hope I can work around with a change to my neovim config.

In the rust-analyzer [changelog #22](https://rust-analyzer.github.io/thisweek/2020/04/27/changelog-22.html) includes this remark:

> [#4107](https://github.com/rust-analyzer/rust-analyzer/pull/4107) custom onEnter command is disabled by default. To re-enable it, use the following config:

 ```json
{
    "key": "Enter",
    "command": "rust-analyzer.onEnter",
    "when": "editorTextFocus && !suggestWidgetVisible && editorLangId == rust"
}
```

I think what this means is that pressing enter no longer automatically triggers some rust-analyzer logic.  I've noticed that now when I press Enter when the cursor is between two braces, the cursor no longer is indented properly.

Specifically; (`|` is the cursor):

```rust
mod foo {|} // cursor is between two braces.  Now I press the Enter key...

// ..this is what happens now with the latest rust-analyzer
mod foo{
|} 

// ..this is what used to happen, and what I want to get back
mod foo {
    |
}
```

I tried setting up a key binding in neovim but it doesn't seem to have an effect:

```vimscript
autocmd FileType rust inoremap <buffer> <CR> :call CocAction('rust-analyzer.onEnter')<CR>
```

Can anyone suggest a way to work around this annoying problem and get back the previous functionality?

**Comment by fannheyward** [comment]
Tested with latest RA and can't reproduce. There is no `onEnter` feature in `coc-rust-analyzer`, no `rust-analyzer.onEnter` command, so #4107 will not effect this, and your autocmd will do nothing.

**Comment by anelson** [comment]
Thanks for looking into it.  

I know there isn't a `coc-rust-analyzer` command `onEnter`, that is a rust-analyzer command.  I'm asking how I can send that command to rust-analyzer when the Enter key is pressed, so that I can get back the intelligent placement of the cursor which I lost when the rust-analyzer team changed this behavior.

You said you can't reproduce, does that mean in my example with `mod foo{}` your cursor is placed properly, and the closing curly brace on its own line?  If so did you have to change your config to make that work?

BTW I'm using the latest `coc-rust-analyzer` release 0.6.4 and `rust-analyzer` version `eb892d7`.

**Comment by fannheyward** [comment]
Yes, `mod foo{}` will expand to 

```
mod aaa {
    |
}
```

and nothing changed.
