### ISSUE TITLE
Requires rustup for no reason

### ISSUE THREAD

**Issue by tidux** [fannheyward/coc-rust-analyzer#247]
On systems without a rustup binary the plugin errors at startup and then fails to find rust-analyzer in /usr/bin.  Basic sanity checks should exist.

**Comment by fannheyward** [comment]
Can't reproduce, coc-rust-analyzer doesn't require rustup.

**Comment by tidux** [comment]
Well that's wrong.

![Screenshot from 2020-05-26 12-37-04](https://user-images.githubusercontent.com/1330562/82943006-bec37480-9f4d-11ea-90b7-70ce9e5bbc44.png)
