### ISSUE TITLE
Weird interaction with easymotion.

### ISSUE THREAD

**Issue by iago-lito** [fannheyward/coc-rust-analyzer#265]
This happens with `coc-rust-analyzer`, but not with `coc-rls`, but maybe I should report at [`vim-easymotion`](https://github.com/easymotion/vim-easymotion) instead?

With my cursor at any position in the file (here on top):

![before](https://user-images.githubusercontent.com/10091387/83350334-beefb580-a33b-11ea-816d-d58adc295718.png)

Now, navigating the easymotion style (here to the last line with `<leader>j` then `w`:

![easymotion-navigating](https://user-images.githubusercontent.com/10091387/83350379-f8c0bc00-a33b-11ea-9802-93c0943ca143.png)

After navigation, everything gets clogged up with syntax errors:

![after](https://user-images.githubusercontent.com/10091387/83350365-e5adec00-a33b-11ea-84d1-ad73c834ccae.png)

Maybe this is `rust_analyzer` trying to parse the easymotion hints?

It is easy to remove all the messages by either entering/leaving insert mode, or saving the file, *etc.*. But it happens any time I easy-motion navigate in large files. Any idea what the problem could be?

**Comment by fannheyward** [comment]
Sorry, I didn't use easymotion...

**Comment by iago-lito** [comment]
Oh, I've just found that the problem actually occurs with other linters, and that they are aware of it at [`easymotion`](https://github.com/easymotion/vim-easymotion/issues/402) (cross-ref). So I think there is not much to do on `coc` side.. except *ad-hoc* workarounds maybe.

Not sure whether to close this issue because the problem is not yours, or to leave it open as long as the problem persists at `easymotion`'s.
