### ISSUE TITLE
Cannot install in vim 8.2

### ISSUE THREAD

**Issue by jknovi** [fannheyward/coc-rust-analyzer#266]
Suddenly it just stopped working, and when loading a rust file get:

```
[coc.nvim]Error on load extension coc-rust-analyzer from /local/home/javiecan/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
```

tried different things like unninstalling/reinstalling coc-rust-analyzer and coc.nvim, still getting the same issue, also updated the ra binary, with no success. Now I get the error right when installing it again.

I'm not sure how can I make the error more verbose.

**Comment by fannheyward** [comment]
What's your node version?

**Comment by fannheyward** [comment]
Looks like you're using node 8.x, please upgrade your node to version 10+. https://github.com/neoclide/coc.nvim#quick-start
