### ISSUE TITLE
Auto import suddenely not working?

### ISSUE THREAD

**Issue by beemstream** [fannheyward/coc-rust-analyzer#270]
Hi it seems auto import detection seems to have stopped working for me, any idea why this might be the case?

I only get these options when i try to use CocAction
Screenshot: https://imgur.com/a/CaDfb9c

Thanks

**Comment by fannheyward** [comment]
How do you fire code action? coc.nvim has changed `coc-codeaction`, you need to select the missing module first, checkout https://github.com/neoclide/coc.nvim/issues/1981

**Comment by fannheyward** [comment]
Or, you can use [coc-actions](https://github.com/iamcco/coc-actions), which can fire code action on current position.
