### ISSUE TITLE
chainingHints with less frequent refresh

### ISSUE THREAD

**Issue by oblitum** [fannheyward/coc-rust-analyzer#271]
At v0.6.0 chainingHints were implemented, which is nice, though it's refreshed on every change in insert mode. What about providing an option, like coc.nvim does for diagnostics, about refreshing it on insert mode or not, and having it default to `false`, and only refresh on insert leave and/or cursor hold by default?

Current implementation has a flickering issue when typing where all hints are refreshed on each char input, which can be avoided with this option.

**Comment by fannheyward** [comment]
`rust-analyzer.inlayHints.refreshOnInsertMode` added.
