### ISSUE TITLE
applySnippetWorkspaceEdit selects wrong token

### ISSUE THREAD

**Issue by TimoFreiberg** [fannheyward/coc-rust-analyzer#272]
Tracking for the bug described in https://github.com/fannheyward/coc-rust-analyzer/pull/252 by @oblitum
Opening a bug here because I don't see this behaviour in the VS Code plugin.

When triggering the "Add function" codeaction in this file without an empty line at the end:
```
fn main() {
    foo<|>();
}
```
The following is generated:
```
fn main() {
    println!("Hello, world!");
    foo();
}
fn foo() {
    todo!()
[}]

```
with the closing brace of the generated function being selected (highlighted with `[]` brackets).

When triggering the codeaction in the same file with an empty line at the end (which rustfmt removes for me :sweat_smile: ), the `todo!()` is correctly selected

The logic of `applySnippetWorkspaceEdit` looks equivalent to the one in the VS code plugin (compare [coc-rust-analyzer](https://github.com/fannheyward/coc-rust-analyzer/blob/acd5e7fca38dbc8ad8bfe9f187f1f4e6ee64ea88/src/commands.ts#L275) with [VS Code](https://github.com/rust-analyzer/rust-analyzer/blob/e66c7b3a453e7b7385f103ae7f1f3f7438bdb31b/editors/code/src/snippets.ts#L17), so maybe this is a coc.nvim bug?

**Comment by fannheyward** [comment]
closed by https://github.com/neoclide/coc.nvim/issues/2154
