### ISSUE TITLE
Error when prompted to upgrade rust-analyzer

### ISSUE THREAD

**Issue by willfindlay** [fannheyward/coc-rust-analyzer#275]
The extension prompts me to download the newest rust-analyzer source from GitHub:
```
Rust Analyzer has a new release: 2020-06-08, you're using 2020-06-01.
Would you like to download from GitHub:
1. Yes
2. Check GitHub releases
3. Cancel
Type number and <Enter> or click with mouse (empty cancels):
```
However it gets stuck at 0.06% each time and throws the following error message:
```
[coc.nvim] Upgrade rust-analyzer failed, please try again
```

**Comment by fannheyward** [comment]
Can't reproduce, `coc-rust-analyzer` just downloads RA from GitHub, maybe this is a network error.

**Comment by mandreyel** [comment]
FWIW, I keep getting this too. Every now and then the upload succeeds, but usually it just fails with the above.

**Comment by fannheyward** [comment]
What version of node do you use?

**Comment by iago-lito** [comment]
I have the same problem now and then, with
```
$ node --version
v10.20.1
```

**Comment by fannheyward** [comment]
Tested with node 10.21.0, can't reproduce this.

**Comment by mandreyel** [comment]
I'm on node `v12.16.3`.

By the way, I've switched to providing the path of the binary with the `rust-analyzer.serverPath` setting and this fixes the issue (though no big surprises here, updates are now delegated to the user).

**Comment by linde12** [comment]
@fannheyward i'm getting `Error: ETXTBSY: text file is busy, open '/path/to/my/rust-analyzer`

I'm unfamiliar with nvim API but im guessing we have to write to a temporary path, kill rust-analyzer & rename the newly downloaded binary to rust-analyzer?

**Comment by fannheyward** [comment]
@linde12 this error is properly caused by multiple vim instances. 

> write to a temporary path

I'll try this solution.
