### ISSUE TITLE
(coc-refactor) only renames 1 occurence.

### ISSUE THREAD

**Issue by iago-lito** [fannheyward/coc-rust-analyzer#280]
I used to smoothly refactor variables with `(coc-refactor)` action, but it does not work anymore. With this file for instance:

```rust
pub fn main() {
    let mut a = 5;
//----------^ cursor here
    for i in 0..a {
        a += a * 4 - i;
    }
    println!("{}", a);
} 
```
I play `<Plug>(coc-refactor)`, this opens the following buffer:

```rust
Save current buffer to make changes
　
　
　src/main.rs 4:8
    for i in 0..a {
        a += a * 4 - i;
    }
    println!("{}", a);
// ----------------^ cursor here
} 
```
This is not how it used to be, for only the last occurence (under cursor) is highlighted, and the cursor is not where I have played the action.

I rename `a` to `b` (`rb`), then save and quit the buffer (`ZZ` then `ZZ` again). This yields:

```rust
pub fn main() {
    let mut a = 5;
//----------^ cursor here again
    for i in 0..a {
        a += a * 4 - i;
    }
    println!("{}", b); // <----- the only renamed occurence
} 
```

What happened? What could be causing the problem?

**Comment by fannheyward** [comment]
I didn't use `coc-refactor` often, what's the expect when you fire `<Plug>(coc-refactor)`? Or what's it used to be?

**Comment by iago-lito** [comment]
Oh, well I expect the rename buffer to look rather like:

```rust
Save current buffer to make changes
　
　
　src/main.rs 2:8
pub fn main() {
    let mut a = 5;
//----------^ cursor here
    for i in 0..a {
        a += a * 4 - i;
    }
    println!("{}", a);
} 
} 
```
.. with every occurence of `a` highlighted (not just the last one).
Then, whenever I change the `a` under the cursor, all other occurences change as well.
And when I save and quit the buffer, my resulting code looks like:
```rust
pub fn main() {
    // All occurences changed.
    let mut b = 5;
    for i in 0..b {
        b += b * 4 - i;
    }
    println!("{}", b);
}
```

I am surprised that you don't do this often. Is this procedure somehow deprecated? Is there another way to rename a variable with `coc`?

**Comment by fannheyward** [comment]
After some tests, I think I found the issue, `coc-refactor` in coc works with LS rename feature, https://github.com/neoclide/coc.nvim/blob/2984f288554ce1713d63465da0201bc22436e9fd/src/handler/index.ts#L1117, this issue *properly* is a RA issue.

RA 2020-02-11 and early release, after `<Plug>(coc-refactor)`, you will **full** document text in rename buffer, but changed `a` under cursor will not work for others.

RA 2020-02-17 and later release, you can't get full document, just part of the document as you, cursor is under last `a`.

I don't know what's `how it used to be`, with my tests, this doesn't work at all even with RA 2020-02-11. I also test some TypeScript code with `coc-refactor`, it works as your described.

For your last question, `coc-refactor` is not deprecated, it's just that I rarely use it. I use `<Plug>(coc-rename)` to rename a variable.

**Comment by iago-lito** [comment]
Okay, so I should maybe transfer the issue to [RA](https://github.com/rust-analyzer/rust-analyzer)?

(also, thank you for `coc-rename`, I had missed that one :)
