### ISSUE TITLE
<C-n> when completing methods jumps into list.

### ISSUE THREAD

**Issue by Avi-D-coder** [fannheyward/coc-rust-analyzer#283]
Completions after the `.` show up, but when I press `<C-n>` the selection jumps into the middle of the list. This does not happen for function completions or with other language servers.
```rust
fn main() {
    println!("Hello, world!");
    "".
}
```

**Comment by fannheyward** [comment]
With my tests, `C-n` jumps to first item.

**Comment by Avi-D-coder** [comment]
This is my suggest config.
```
	"suggest.removeDuplicateItems": true,
	"suggest.preferCompleteThanJumpPlaceholder": false,
	"suggest.noselect": true,
	"suggest.enablePreselect": true,
	"suggest.fixInsertedWord": true,
```

**Comment by fannheyward** [comment]
Reproduced with your suggest config.

**Comment by fannheyward** [comment]
It's not coc-rust-analyzer issue. I tested with coc.nvim `languageserver.rust` directly, same issue.

**Comment by fannheyward** [comment]
Looks like it's a RA issue. Tested with same version of coc.nvim, RA 2020-05-25 works but RA 2020-06-01 and later release fails.
