### ISSUE TITLE
Add user manual link from rust-analyzer to README

### ISSUE THREAD

**Issue by UgurcanAkkok** [fannheyward/coc-rust-analyzer#284]
I was confused because I didn't see it was necessary to install rust-analyzer binary first. I succeed at installing at the end but there may be people who are confused like me. So I think we should add this link to README https://rust-analyzer.github.io/manual.html#vimneovim which also gives information about how to install rust-analyzer binary. 
Also one reason why i think this is necessary is that my installation was not working even though i installed the binary. It worked after I set "rust-analyzer.serverPath" to "/bin/rust-analyzer". So I think that may be related to the fact that i installed the binary after the coc-rust-analyzer
I may be happy to do that and was gonna pull request it but I wanted to open an issue first to see if this idea could be improved etc.

**Comment by fannheyward** [comment]
You don't need to install RA binary first, `coc-rust-analyzer` can install/update it for you when you open `rust` files.
