### ISSUE TITLE
Workspace specific settings?

### ISSUE THREAD

**Issue by thorlucas** [fannheyward/coc-rust-analyzer#285]
There is one project I'm currently working on that requires me to change rust-analyzer settings for the workspace. See rust-analyzer/rust-analyzer#4490 for more info.

Apparently in VSCode it is possible to change rust-analyzer settings per workspace. Is it possible to do this in coc-rust-analyzer?

**Comment by fannheyward** [comment]
Try `CocLocalConfig`
