### ISSUE TITLE
Error appears then goes away

### ISSUE THREAD

**Issue by davidpdrsn** [fannheyward/coc-rust-analyzer#29]
I'm having an issue where after I save it'll correctly detect an error but after about a second the error goes away. Any idea whats going on?

Recording:

![coc error goes away](https://user-images.githubusercontent.com/718941/66271337-32006500-e85d-11e9-8b4e-6a4c5e6cf84e.gif)

**Comment by fannheyward** [comment]
Looks like `cargo watch` changes the diagnostic.

**Comment by JeanMertz** [comment]
Was this fixed, or not a bug?

**Comment by fannheyward** [comment]
Can't reproduce.
