### ISSUE TITLE
missing instructions?

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#296]
when I install coc-rls, after the installation it works directly.

But it's not the case of coc-rust-analyzer, it asks if I want to download rust-analyzer and I choosed yes, then I have no idea if it has finished or not.

I tried to wait for 1 minute, then I opened a rust project but I cannot find any completions

**Comment by fannheyward** [comment]
Download progress will show on your vim status line.

**Comment by fannheyward** [comment]
`coc-rust-analyzer` will download RA from GitHub releases, maybe there is something wrong with your network. Delete `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer` and try to download again.

**Comment by GopherJ** [comment]
@fannheyward Just info, I tried to do it again but still it doesn't work

**Comment by GopherJ** [comment]
@fannheyward 
```
➜  sda_manager git:(master) ~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer
[1]    12351 segmentation fault  ~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyz
```
