### ISSUE TITLE
strange initialisation time?

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#299]
While trying to use this plugin, I found it can take 5 to 10 seconds to do some initialisation work(my guess).

The means if I open a new rust project, I need to wait at least 5 to 10 seconds to be able to start coding.

Is this normal? I have this behavior on two laptops.

Why rls doesn't have the same behaviour? Shall I consider it's bug from coc-rust-analyzer or rust-analyzer.

Thanks

**Comment by GopherJ** [comment]
During this 5 to 10 seconds, completion, documentation will not work.

**Comment by fannheyward** [comment]
rust-analyzer's issue. It needs time to analyze your code base, depends on your code size.

**Comment by GopherJ** [comment]
@fannheyward ok thanks for  pointing out

**Comment by GopherJ** [comment]
@fannheyward Hi, one another question, how can I check if rust-analyzer's anlysis process? A percentage in status line will be fine, do you think it can be possible?

**Comment by GopherJ** [comment]
@fannheyward Another question:

> can some kind of cache be implemented to solve this?

thanks

**Comment by fannheyward** [comment]
> A percentage in status line will be fine

Already supported.

<img width="507" src="https://user-images.githubusercontent.com/345274/85963699-7fbf8d80-b9e9-11ea-9d74-7b5c6533586c.png">

> can some kind of cache be implemented to solve this?

No, need LS supports this.

**Comment by GopherJ** [comment]
@fannheyward Hi how can I got this spinner?

**Comment by fannheyward** [comment]
Upgrade to the latest nightly release of RA, or use coc-rust-analyzer v0.7.7, this extension had a custom status progress display, and the latest RA has built-in progress support, so the extension has removed it.

Or, just wait RA cuts a new release, properly tomorrow.
