### ISSUE TITLE
Add disableDiagnostics setting

### ISSUE THREAD

**Issue by oblitum** [fannheyward/coc-rust-analyzer#3]
I'm not yet using coc-rust-analyzer, my old setup is:

```vim
  let languageservers = {}

  let languageservers['rust'] = {
  \   'command': 'ra_lsp_server',
  \   'filetypes': ['rust'],
  \   'rootPatterns': ['Cargo.toml'],
  \   'disableDiagnostics': v:true
  \ }

  call coc#config('languageserver', languageservers)
```

Having `disableDiagnostics` is important in my setup because at the moment rust-analyzer isn't useful for diagnostics, so I'm using ALE with RLS for that. I'm not sure whether I can already use this setting with coc-rust-analyzer or it needs to be added.

**Comment by fannheyward** [comment]
Did `disableDiagnostics` works for your setup? I didn't find this setting flag in rust-analyzer. Instead, bellow config is works:

```
  "rust-analyzer.featureFlags": {
    "lsp.diagnostics": false
  },
```

1. https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide_api/src/feature_flags.rs#L53
2. https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_lsp_server/src/main_loop.rs#L622

This feature flag is just added 10days ago: https://github.com/rust-analyzer/rust-analyzer/pull/1715

**Comment by oblitum** [comment]
Yes it worked, it's coc.nvim specific, after using it coc.nvim  won't provide diagnostics.

**Comment by oblitum** [comment]
https://github.com/neoclide/coc.nvim/commit/7006c75f2b6641ebe1f34750523def6ecbc2ce95

**Comment by oblitum** [comment]
Well, if there's an LSP flag, then I'll grab that one, thanks.

**Comment by fannheyward** [comment]
Got it, `disableDiagnostics` is coc.nvim feature, which will not handle diagnostics if set true.

If you use `ra_lsp_server` with coc languagserver config, use `disableDiagnostics`, if you use coc-rust-analyzer, use `rust-analyzer.featureFlags`.

**Comment by oblitum** [comment]
I do my config from `.vimrc`, but this didn't work:

```vim
  call coc#config('rust-analyzer.featureFlags', {
  \   'lsp.diagnostics': v:false
  \ })
```

I get error when the extension starts:

```
[coc.nvim] coc-rust-analyzer is works!
[coc.nvim] failed to deserialize config: invalid type: map, expected a boolean
[coc.nvim] workspace loaded, 16 rust packages
```

**Comment by fannheyward** [comment]
coc-settings.json is works.

Confirmed, `coc#config` setting failed, your config has been parsed to `{ lsp: { diagnostics: false } }`, which is invalid. Looks like this is caused by coc.nvim, I'll dig it later.

**Comment by oblitum** [comment]
Hmm, never mind, doing it this way worked:

```vim
  call coc#config('rust-analyzer', {
  \   'featureFlags': {
  \     'lsp.diagnostics': v:false
  \   }
  \ })
```

**Comment by JeanMertz** [comment]
> at the moment rust-analyzer isn't useful for diagnostics, so I'm using ALE with RLS for that

Would you mind sharing the configuration of this hybrid-setup? This sounds like a best-of-both-worlds approach that I'm interested in adopting.

**Comment by oblitum** [comment]
@JeanMertz I think the relevant parts are

```
augroup vimrc | autocmd! | augroup end

let g:ale_linters['rust'] = ['rls']
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_text_changed = 'normal'

autocmd vimrc User ALEJobStarted call lightline#update()
autocmd vimrc User ALELintPost   call lightline#update()
autocmd vimrc User ALEFixPost    call lightline#update()

call coc#config('rust-analyzer', {
\   'featureFlags': {
\     'lsp.diagnostics': v:false
\   }
\ })

autocmd vimrc User CocStatusChange call lightline#update()
```

**Comment by JeanMertz** [comment]
Thanks a lot!

Out of curiosity, what do you currently miss in RA's diagnostics?

Also, any reason not to let them both report diagnostics information? Is there too much overlap?

And from your config, it looks like you haven't configured RA to start `cargo clippy` in the background, does that change the equation, or is RLS' diagnostics still far ahead of RA's?

**Comment by oblitum** [comment]
@JeanMertz my experience is that RA's diagnostics is mostly absent when compared to RLS, it's simply not useful. That's why they direct people to use it coupled to cargo-watch, which is being added to this extension. I didn't try cargo-watch integration yet but I believe I'll stick RLS bc it feels a lighter solution. It'll be best when RA becomes useful at that.

I have yet to check on clippy. The defaults diagnostics provided by RA are a small subset of what RLS provides, so I see no use to have those duplicated.

**Comment by JeanMertz** [comment]
> but I believe I'll stick RLS bc it feels a lighter solution.

For what it's worth, I'm using this plugin with cargo-watch (using `clippy` instead of `check`), and have had no issues with performance of heaviness.

Contrast that to the past when I used RLS, which could take 10+ seconds before it gave back any feedback after making a change to a document in a larger project.

I'm definitely going to check out your solution, but I have the opposite feeling of finding RLS heavyweight and RA+Clippy lightweight. Perhaps that feeling is no longer justified, so I'm definitely going to give it a go!

**Comment by oblitum** [comment]
@JeanMertz thanks for you report, that makes me give it a try :)

**Comment by oblitum** [comment]
@JeanMertz ah yeah, I forgot (as documented in RA docs), I have no diagnostics as I type with cargo-watch, which sucks :-/

**Comment by JeanMertz** [comment]
Ah I see. Yeah that’s a difference in preference I guess. I disable diagnostics in insert mode so never noticed this drawback.

**Comment by oblitum** [comment]
@JeanMertz I also disable it in insert mode, reason for:

```
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_text_changed = 'normal'
```

Which makes ALE behave like coc.nvim defaults for other languages: diagnostics on sensible occasions, like going when going to normal mode, or after normal mode changes.

**Comment by oblitum** [comment]
Also, lint of file save is annoying because it requires a write to clear up diagnostics...
