### ISSUE TITLE
strange documentation background

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#300]
![image](https://user-images.githubusercontent.com/33961674/85947761-f195c980-b94c-11ea-9e45-efa9b67def49.png)

After switching to coc-rust-analyzer, I got strange documentation background like this.

Any idea?

vimrc: https://github.com/GopherJ/cfg/blob/master/vim/.vimrc

This problem just happens in `vim 8.2`, in neovim it's better but still some strange black highlight

![image](https://user-images.githubusercontent.com/33961674/85947839-5cdf9b80-b94d-11ea-82eb-00a626b810c7.png)

**Comment by GopherJ** [comment]
comparing to `vim`
![image](https://user-images.githubusercontent.com/33961674/85947901-bba51500-b94d-11ea-992f-89f657f9a135.png)

**Comment by GopherJ** [comment]
I tried to add `hi Quote ctermbg=109 guifg=#83a598` but it didn't help.

**Comment by fannheyward** [comment]
Theme issue.
 
<img width="636" src="https://user-images.githubusercontent.com/345274/85965600-bac4bf80-b9ef-11ea-8cbf-87d5e76e7de7.png">
