### ISSUE TITLE
magic completion support

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#304]
Hi, do you have a plan on adding `magic completion`?:

![image](https://user-images.githubusercontent.com/33961674/86245397-b04e2580-bba9-11ea-98f9-7e3a327e6088.png)

It seems quite interesting and not so difficult to add.

**Comment by GopherJ** [comment]
I see that you have also https://github.com/fannheyward/coc-postfix but seems there is no rust support

**Comment by fannheyward** [comment]
Already support.

**Comment by GopherJ** [comment]
@fannheyward Sorry seems I didn't use them correctly.

I did another test. This time I can see:

- [ x ] expr.if

**Comment by fannheyward** [comment]
`pd/ppd` doc error, https://github.com/rust-analyzer/rust-analyzer/pull/5186
`tfn/tmod` can't reproduce, test function is generated.

**Comment by GopherJ** [comment]
ok @fannheyward I misunderstood, I thought tfn and tmod will show up on completion list. Thanks
