### ISSUE TITLE
latest downloading of rust-analyzer failed

### ISSUE THREAD

**Issue by dakom** [fannheyward/coc-rust-analyzer#310]
Happy to provide any more details, just let me know how :)

![image](https://user-images.githubusercontent.com/6406986/86749563-060d4c80-c046-11ea-811f-9602958c1f86.png)

**Comment by fannheyward** [comment]
What's `:CocOpenLog` output? And `:CocInfo`

**Comment by dakom** [comment]
`:CocOpenLog`
![image](https://user-images.githubusercontent.com/6406986/86751982-b760b200-c047-11ea-9653-96e4a5c87994.png)

(yikes!)

`:CocInfo`

```
## versions

vim version: NVIM v0.5.0-577-g48ac77a14
node version: v14.4.0
coc.nvim version: 0.0.78-55ff49c9b7
coc.nvim directory: C:\Users\david\.local\share\nvim\plugged\coc.nvim
term: undefined
platform: win32

## Output channel: Rust Analyzer Language Server Trace
```

**Comment by dakom** [comment]
(btw I am able to use the plugin otherwise, it's something new with the update that's broken)

**Comment by fannheyward** [comment]
`CocOpenLog` issue: https://github.com/neoclide/coc.nvim/issues/2022

The downloading maybe failed in some cases, I'll dig this.

**Comment by Rantanen** [comment]
While `CocOpenLog` doesn't work, it's possible to open that file directly:

```text
2020-07-08T06:34:36.964 INFO (pid:28364) [plugin] - coc.nvim 0.0.78-5d0557f13f initialized with node: v14.3.0 after 236ms
2020-07-08T06:34:47.725 INFO (pid:28364) [services] - registered service "rust-analyzer"
2020-07-08T06:34:47.726 INFO (pid:28364) [services] - Rust Analyzer Language Server state change: stopped => starting
2020-07-08T06:34:47.736 INFO (pid:28364) [language-client-index] - Language server "rust-analyzer" started with 35508
2020-07-08T06:34:47.747 INFO (pid:28364) [services] - Rust Analyzer Language Server state change: starting => running
2020-07-08T06:34:47.756 INFO (pid:28364) [services] - service rust-analyzer started
2020-07-08T06:34:48.696 WARN (pid:28364) [extensions] - Extension coc-rust-analyzer activate cost more than 1s
2020-07-08T06:35:24.738 ERROR (pid:28364) [extension:coc-rust-analyzer] - [Error: EPERM: operation not permitted, unlink 'C:\Users\User\AppData\Local\coc\extensions\coc-rust-analyzer-data\rust-analyzer.exe'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\Rantanen\\AppData\\Local\\coc\\extensions\\coc-rust-analyzer-data\\rust-analyzer.exe'
}
```

I'm guessing the process is running, which prevents the file from being written.

**Comment by Rantanen** [comment]
Killed the process enough times so coc-rust-analyzer didn't restart it anymore. After that the upgrade succeeded just fine.

**Comment by fannheyward** [comment]
handle `EPERM` error 752a08059e29c0d54bfd0c1bd5fce821feee00ee

**Comment by Rantanen** [comment]
At least with Neovim + Coc, I was getting the error with only a single instance. My flow was:
- Open `README.md` (since that was in the project root)
- Use `:CocList files` to open a Rust file.
- Answer `1` to update rust-analyzer when prompted.

I verified that `rust-analyzer` wasn't running at first. When I opened the first Rust-source file in neovim, rust-analyzer showed up in task manager.

**Comment by dakom** [comment]
Killing `rust-analyzer` in the task manager didn't seem to help me. I am still stuck with this bug (just running one instance, selecting `lib.rs`)

**Comment by Rantanen** [comment]
@dakom rust-analyzer will autorestart. Try killing it repeatedly until coc-rust-analyzer gives up. (I think the threshold is something around the lines of 5 failures within a minute.)

**Comment by dakom** [comment]
lol... well... that does technically work :)

**Comment by SuperCuber** [comment]
Can confirm on my windows machine. Relevant log:
```
2020-08-07T13:13:14.036 ERROR (pid:6088) [extension:coc-rust-analyzer] - { [Error: EPERM: operation not permitted, unlink 'C:\Users\Glen\AppData\Local\coc\extensions\coc-rust-analyzer-data\rust-analyzer.exe']
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path:
   'C:\\Users\\Glen\\AppData\\Local\\coc\\extensions\\coc-rust-analyzer-data\\rust-analyzer.exe' }
```
I tried `del rust-analyzer.exe` from cmd while the server was running and it predictably said "access is denied", then I exited vim and deleting worked.
Starting vi again resulted in "rust analyzer not found. download?" prompt which worked.

Would appreciate a fix on this :D

**Comment by btrepp** [comment]
So the workaround for me is.

1) Start neovim
2) Open rust file
3) Get update popup
4) Alt tab out/ kill rust-analyzer.exe 5 times (or until it stops spawning).
5) Alt tab back into vim (Dont click, click causes it to lose the update window).
6) press 1 and download. then it's all fixed.

It's probably okay for the coc-rust-analyzer to kill the rust analyzer it spawned before it updates on windows :).

**Comment by dakom** [comment]
This is still not working for me... is there anything I'm supposed to do besides `PlugUpdate` ?

**Comment by Rantanen** [comment]
`coc-rust-analzyer` is a coc plugin so that would be `:CocUpdate`
