### ISSUE TITLE
Ability to hide less relevant (ie. "ready") information from the status message

### ISSUE THREAD

**Issue by Rantanen** [fannheyward/coc-rust-analyzer#314]
Once the rust-analyzer has loaded, it keeps reporting "rust-analyzer ready" as part of the status message. Reports for rust-analyzer loading/reload needed/etc. are just fine, as those should be somewhat temporary states, but seeing "rust-analyzer ready" constantly in the status bar is somewhat useless.

I am tempted to remove `coc_status` completely from the statusline, but this also removes the `cargo check`, etc. status messages.

Alternatives that popped to my head are:
- Remove `rust-analyzer xyz` portion completely.
- Display `rust-analyzer xyz` only if `xyz` != `ready`

(Original issue: https://github.com/rust-analyzer/rust-analyzer/issues/5275)

**Comment by fannheyward** [comment]
Currently, RA will return four kind status: `loading`, `ready`, `invalid`, `needsReload`.

Here is my thought:

1. display `loading`, at `ready`, remove all.
2. display `invalid` when RA error 
3. when `needsReload`, display it with `reloadWorkspace` suggestion
