### ISSUE TITLE
Limit the max number of syntax errors displayed?

### ISSUE THREAD

**Issue by yihuang** [fannheyward/coc-rust-analyzer#315]
Some times when editing code, rust-analyzer will generate lots syntax errors across the whole source file, which makes vim very slow. Can we limit the max number of syntax errors to process?

**Comment by fannheyward** [comment]
No.

**Comment by yihuang** [comment]
This has become a annoying experience to me, and I'm surprised that no one else has raised similar issue. 
I've opened [similar issue](https://github.com/rust-analyzer/rust-analyzer/issues/3434) in `rust-analyzer` itself before, I'm not sure which one(rust-analyzer or coc-rust-analyzer) is the best place to implement it.

**Comment by GopherJ** [comment]
@yihuang I have similar issue but I think it's more rust-analyzer related

**Comment by yihuang** [comment]
> @yihuang I have similar issue but I think it's more rust-analyzer related

solved: https://github.com/rust-analyzer/rust-analyzer/issues/3434#event-3533168339
