### ISSUE TITLE
signatureHelp issue

### ISSUE THREAD

**Issue by fannheyward** [fannheyward/coc-rust-analyzer#321]
https://github.com/rust-analyzer/rust-analyzer/issues/4751#issuecomment-657126783 

The character offset is not identical to VSCode/coc+languageserver.rust, cc @oblitum

**Comment by fannheyward** [comment]
Character offset will be decreased https://github.com/fannheyward/coc-rust-analyzer/blob/master/src/client.ts#L46

https://github.com/rust-analyzer/rust-analyzer/issues/3615

**Comment by fannheyward** [comment]
For https://github.com/rust-analyzer/rust-analyzer/issues/3615, VSCode will trigger signatureHelp after every character input, coc only trigger when `triggerCharacters` input.

**Comment by oblitum** [comment]
Hi @fannheyward.

I still have the same behavior as in rust-analyzer/rust-analyzer#3615.

Do you reproduce the same?

**Comment by fannheyward** [comment]
Do you use the master branch?

**Comment by oblitum** [comment]
ah, no, I don't. It requires a npm release right?

**Comment by oblitum** [comment]
Okay, I see it requires a new release.

**Comment by fannheyward** [comment]
v0.7.13 is released.

**Comment by oblitum** [comment]
ah nice, fixed!
