### ISSUE TITLE
Loading status/cargo check status not showing

### ISSUE THREAD

**Issue by ludwj61** [fannheyward/coc-rust-analyzer#325]
The first time you create a project or after you adjust the cargo.toml file, the status is correctly sent to the statusline/lightline/etc. (As in, there is the loading icon and it displays each crate it is loading).

However, when reopening the file/project later, the status is not shown. Therefore it is unclear that rust-analyzer is loading in the background.

I am using the most recent nvim, coc, and coc-rust-analyzer.

**Comment by ludwj61** [comment]
I tried with a minimal init.vim and got the same issue. I recommend testing using something that takes a awhile to compile/check, I noticed it by used the Iced gui library.

here's what I used: https://pastebin.com/0Mu8PDV8

**Comment by fannheyward** [comment]
The status message is came from RA, when you create a project, RA shows status loading -> ready, coc-rust-analyzer will remove status at `ready`.

Looks like RA has cached the analyze result, when you reopen the project, RA send `ready` quickly back to client, coc-rust-analyzer will hide it.

**Comment by ludwj61** [comment]
So this is normal behavior? I can see rust-analyzer starting up in task manager (it uses lots of cpu and ram as it starts up) but there's no notification in nvim about it. LSP completion does not work until it's fully loaded.
