### ISSUE TITLE
Add missing arms in match

### ISSUE THREAD

**Issue by linde12** [fannheyward/coc-rust-analyzer#331]
I love this feature (as well as the default impl of a trait) but to do it i have to do `:CocAction`, read through the alternatives and go to the option number each time. I'd rather use <Plug>(coc-fix-current) or <Plug>(coc-codeaction), which i use all the time for e.g. coc-tsserver, in the match block - do you think this is possible or is it a limitation of rust analyzer?

**Comment by fannheyward** [comment]
You can map `CocAction`, or use `coc-codeaction-selected`, or https://github.com/iamcco/coc-actions with `nmap <silent> ga :<C-u>execute 'CocCommand actions.open'<CR>`

**Comment by fannheyward** [comment]
Or you can use `<Plug>(coc-codeaction-line)`, `coc-codeaction` works for current buffer file in latest coc.nvim https://github.com/neoclide/coc.nvim/issues/1937

**Comment by linde12** [comment]
@fannheyward Neither coc-codeaction-line or coc-codeaction works, only CocAction. I got `coc-codeaction-line` to work if i added a comment inside the match expression:
![image](https://user-images.githubusercontent.com/3235069/88041757-23184400-cb4b-11ea-84d3-247149faa36c.png)

Without that it doesn't work, see image:
![image](https://user-images.githubusercontent.com/3235069/88041807-362b1400-cb4b-11ea-9860-217e4e47f2c4.png)

So that isn't very helpful. CocActions work, but i don't have to use it for coc-tsserver and i already have lots of bindings for coc and would like to avoid having even more. I will try coc-actions, although i prefer not having another plugin just to do a codeaction.
