### ISSUE TITLE
Renaming works wrong when a renamed variable appears multiple times in a single line

### ISSUE THREAD

**Issue by fimmind** [fannheyward/coc-rust-analyzer#332]
An issue and a way to reproduce it was described in [rust-analyzer#4420](https://github.com/rust-analyzer/rust-analyzer/issues/4420) and `rust-analyzer`'s devs redirected it to `coc-rust-analyzer`, but after a quick search I couldn't find any issue describing the problem here, so I thought it might be a good idea to create it by myself.

I'm now experiencing the same problem with neovim `v0.4.3` and coc-rust-analyzer `0.7.2` (server version: `rust-analyzer c9c518e`). My configuration can be found [here](https://github.com/fimmind/Dotfiles/tree/master/nvim)

**Comment by fannheyward** [comment]
Fixed by https://github.com/neoclide/coc.nvim/issues/2203, upgrade your coc.nvim to latest.

**Comment by fimmind** [comment]
Sorry for a late answer. Upgrading fixed the issue, thanks
