### ISSUE TITLE
Snippet navigation not working

### ISSUE THREAD

**Issue by ludwj61** [fannheyward/coc-rust-analyzer#333]
When trying to use snippets, I cannot navigate through them with \<c-j\> or \<c-k\>.

For example when trying to use the function snippet, I get this:
![image](https://user-images.githubusercontent.com/42984254/88219557-c93d7a00-cc2f-11ea-9157-5775c41cbcda.png)
![image](https://user-images.githubusercontent.com/42984254/88219575-ce022e00-cc2f-11ea-8fa8-c3530ebbe3a5.png)

The mode stays on insert and I cannot move through any snippet locations.

When using coc-snippets and honza's snippets, snippets work correctly, but those provided by rust analyzer still do not:
![image](https://user-images.githubusercontent.com/42984254/88219894-3ea94a80-cc30-11ea-805a-b0601f55e855.png)
![image](https://user-images.githubusercontent.com/42984254/88219923-4a950c80-cc30-11ea-928c-a752cf513b4e.png)

I am using nvim nightly, updated rust analyzer, and my OS is ubuntu. I had the same issues on windows 10 as well.
my main config: https://pastebin.com/tcAYP1J9
my coc  config that I source in my main config: https://pastebin.com/MhqPsfqS

**Comment by fannheyward** [comment]
rust-analyzer's issue.

The first snippet is came from RA, `fn $0() {}`, there is only one position.

The second snippet is came from vim-snippets,

```
fn ${1:function_name}(${2})${3} {
	${0}
}
```

you can use <C-j/k> to do jumping.

**Comment by ludwj61** [comment]
Thanks. A good temporary solution for me (assuming RA will fix this) was to raise priority from snippets from coc-snippets so that they were over the snippets built into the LSP.
