### ISSUE TITLE
Support for rust-analyzer.inlayHints.enable

### ISSUE THREAD

**Issue by dmarcoux** [fannheyward/coc-rust-analyzer#346]
Thank you for `coc-rust-analyzer`!

I would like disable inlay hints by default with `"rust-analyzer.inlayHints.enable": false` introduced upstream in https://github.com/rust-analyzer/rust-analyzer/pull/4372.

As an alternative, I tried this in my Neovim configuration to achieve the same. It didn't work though.
```
autocmd BufNewFile,BufRead,FileReadPost *.rs :CocCommand rust-analyzer.toggleInlayHints
```

**Comment by fannheyward** [comment]
Set `rust-analyzer.inlayHints.chainingHints` to false.
