### ISSUE TITLE
No config directory

### ISSUE THREAD

**Issue by TENX-S** [fannheyward/coc-rust-analyzer#351]
Sorry if it's a noise, I'm new to Vim.

macOS 10.15.6

```shell
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  5 2020 01:22:14)
```

After Install the `coc.nvim` and `coc-rust-analyzer`, I found there is no folder named `nvim` under the `.config` folder.  Should I create one? Anyway, I have done it already. And write the following code to `$HOME/.config/nvim/coc-settings.json`:
```json
{
    "rust-analyzer.serverPath": "/Users/tenx/.cargo/bin/rust-analyzer-mac"
}
```

But when I `vim somefile.rs`, It always reminds me of this: Rust Analyzer is not found, download ... ?
And when I chose Yes, I wait for a long time but no response to note me if it works or not.
I have used rust-analyzer on VS Code before, it's works fine.

**Comment by fannheyward** [comment]
Try `:CocConfig`, this will create coc-settings.json if not found.
