### ISSUE TITLE
rust-analyzer.serverVersion not working

### ISSUE THREAD

**Issue by Ran4** [fannheyward/coc-rust-analyzer#352]
If I run `CocCommand` and choose the `rust-analyzer.serverVersion` command I get the error

`[coc.nvim] Command: rust-analyzer.serverVersion not found`

```
vim version: NVIM v0.4.3
node version: v12.16.3
coc.nvim version: 0.0.78-bdd9a9e140
```

**Comment by fannheyward** [comment]
`coc-rust-analyzer` hasn't activated yet, open a rust file and try again.
