### ISSUE TITLE
consecutive quickfix produces strange result

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#362]
![Peek 2020-08-27 13-04](https://user-images.githubusercontent.com/33961674/91435106-1aabdb00-e866-11ea-947e-382091e09151.gif)

## Environments

- coc-rust-analyzer: **0.7.15**
- rust-analyzer: **e7da581**

**Comment by GopherJ** [comment]
Actually I'm not sure if it's coc-rust-analyzer's issue or rust-analyzer's issue

**Comment by fannheyward** [comment]
Can you post the demo rust code to debug this issue?

**Comment by GopherJ** [comment]
Hi @fannheyward I managed to reproduce on the following code:

```rust
use actix::{self, Actor, Handler};
use uuid::Uuid;

fn main() {
    println!("Hello, world!");
}
```

**Comment by fannheyward** [comment]
Reproduced similar issue with VSCode+rust-analyzer

![](https://user-images.githubusercontent.com/345274/92469305-32407780-f207-11ea-924f-5eaa5ecaa759.gif)

It's better to do saving after each quickfix.
