### ISSUE TITLE
Is it possible to configure the color of the type hints?

### ISSUE THREAD

**Issue by maxcountryman** [fannheyward/coc-rust-analyzer#365]
I'm not sure what the correct term for these hints is, but I'm referring to the right-hand side of lines 14 and 15 pictured below.

This is a really handy feature and I find it quite useful, however the fact that it's rendered in a very visible dark blue it can be distracting when there are many chained method calls.

Is it possible to configure a color override for this?

<img width="979" alt="Screen Shot 2020-08-30 at 12 30 19 PM" src="https://user-images.githubusercontent.com/74351/91667863-92734300-eabc-11ea-9e87-3c995e2600c8.png">

**Comment by fannheyward** [comment]
It's `CocRustChainingHint`, you can customize it.

**Comment by maxcountryman** [comment]
> It's `CocRustChainingHint`, you can customize it.

Are there any examples of using this to customize the color?

**Comment by imjasonmiller** [comment]
@maxcountryman you can view all available colors via `:hi`. 

I've edited a couple of the colors like so in `init.vim`:

```vim
" Change highlight colors for coc
hi CocErrorSign         guifg=#E06C75
hi CocWarningSign       guifg=#E5C07B
hi CocInfoSign          guifg=#61AFEF
hi CocHintSign          guifg=#586069
hi CocRustChainingHint  guifg=#586069
```

With `CocHintSign` and `CocRustChainingHint` both being the colors for hints.
