### ISSUE TITLE
The document content displayed in CoC's floating window is highlighted with the wrong syntax.

### ISSUE THREAD

**Issue by flw-cn** [fannheyward/coc-rust-analyzer#374]
The document content displayed in CoC's floating window is highlighted with the wrong syntax.
It appears to be due to mistakenly treating the pointed brackets in the Rust type signature as an HTML tag.

I understand that I should try to solve it myself first, but I don't know where to start, e.g. how do I change the code so that CoC can use my modified extensions? And what part of the code is responsible for this problem?

coc-rust-analyzer is a great extension, expect someone to work with me on this to make it better.

Thank you in advance.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5546718/92362336-7279fa00-f122-11ea-8f85-c6d7a8ecc26a.png">

**Comment by fannheyward** [comment]
<img width="907" alt="2020-09-08 18 55 05" src="https://user-images.githubusercontent.com/345274/92467824-d117a480-f204-11ea-9290-0ffa4f68c353.png">

colors cheme  issue.

**Comment by flw-cn** [comment]
Could you help me configure it correctly?

I'm not sure what controls the document syntax in the floating window.

@fannheyward
