### ISSUE TITLE
Extention have stopped autocomplete code after the last update of rust-analyzer

### ISSUE THREAD

**Issue by disDeal** [fannheyward/coc-rust-analyzer#376]
Screenshot: 
![image](https://user-images.githubusercontent.com/32329320/92500839-2eb4ec80-f217-11ea-8fe7-7574d72d3625.png)

``:CocInfo``
```
## versions

vim version: NVIM v0.5.0-617-g82bfdbfe5
node version: v14.2.0
coc.nvim version: 0.0.78-9f9d8a32c4
coc.nvim directory: /home/koms/.config/nvim/plugged/coc.nvim
term: alacritty
platform: linux
```
And no errors in :CocOpenLog unfortunate...

**Comment by fannheyward** [comment]
Your screenshot shows rust-analyzer is working.

**Comment by jessun2017** [comment]
I have to say I have same problem.

![](https://raw.githubusercontent.com/zlipsun/picstore/master/imgs%E6%88%AA%E5%B1%8F2020-09-10%20%E4%B8%8B%E5%8D%8810.52.45.png)

![](https://raw.githubusercontent.com/zlipsun/picstore/master/imgs%E6%88%AA%E5%B1%8F2020-09-10%20%E4%B8%8B%E5%8D%8811.03.07.png)

I prefer rust-analyzer may change something?

**Comment by jessun2017** [comment]
I found the reason: https://github.com/racer-rust/racer/issues/1125
