### ISSUE TITLE
"Run test" codelens action runs all tests

### ISSUE THREAD

**Issue by tomtomjhj** [fannheyward/coc-rust-analyzer#380]
The "Run test" codelens action doesn't seem the generate correct cargo command.

In vscode client, clicking "Run test" above `test1` function runs `test1` only.
![image](https://user-images.githubusercontent.com/19489738/93166377-56e1a580-f759-11ea-9b14-7811b02ae98c.png)

On the other hand, in coc-rust-analyzer, if I run `<Plug>(coc-codelens-action)` on line 3 or 4 and chose "Run test", it runs the whole test suite.
![image](https://user-images.githubusercontent.com/19489738/93166529-a0ca8b80-f759-11ea-9371-93b1d2188d34.png)

So coc-rust-analyzer doesn't generate `-- tests::test1 --exact --nocapture <` part of the command.

I'm using the same rust-analyzer binary that I manually built for both coc-rust-analyzer and vscode (2020-09-14 version).

[Similar report](https://www.reddit.com/r/neovim/comments/gbnl7x/where_does_run_test_come_from_and_what_can_i_do/fpcdogk/?utm_source=reddit&utm_medium=web2x&context=3)

**Comment by tomtomjhj** [comment]
Hmm coc-rls has a similar issue. It runs `cargo run` instead of `cargo test -- ...`
![image](https://user-images.githubusercontent.com/19489738/93169108-59df9480-f75f-11ea-9362-ed418a11d6f3.png)
![image](https://user-images.githubusercontent.com/19489738/93169158-75e33600-f75f-11ea-8bb0-d499dac9cfca.png)

**Comment by fannheyward** [comment]
Try coc-rust-analyzer v0.8.0

**Comment by tomtomjhj** [comment]
Works well now. Thanks!
