### ISSUE TITLE
Couldn't import type automatically

### ISSUE THREAD

**Issue by JoshuaLight** [fannheyward/coc-rust-analyzer#389]
The following code is the minimal reproduction example:
```rust
fn test() {
    let x = HashMap::new();
}
```

Here the `HashMap` token is marked with red in both VsCode and NeoVim. However, VsCode allows executing an action:
![image](https://user-images.githubusercontent.com/7947142/93771703-8a737280-fc26-11ea-810d-e1c32f68e927.png)

While in NeoVim executing `coc-codeaction` results in: `[coc.nvim] No action available` message.

Is there any way to get access to the same action?
Is there any way to use autocompletion for `HashMap` without `use` and automatically import it after completing the selection?

**Comment by fannheyward** [comment]
`:h coc-codeaction` and `:h coc-codeaction-selected`.
