### ISSUE TITLE
Range formatting broken

### ISSUE THREAD

**Issue by Frederick888** [fannheyward/coc-rust-analyzer#393]
I thought it was caused by neoclide/coc.nvim#2363 but now it's been fixed and I still cannot format selected ranges in Rust (other languages, e.g. Java, JavaScript, now work).

Tested the same version of rust-analyzer (2020-09-21 e70cf70) in VSCode and it worked normally, and I see no related bug reports at rust-analyzer, so I suspect it's a bug here.

Btw how can I see the logs? I enabled `"rust-analyzer.trace.server": "verbose"` but got no new logs in `CocCommand workspace.showOutput` after formatting.

**Comment by fannheyward** [comment]
rust-analyzer doesn't support range formatting: https://github.com/rust-analyzer/rust-analyzer/blob/bcdedbb3d5a45ea974cc5f8e9068e9604c43a757/crates/rust-analyzer/src/caps.rs#L55
```
        document_range_formatting_provider: None,
```

> in VSCode and it worked normally

How do you test this? There is only document formatting, no range formatting.

**Comment by Frederick888** [comment]
Ah, sorry, I was being stupid... I selected a few lines in VSC, hit the reformat hotkey, those lines got properly formatted and just thought it was working. But in fact it just formats the whole file anyway no matter whether you've selected a range or not. Imma gonna head out to get some fresh air lol...
