### ISSUE TITLE
inlay hints turn back on when re-typing method chains, after being turned off

### ISSUE THREAD

**Issue by McYoloSwagHam** [fannheyward/coc-rust-analyzer#396]
after executing 
```
:CocCommand rust-analyzer.toggleInlayHints
```
the inlay hints turn off.

Though if I delete a method chain and retype the method the hints turn back on.

e.g.
```
SomeIter
                .zip(SomeOtherIter)
                .map(|(x, y)| (x.unwrap(), y.unwrap()))
                .collect();
```
here the inlay hints would be on, but after deleting the collect method and re-typing it, they'd turn on

**Comment by KouAkitaki** [comment]
I'm experiencing the same issue. The inlay hints are turned back on upon hitting `o` to open a new line in the middle of a chain.

```Rust
self.records
    .into_iter() // Pressing `o` with cursor at here turns on the hints
    .filter_map(|raw| Record::from_raw(raw).ok())
```
