### ISSUE TITLE
diagnostics not showing

### ISSUE THREAD

**Issue by ludwj61** [fannheyward/coc-rust-analyzer#401]
Hi, when using this extension, I noticed that errors/warnings are not getting underlines or descriptions when I hover over them.

This is what happens with coc-rust-analyzer:
![image](https://user-images.githubusercontent.com/42984254/94840129-f18ee500-03e5-11eb-844b-4ce289769d10.png)

In contrast, this is what happens in coc-java and other LSPs:
![image](https://user-images.githubusercontent.com/42984254/94840076-de7c1500-03e5-11eb-89dc-6041f336e5fe.png)

I am using the latest plugin and neovim nightly, as well coc.nvim development branch.

**Comment by fannheyward** [comment]
What's `:CocCommand rust-analyzer.serverVersion` output?

**Comment by ludwj61** [comment]
That command shows: ``[coc.nvim] rust-analyzer 277488b``

**Comment by ludwj61** [comment]
Also, I just noticed this error in ``CocInfo`` which sounds like it could be related.
![image](https://user-images.githubusercontent.com/42984254/94932830-96b5c600-0497-11eb-93a8-38259743d1da.png)

**Comment by fannheyward** [comment]
Yes, you need to do saving for rust-analyzer to work.
