### ISSUE TITLE
thiserror seems broken (import error)

### ISSUE THREAD

**Issue by mysteriouspants** [fannheyward/coc-rust-analyzer#407]
I use the crate [thiserror](https://crates.io/crates/thiserror) in my project, which apparently uses a proc macro. This creates an import error with rust-analyzer. On VSCode's rust-analyzer integration these can be resolved by adding the configuration:

```json
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true
}
```

However, when using coc-rust-analyzer, the recommended configuration does not have the same effect. The following is my coc-config as found by using :CocConfig. This seems to be the configuration suggested by https://github.com/fannheyward/coc-rust-analyzer#configurations, though I may have misunderstood something somewhere.

```json
{
  "rust-analyzer.cargo.loadOutDirsFromCheck": true,
  "rust-analyzer.procMacro.enable": true
}
```

I've boiled this down to a small reproduction.

`main.rs`:

```rust
use thiserror::Error; // this line is seems to be divergent in coc-rust-analyzer
// cargo-check is clean, but coc-rust-analyzer shows "unresolved import."

#[derive(Debug, Error)]
enum MyError {
    #[error("Oops error with message {0}")]
    Oops(#[from] std::num::ParseIntError)
}

fn foo() -> Result<u32, std::num::ParseIntError> {
    "one".parse::<u32>()
}

fn main() -> Result<(), MyError> {
    foo()?;
    Ok(())
}
```

`Cargo.toml`:

```toml
[package]
name = "cocraprocmacrorepro"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
thiserror = "1.0.21"
```

Observed on coc-rust-analyzer 0.9.0 with nvim 0.4.3.

**Comment by fannheyward** [comment]
It's very likely a rust-analyzer issue.

Tested with this example with RA+VSCode.

1. `code .` open the project
2. open `main.rs`, no errors
3. Quit VSCode
4. `code .` again, this will open `main.rs` directly, as we quit VSCode with `main.rs` opened. There is an `unresolved import.` error.

**Comment by fannheyward** [comment]
Another test with coc-rust-analyzer:

1. touch `src/bar.ts`, an empty rust module
2. `vim src/bar.ts`, this will activate coc-rust-analyzer and start RA server
3. `:e src/main.rs`, no errors

This is not coc-rust-analyzer's issue.

**Comment by mysteriouspants** [comment]
I restarted VSCode, it downloaded a new version of r-a, and now that's got the bug, too. It looks like the rust-analyzer project is aware of the issue. https://github.com/rust-analyzer/rust-analyzer/issues/6053

Thanks for looking into this, I appreciate it!
