### ISSUE TITLE
cannot jump to code generated by tonic grpc

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#417]
See also: https://github.com/rust-analyzer/rust-analyzer/issues/5799

I tested it works in Vscode but not with coc.nvim + coc-rust-analyzer

**Comment by fannheyward** [comment]
Please provide steps to reproduce this issue with coc-rust-analyzer.

**Comment by GopherJ** [comment]
Hi @fannheyward here are the steps to reproduce:
```
git clone https://github.com/hyperium/tonic
cd tonic/examples/src/helloworld
vim client.rs
```

**Comment by fannheyward** [comment]
`jumpDefinition` on `say_hello` will goto server.rs L15, `async fn say_hello`, does this is your expect?

Tested with VSCode, can't jump on `say_hello`.

**Comment by GopherJ** [comment]
@fannheyward are you able to jump to HelloRequest?  I seem to give you a bad example. 


The problem that I'm having is: I cannot jump to type defined by proto file. 

VScode works well on this point you may need add some configs

**Comment by fannheyward** [comment]
Do you means `./target/debug/build/helloworld-tonic-06a6a2f05b82a4ad/out/helloworld.rs` file, which defined `HelloRequest` struct?

I can't jump to this with VSCode, with `"rust-analyzer.cargo.loadOutDirsFromCheck": true`

**Comment by GopherJ** [comment]
@fannheyward yes I mean that file. I cannot jump into it using coc-rust-analyzer but I succeed with VSCode, maybe it's related to version of RA and your rustup channel

**Comment by fannheyward** [comment]
Tested with RA nightly + rustup nightly + VSCode, still don't work...

**Comment by lnicola** [comment]
@fannheyward did you enable proc macro and build script support?

**Comment by lnicola** [comment]
Actually, it doesn't work for me either :confused:.

**Comment by GopherJ** [comment]
Strange it worked for me some days ago...
