### ISSUE TITLE
Support for customizing inlay hints format

### ISSUE THREAD

**Issue by ddnomad** [fannheyward/coc-rust-analyzer#449]
Hey, I'd love to have a way to set a prefix for inlay hints, similar to `codeLens.separator` in COC. As it is right now, I feel it's too crowded when I have EOL symbols enabled (which I do prefer).

Any chance this can be added?

![image](https://user-images.githubusercontent.com/6703766/97722255-1e144a80-1ad3-11eb-8915-ec7abe6145b2.png)

**Comment by fannheyward** [comment]
Added `rust-analyzer.inlayHints.chainingHintsSeparator`, default `‣`.
