### ISSUE TITLE
Convert markdown documentation to plain text

### ISSUE THREAD

**Issue by Saecki** [fannheyward/coc-rust-analyzer#450]
Markdown documentation is awesome in IDEs where it can be rendered but in vim it really takes away the readability. I would love if the markdown could be converted to plain text to get rid of `<br/>`s, unnecessary line breaks that are just there because of the formatting of the documentation etc.. There are other elements that I think could stay like `#` infront of headings but the headings could maybe be highlighted in another color or underlined.
I took a look at the code but since I'm not really familiar with javascript or the LSP I didn't see an obvious way to implement this.

**Comment by fannheyward** [comment]
coc.nvim will rework markdown document highlighting, https://github.com/neoclide/coc.nvim/issues/2497

**Comment by Saecki** [comment]
Sorry I missed that.
