### ISSUE TITLE
Asks for downloading a new version of rust-analyzer because it can't detect the current version

### ISSUE THREAD

**Issue by sdroege** [fannheyward/coc-rust-analyzer#451]
Every time I open a Rust file in vim I get the "Rust Analyzer has a new release: 2020-10-26, you're using an unknown release. Would you like to download from GitHub" dialog.

```sh
$ ~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --version
rust-analyzer eae54b5
```

So maybe the problem is that recent releases don't contain any date?

**Comment by fannheyward** [comment]
Do you have `coc-rust-analyzer|global` field in `~/.config/coc/memos.json`? coc-rust-analyzer stores the release tag in this file.

**Comment by sdroege** [comment]
Thanks, there was the problem. That json file was apparently corrupted by some other coc extension and was not valid json :) Deleting it and having it re-created solved this problem.
