### ISSUE TITLE
Requires Cargo.toml to be in root of git repo

### ISSUE THREAD

**Issue by Darksonn** [fannheyward/coc-rust-analyzer#46]
When trying to use coc in a project that isn't at the root of the git repo, I get this error:

```
[coc.nvim] Couldn't find 'Cargo.toml' in /home/alice/src/server/Cargo.toml
```

While the `Cargo.toml` is located one directory deeper in the current working directory.

**Comment by fannheyward** [comment]
The `Cargo.toml` file is expected in workspace root, this is same as rust-analyzer VSCode: https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/src/commands/cargo_watch.ts#L23 , does VSCode works for your project?

Also, you can use this workaround: 

1. add `Cargo.toml` to `coc.preferences.rootPatterns` coc-settings: `"coc.preferences.rootPatterns": [".git", "Cargo.toml"]`
2. cd to sub directory that `Cargo.toml` located
3. vim to open your rust project

**Comment by Darksonn** [comment]
I've never used VSCode, I switched from deoplete with vim-racer. Anyway your workaround works great. Thanks for the help.

**Comment by dessalines** [comment]
For me, this was:

`"coc.preferences.rootPatterns": [".git/server", "Cargo.toml"]`

**Comment by dessalines** [comment]
Is there a way to add multiple root patterns? For one project, my `Cargo.toml` will be at `.git`, and others it might be at other locations.
