### ISSUE TITLE
how to config it on windows

### ISSUE THREAD

**Issue by Kengyen** [fannheyward/coc-rust-analyzer#464]
I've downloaded the executable for window "rust-analyzer-windows.exe" and put it in coc extensions under "coc-rust-analyzer-data" folder. then I configure the "coc-settings.json" like this:

```json
"rust-analyzer.serverPath": "/c/Users/admin/AppData/Local/coc/extensions/coc-rust-analyzer-data/rust-analyzer-windows.exe"
```

but it's not working.

it always ask me to download rust-analyzer but download the wrong one that can't even run.
please advise thx.

**Comment by fannheyward** [comment]
Sorry, I don't have a Windows env to reproduce this.

> download the wrong one that can't even run.

What do you mean `the wrong one`?

**Comment by Kengyen** [comment]
> 
> 
> Sorry, I don't have a Windows env to reproduce this.
> 
> > download the wrong one that can't even run.
> 
> What do you mean `the wrong one`?

it download an executable named "rust-analyzer.exe" and when I open a .rs file it tells:
Rust Analyzer is not found, download from GitHub release?
I did download it. can't figure out why xd.

**Comment by fannheyward** [comment]
Remove `rust-analyzer.serverPath` from your coc-settings.json and try again.

**Comment by Kengyen** [comment]
> 
> 
> Remove `rust-analyzer.serverPath` from your coc-settings.json and try again.

Thx so much it worked! but I still have no idea why it's no working when I add `serverPath` to the config file xd.
