### ISSUE TITLE
Error on applyEdits: Create document file: file:///home/cheng/Project/Rust/ruuls-rs/src/lib.rs timeout after 1s

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#465]
![image](https://user-images.githubusercontent.com/33961674/98829301-5738ad00-2439-11eb-9196-22c9b1f67625.png)

Reproduce steps:

1. git clone https://github.com/GopherJ/ruuls-rs
2. cd ruuls-rs && vim src/ruuls-rs
3. go to line 91: https://github.com/GopherJ/ruuls-rs/blob/65afdd4c4d8d4422a22c0d9025993f9c0f2c24a0/src/ruuls.rs#L91
4. run `rename symobol` action on `Rule::check` method

**Comment by GopherJ** [comment]
This will also happen if we run `rename symbol` action on line 119, when I rename `Rule::NumberOf` to `Rule::MinMet`

**Comment by GopherJ** [comment]
rust-analyzer: `111cc34`
rustc: `rustc 1.43.0 (4fb7144ed 2020-04-20)`

**Comment by fannheyward** [comment]
Can't reproduce, try to upgrade your coc.nvim to latest release.

**Comment by GopherJ** [comment]
@fannheyward Wow latest coc.nvim looks awesome! It works thanks
