### ISSUE TITLE
[Feature Request] Support for rustc --explain

### ISSUE THREAD

**Issue by elkowar** [fannheyward/coc-rust-analyzer#467]
When hovering over an Error / looking at an error, it would be nice if there was an easy way to open the output of `rustc --explain ERROR_ID`.

After some initial looks at the code, this could be pretty easily implemented as a new command that just runs `rustc --explain`.

Would you be willing to merge a PR for this feature? (seeing that it's not currently provided by rust-analyzer, but would be implemented by running the rustc binary)
If so, i'd be happy to try and implement this!

**Comment by fannheyward** [comment]
Yes, PR is welcome.

**Comment by elkowar** [comment]
Nice @fannheyward! I already have a working proptotype, main thing i'm unsure about is how to best display it. Currently i'm opening a new buffer and setting that buffers filetype to markdown, which i feel like is not the best UX. Optimally, do you reckon that the best option would be using the same popup that is also used for documentation in autocompletion, etc? there we'd have full rust syntax highlighting as well, which would definitely be nice. 

If so, could you give any tips as to where to look for how to use that popup? I couldn't really find any proper documentation on the related coc.nvim api (yet) ^^'

**Comment by fannheyward** [comment]
I prefer to use a new buffer instead of popup window.

> which i feel like is not the best UX

What's the UX problem? markdown code formats error ?

**Comment by fannheyward** [comment]
You can check https://github.com/neoclide/coc.nvim/blob/master/src/model/floatFactory.ts#L133 for floating window usage.

**Comment by elkowar** [comment]
> I prefer to use a new buffer instead of popup window. There are already too many popup/floating windows, completion docs, diagnostics, code actions, etc. We also need to care about popup/floating window size, but `rust --explain` returns long content, I think it's better to use buffer.
> 
> > which i feel like is not the best UX
> 
> What's the UX problem? markdown code formats error ?

I guess I'll make it configurable then, if you're okay with that ;D I generally prefer minimizing the amount of necessary context switches, and enjoy the format of popup windows more than having a new buffer that i need to close again. 

The main UX issue i see is that Markdown syntax highlighting generally does not include actual code highlighting (and  IIRC (can't check rn) the `rustc --explain` output does not include the specific ```rust annotation.) Thus, in the separate buffer, the code samples will be less readable. 


Thanks for the link!

**Comment by fannheyward** [comment]
closed by #469
