### ISSUE TITLE
coc-rename on multiple buffers failing with last rust-analyzer update

### ISSUE THREAD

**Issue by ericpubu** [fannheyward/coc-rust-analyzer#482]
With 2020-11-23 rust analyzer release, there is an error using coc-rename if the element to rename has references on other buffers, the following error occurs:
```
[coc.nvim] Error on applyEdits: Invalid document change: {
  "edits": [
    {
      "newText": "new_function",
      "range": {
        "end": {
          "character": 29,
          "line": 1778
        },
        "start": {
          "character": 12,
          "line": 1778
        }
      }
    }
  ],
  "textDocument": {
    "uri": "file:///filepath.rs"
  }
}
```

before this release, coc showed that a file would be loaded, and change the corresponding buffers.
If I open manually each buffer, then the rename works 

Observed on: 
OS: macOS Catalina and manjaro linux
nvim 0.4.4

**Comment by fannheyward** [comment]
Can't reproduce, please upgrade your coc and try again.

**Comment by ericpubu** [comment]
> Can't reproduce, please upgrade your coc and try again.

coc is upgraded, and coc-rust-analyzer on the latest version, 0.17.0
Still seeing the same behavior, it only works if I open each file where the element is referenced.

I know is not a coc.nvim issue, as coc-go works as expected

**Comment by ericpubu** [comment]
I just tested on vscode, same error, seems like a server error, I'll create the issue on the rust-analyzer repo
