### ISSUE TITLE
Add configration support for `rust-analyzer.inlayHints.maxLength` 

### ISSUE THREAD

**Issue by shekohex** [fannheyward/coc-rust-analyzer#485]
We need to configure the `InlayHints` `maxLength` since this looks so messy.

![Screenshot](https://user-images.githubusercontent.com/14620076/100467796-0aa4d100-30cb-11eb-8c44-921311e5304e.png)

**Comment by fannheyward** [comment]
What do you expect with maxLength? Cut the message?

**Comment by shekohex** [comment]
Yes, this option is already supported by rust-analyzer it self, the option is sent in the initialization phase along with other configuration.

The server then instead of sending the Full Chain .. it gets truncated (somehow internally in RA) and send it back ready to be viewed as is .. so to implement this, we just need to send this option and we are done, nothing really need to be done in the client side.

I could make a PR to implement this (it's too easy btw), but I don't know how to make CoC use the local development version instead of the one on npm.

**Comment by shekohex** [comment]
That was fast, thank you!
