### ISSUE TITLE
quickfix is broken

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#492]
Hi, just found quick fix is broken:

![Peek 2020-12-04 14-12](https://user-images.githubusercontent.com/33961674/101168222-67f4d100-363b-11eb-88b4-6038823cd527.gif)

I can reproduce with the following code:

```rust
use std::thread; // put cursor in the middle and call coc quick fix action gives no quick fix available

fn main() {
    println!("Hello, world!");
}
```

**Comment by GopherJ** [comment]
coc-rust-analyzer: `0.19.0`

**Comment by fannheyward** [comment]
`CocFix` does `:CocAction quickfix`, where `quickfix` will be used to filter the codeActions.

`coc-codeaction-selected` and `coc-codeaction-line` works.

**Comment by GopherJ** [comment]
ok let me try it, thanks

**Comment by GopherJ** [comment]
@fannheyward it didn't work, I think there must be some upstream changes on `coc.nvim` or `coc-actions`.

I tried both `coc-codeaction-line` and `coc-codeaction-selected`, it didn't work anymore. However, it was working perfectly one week ago

**Comment by GopherJ** [comment]
@fannheyward I just tried the same thing works for `typescript` but not with `rust`

![Peek 2020-12-07 09-37](https://user-images.githubusercontent.com/33961674/101328211-05384b00-3870-11eb-9020-c69d13e05349.gif)



![Peek 2020-12-07 09-38](https://user-images.githubusercontent.com/33961674/101328223-08cbd200-3870-11eb-9aa5-99ae44c6a1ea.gif)

**Comment by fannheyward** [comment]
<img width="451" alt="截屏2020-12-07 16 54 39" src="https://user-images.githubusercontent.com/345274/101329871-e73d0b80-38ac-11eb-8015-28eaed5e6cf4.png">

Use `coc-codeaction-selected`. Tested with VSCode + rust-analyzer, same result.

**Comment by fannheyward** [comment]
Tested with VSCode + rust-analyzer, same result.

**Comment by fannheyward** [comment]
> same thing works for `typescript` but not with `rust`

Looks like it's a rust-analyzer issue, because the client has the same request.

**Comment by EdmundsEcho** [comment]
Quick request for clarification: 

There are essentially three ways to to have automagically update our code:
1. coc-format-xxx
2. coc-fix-xxx
3. coc-codeaction-xxx

To describe what gets updated (the xxx), there are three qualifiers
1. `selected`
2. `line`
3. unqualified (and deprecated/unsupported for some languages, e.g., rust-analyzer)

#### CodeActions - used in several different contexts
1. the coc-extension `coc-actions` was used to enable VS Code code-actions

    * The `[coc-actions](https://github.com/iamcco/coc-actions)` extension is essentially deprecated.  This is true because anyone using the latest nvim can benefit from the improved popup. Is that correct?

     * What remains unclear is whether the commands it supported are now part of another extension.  For instance, should I get rid of `coc-codeaction-line` and `coc-codeaction-selected`? (not to mention what I believe was deprecated for different reasons: `coc-codeaction`).

2. coc-nvim uses `CocAction`.   Unlike, `CocCommand`,  without the capacity to `CocList` the active  "actions"  for `CocAction`, I'm left with snippets here and there that describe what I believe remains supported: `CocAction quickfix`.

    *  coc-nvim uses 'coc-codeaction-selected', 'coc-codeaction-line' and *'coc-codeaction'*
        ```vimscript
        nnoremap <Plug>(coc-codeaction-selected)   :<C-u>set        operatorfunc=<SID>CodeActionFromSelected<CR>g@
        nnoremap <Plug>(coc-codeaction-line)       :<C-u>call       CocActionAsync('codeAction', "n")<CR>
        nnoremap <Plug>(coc-codeaction)            :<C-u>call       CocActionAsync('codeAction', "")<CR>
        ```

     * coc-nvim supports 'coc-fix-current', but nothing else
        ```vimscript
        nnoremap <silent> <Plug>(coc-fix-current)           :<C-u>call       CocActionAsync('doQuickfix')<CR>
        ```

       * coc-nvim supports 'coc-format', but nothing else
       ```vimscript
        nnoremap <silent> <Plug>(coc-format)                :<C-u>call       CocActionAsync('format')<CR>
        ```

        * Other places where `CocAction` shows up in `coc-nvim`: 
            * `CocAction` is a coc-nvim function
                It does not process any errors so will fail silently (I believe) in the event we send an unsupported command.  Is that right?
                   ```vimscript
                   function! CocAction(name, ...) abort
                   ```
              * Several fix-related capacities utilize `CocAction` or `CocActionAsync`:
                  * `coc-codelens-action` uses CocActionAsync
                    ```vimscript
                     nnoremap <Plug>(coc-codelens-action)       :<C-u>call       CocActionAsync('codeLensAction')<CR>
                     ```

                  * `coc-fix-current` uses CocActionAsync
                    ```vimscript
                     nnoremap <silent> <Plug>(coc-fix-current)           :<C-u>call       CocActionAsync('doQuickfix')<CR>
                     ```


3. Finally, the terminology `code action` has meaning in the `rust-analyzer` world.  It provides essentially, snippet-like capacity that benefits from information in the type-checker. 
    * coc-rust-analyzer uses the `CodeAction`
        ```
        import { ClientCapabilities, CodeAction, CodeActionParams, CodeActionRequest, Command, InsertTextFormat, 
        TextDocumentEdit } from 'vscode-languageserver-protocol';
        ```


`CocFix` is in a category on its own.  In practice, it seems to be the single gateway a user can rely on to generate the fixes, code expansions/substitutions etc... Is that right? 

`CocFix` uses vim quickfix; is a coc-nvim command
```vimscript
command! -nargs=* -range CocFix    :call coc#rpc#notify('codeActionRange', [<line1>, <line2>, 'quickfix'])
```

What I'm hoping to accomplish, is clarity on what the `coc-nvim` interface is and how to use it in the vim config.  In addition, how much of that interface is supported by the rust-analyzer.  This way, I hope to have a full inventory of the feature set and how to configure it "with confidence" :))

Any comments or clarifications as you see fit would be welcome.

\- E

**Comment by fannheyward** [comment]
@EdmundsEcho I'll try to explain your questions, but I don't know I understand your questions correctly.

> is clarity on what the coc-nvim interface is and how to use it in the vim config. 

It seems to me that your question is what are these features coc.nvim provides and how to use them, yes?

The main point is `CodeAction`. It's provided by language server, for example `rust-analyzer`, to edit your code. For example, your code is missing a package import, LS can provide an action to add the missing import, or your code has an error at line 10, LS provide an action to fix it.

What coc.nvim does is requesting LS with some code, if LS responses a `CodeAction`, coc.nvim applies it to your code, that's all.

- `coc-codeaction-selected`: coc.nvim does requesting with _selected_ code, you need to do selections first
- `coc-codeaction-line`: coc.nvim does requesting with current line code
- `coc-codeaction`: coc.nvim does requesting with whole current buffer
- `coc-fix-current`: coc.nvim does requesting to LS for current line code for only `quickfix` kind `CodeAction`
- `CocFix` does the similar things, requests with lines code for `quickfix` only.
- `CocAction` is a command to do special request

> In addition, how much of that interface is supported by the rust-analyzer.

All, rust-analyzer provides lots of CodeAction.

> The [coc-actions](https://github.com/iamcco/coc-actions) extension is essentially deprecated.

The main feature of coc-actions is displaying actions list in floating window, latest coc.nvim has added this, you don't need it.

**Comment by fannheyward** [comment]
@EdmundsEcho `:h coc-nvim.txt@en`

**Comment by EdmundsEcho** [comment]
Thank you!  Is there a way to generate a list of the available 'coc-actions' similar to the way we can list the commands with `CocList commands`? How are 'coc-actions' different from 'commands' and when do they overlap?

**Comment by GopherJ** [comment]
@EdmundsEcho commands don't communicate with language server but just extensions features.

You can see the README.md to know more
