### ISSUE TITLE
some code actions are broken in coc-rust-analyzer 0.19.0

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#500]
Ref: https://github.com/rust-analyzer/rust-analyzer/issues/6753

**Comment by GopherJ** [comment]
I tested things work using coc-rust-analyzer 0.8.0 + latest rust-analyzer, but code actions like quickfix dont work anymore in coc-rust-analyzer

**Comment by fannheyward** [comment]
> coc-rust-analyzer 0.8.0

Do you mean 0.18.0?

**Comment by GopherJ** [comment]
@fannheyward No I mean `0.8.0`, I used `npm view  coc-rust-analyzer versions --json` to find versions and used `0.8.0`

**Comment by fannheyward** [comment]
Try v0.20.0

**Comment by GopherJ** [comment]
@fannheyward thanks, it worked.

BTW can I ask what `parentModule` command is for? I always got an error when I run it:

![image](https://user-images.githubusercontent.com/33961674/101686813-dab1e200-3a69-11eb-8dc7-1b0c3306d19d.png)

**Comment by fannheyward** [comment]
https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/parent_module.rs#L64

```rust
mod foo {
    mod bar {
        mod baz {  }
    }
}
```

Fire `:CocCommand rust-analyzer.parentModule` at `baz`, will jump to `bar`.

**Comment by GopherJ** [comment]
![Peek 2020-12-10 10-43](https://user-images.githubusercontent.com/33961674/101754902-8db72580-3ad4-11eb-8e3b-0503ae6e73c7.gif)

@fannheyward I still get errors, I'll try to upgrade coc.nvim but I think I'm already using latest coc.nvim because I keep it up to date every day

**Comment by GopherJ** [comment]
@fannheyward Never mind, I pull latest coc.nvim manually from `~/.vim/plugged/coc.nvim` now it started working! Thanks
