### ISSUE TITLE
Handle RA indexing in middleware

### ISSUE THREAD

**Issue by fannheyward** [fannheyward/coc-rust-analyzer#506]
coc supports WorkDoneProgress notification in popup windows, RA will do indexing and send notifications on every edit, this is annoying. coc-rust-analyzer can handle the indexing notification in middleware.

**Comment by kyle-mccarthy** [comment]
Do you know if it is possible to hide the notification or at least change where it appears (such as in the status bar)? As of right now it is a little overwhelming/distracting.

![2020-12-11 17 07 44](https://user-images.githubusercontent.com/7758522/101963183-b114ca00-3bd3-11eb-80b9-a8869c5dd86b.gif)

**Comment by fannheyward** [comment]
Set `workspace.progressTarget` to `statusline`.

**Comment by faraazahmad** [comment]
Thank you! @fannheyward I've been searching around how to fix this bug thinking it was caused by syntastic or rust.vim

**Comment by fannheyward** [comment]
Latest coc.nvim release has removed the WorkDoneProgress notification.
