### ISSUE TITLE
Rustfmt Support

### ISSUE THREAD

**Issue by jasonkena** [fannheyward/coc-rust-analyzer#51]
Just like https://github.com/neoclide/coc-rls

**Comment by fannheyward** [comment]
Do you have rustfmt installed?

rust-analyzer has built in rustfmt support. In coc.nvim, you can use `:call CocAction('format')` to format whole document.

**Comment by jasonkena** [comment]
Thanks! It works

**Comment by fannheyward** [comment]
Tips: you can add rust to `"coc.preferences.formatOnSaveFiletypes"`, this will auto format on save.

**Comment by haze** [comment]
@fannheyward sorry to bump a closed issue, but I happen to be getting a lot of `willSaveTimeout ` errors on a simple mis-indented file, is there anything I can do to alleviate this?

**Comment by fannheyward** [comment]
@haze sorry for the delay response, could you post the full error messages? Maybe you can open a new issue.
