### ISSUE TITLE
How display docs for word under the cursor in a pop-up

### ISSUE THREAD

**Issue by EdmundsEcho** [fannheyward/coc-rust-analyzer#512]
I'm loving the virtual text display of the types while I work away at the code.

When I use `coc-nvim` in other languages, I can show the docs, types etc., using `K` in normal mode.  It does not work for `coc-rust-analyzer`  This said, when I'm typing, I get the pop-up with everything I would expect.

How can I show the same information "on command"?

**Comment by GopherJ** [comment]
@EdmundsEcho it should work
![image](https://user-images.githubusercontent.com/33961674/101989329-f1da1500-3c9f-11eb-9fb4-d834dab07d03.png)

**Comment by EdmundsEcho** [comment]
Thank you.  I made a mistake when I updated my config...

I have the `K -> document` in popup working now.

```vimscript
nnoremap <silent> K :call CocAction('doHover')<CR>
```

How did you generate the list of commands in the `quickfix` window whilst in "insert" mode?
