### ISSUE TITLE
Doc popup is immediately closed by the opening of the "indexing..." and other modals

### ISSUE THREAD

**Issue by sudoforge** [fannheyward/coc-rust-analyzer#515]
Hey there. The documentation popup (is there a canonical name for this?) opens and is immediately closed, by what I'm guessing is the appearance of the "indexing..." and other popups (recording below). This only occurs in rust files, which is why I'm posting this issue here. A couple questions...

* Is there a way to avoid displaying the "indexing..." and related popups? (I don't like them anyway and would rather not see them at all, even if I didn't have this issue)

* Can anyone point me in the right direction for resolving this issue?

![output](https://user-images.githubusercontent.com/3893293/102040571-6ab59b80-3d8a-11eb-9268-0bbf6fbc03e2.gif)

**Comment by fannheyward** [comment]
Upgrade your coc.nvim to latest release.

**Comment by sudoforge** [comment]
Huh, that did it. I run off of `release` directly and update fairly regularly, but just started using this extension, so I didn't correlate it to a coc.nvim issue.

```
➜ git rev-parse HEAD
df7b5d4f4e64d5dc2fa24dbf8143109afa93539c

➜ git rev-list ...@{u}
1fe1e02eca07fe1fbe9427e2e8a1b29289f281be
2476d24473aa01c68012e06a23da83515696a523
8e39d10ce98f08378554d655de1282da5670aefe
4d191c5f146c563477ce9815db9a322398116b83
1f9d18eeabb104d8f617c166e843f826c2e06bff
94bdd76dec4516dbb35f57aa2d99023de1403739
```

Thanks for the pointer!
