### ISSUE TITLE
better handling of executable args in debugSingle

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#516]
currently coc-rust-analyzer passes only two arguments to debugger:

- executable
- args

executable is fine, but args doesn't work well yet

If we would like to run specific test under cursor, often RA will return something like:

```
executableArgs: ["mod_name::tests::test_name", "--exact", "--nocapture"]
```

combining with executable the final command will be like:

```
/home/xxx/package_name/target/debug/deps/package_name-f2718b21135e7a89 "mod_name::tests::test_name --exact --nocapture"
```

this will be an invalid command because `/home/xxx/package_name/target/debug/deps/package_name-f2718b21135e7a89` needs to have execute kind:

- `--test`

- `--bench`

etc

However, even if we add `--test` OR `--bench` to run like:

```
/home/xxx/package_name/target/debug/deps/package_name-f2718b21135e7a89 "--test mod_name::tests::test_name --exact --nocapture"
```

it's still an invalid command because executable will treat `--test mod_name::tests::test_name --exact --nocapture` as a single option...which doesn't exists

**Comment by GopherJ** [comment]
See also: https://github.com/rust-analyzer/rust-analyzer/issues/6872

**Comment by GopherJ** [comment]
is there a way to pass an array to vimspector?

so the command can be converted into:

```
/home/xxx/package_name/target/debug/deps/package_name-f2718b21135e7a89 "--test" "mod_name::tests::test_name" "--exact" "--nocapture"
```

which is correct

**Comment by puremourning** [comment]
I have no idea what this has to do with Vimspector, but the answer is likely in the docs. https://puremourning.github.io/vimspector/configuration.html#the-splat-operator

**Comment by GopherJ** [comment]
@puremourning sorry didn't find this feature exists in vimspector.

Now it works with the following config:

```
{
    "configurations": {
        "codelldb - launch": {
            "adapter": "CodeLLDB",
            "configuration": {
                "type": "lldb",
                "request": "launch",
                "program": "${Executable}",
                "args": ["*${Args}"]
            }
        }
    }
}
```
