### ISSUE TITLE
weird signature for std function?

### ISSUE THREAD

**Issue by naps62** [fannheyward/coc-rust-analyzer#525]
This is what my vim was showing as the documentation floating window for `std::result::Result::map_err`:

![image](https://user-images.githubusercontent.com/283819/102219468-6cd94080-3ed7-11eb-975f-a379d4bc46da.png)

I ended up searching for a bit to try and understand what that `?0.3` syntax was all about. It was completely new to me.
When I went back to my code, it was now showing the proper signature, as it shows on official docs.

Asked on Rust discord as well, and was told `it means there is a bug in the program you're using to display the doc.`

**Comment by GopherJ** [comment]
emm I reproduced this: 
![image](https://user-images.githubusercontent.com/33961674/102233426-8c309780-3ef0-11eb-8b3f-9e1d7a12f91c.png)

**Comment by fannheyward** [comment]
Can't reproduce, the document is came from rust-analyzer, you can check it as follow:

1. `"rust-analyzer.trace.server": "verbose"` in coc-settings.json
2. `:CocCommand workspace.showOutput`, choose `Rust Analyzer Language Server Trace`
3. search `textDocument/hover`

**Comment by GopherJ** [comment]
@naps62 @fannheyward this weird signature comes from RA:


![image](https://user-images.githubusercontent.com/33961674/102656860-e5106200-4174-11eb-970d-7c803e2a8def.png)
