### ISSUE TITLE
[Enhancement] terminal startinsert

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#526]
Hi, is it possible to make runsingle's terminal starts in insert mode? that'll be easier to use mappings of `tnoremap` make sense and users can also type other commands if they want

**Comment by GopherJ** [comment]
but also I'm wondering if this is intentional so that coc-rust-analyzer can keep track of this open terminal? If we close it manually will it cause issues?

**Comment by GopherJ** [comment]
with this I can have some mappings to exit quickly:

```
    tnoremap <Esc> <C-\><C-n>:bd!<CR>
```

without typing `:q` which is annoying

also I can execute other commands

**Comment by GopherJ** [comment]
Now to solve this I have to type `A` after entering the terminal created by coc-rust-analyzer

**Comment by fannheyward** [comment]
Set `rust-analyzer.terminal.startinsert` to true.
