### ISSUE TITLE
Great productivity tool - Advice on how to speed it up

### ISSUE THREAD

**Issue by EdmundsEcho** [fannheyward/coc-rust-analyzer#527]
I'm beginning to see a good amount of lag in the nvim responsiveness (delay screen refresh when typing).  Is there any advice on wha to do to trim down the linting capacity.  I suspect there is a way to limit the directories it uses to inform the lints? I suspect it is getting large as the dependencies in the project grow.  Thank you in advance for any guidance here.  \- E

PS: I have updated to the latest node and otherwise done what I can from other sources.

**Comment by GopherJ** [comment]
@EdmundsEcho Actually I think the lag doesn't come from nodejs && coc.nvim && coc-rust-analyzer, because while using coc.nvim for projects like go, typescript. things are super fluent.

The lag comes more from rust-analyzer, which consumes > 1GB of your memory and indexing on background. After your changes, rust-analyzer will rerun cargo check also which can cause instant high CPU usage...

I would say rust is not IDE yet, hope the next year it can be...

**Comment by fannheyward** [comment]
Use latest rust-analyzer release and wait it to get better and better.

**Comment by EdmundsEcho** [comment]
Thank you for the response.  It is useful as it stops me from problem solving something that is, as you suggest, is out of our hands.  

The work that you are doing is *amazing*.  Truly.  My Rust programming experience is so much more productive; seeing the types in the virtual text - Great stuff.  

One other FYI, I have a function that pulls the docs into my pop-up using `K`. e.g., it works well with JS.  That functionality does not work with this extension... despite my seeing the docs when an active lint session kicks in.  Is this something that should work?

**Comment by fannheyward** [comment]
> I have a function that pulls the docs into my pop-up using `K`

@EdmundsEcho what's the function?

**Comment by EdmundsEcho** [comment]
I have it working now.  It was my mistake.  

Only to close out on the feature/functionality, I believe I'm using the recommended/default commands that `coc-nvim` provides.  

```vimscript
nnoremap <silent> K :call CocAction('doHover')<CR>
```
In normal mode it uses the popup to display any documentation associated with the symbol under the cursor.

Re speeding up: someone at the `rust-analyzer` repo suggested I essentially throttle the diagnostic to increase the render performance.  This improves the situation.

```json
  "diagnostic.messageDelay": 200,
```

There could be evidence that the issue could be solved with this plugin. Only you might know for sure.  I say that because the display "hangs" moving between  "normal" and "insert" modes; unique to vim/nvim?  The computation seems to be updating the type inference values.

Did what I describe make sense?

\- E

**Comment by fannheyward** [comment]
> `nnoremap <silent> K :call CocAction('doHover')<CR>`

It's recommend to use `s:show_documentation` function in https://github.com/neoclide/coc.nvim#example-vim-configuration, with fallback hover handle.
