### ISSUE TITLE
Virtual text no longer shows error

### ISSUE THREAD

**Issue by cloudhead** [fannheyward/coc-rust-analyzer#531]
Since updating, my virtual text diagnostics for errors aren't working the same anymore, instead of showing the first line of the error message, they show the second or third line, and the highlight color is no longer that of an error. This used to work fine.

Eg. the following error:

```
error[E0308]: mismatched types
    --> src/core/mod.rs:1170:9
     |
1120 |     pub fn read<F>(&mut self, fb: &Framebuffer) -> Vec<Bgra8> {
     |                                                    ---------- expected `Vec<Bgra8>` because of return type
...

1170 |         body
     |         ^^^^
     |         |
     |         expected struct `Vec`, found `&[Bgra8]`
     |         help: try using a conversion method: `body.to_vec()`
     |
     = note: expected struct `Vec<Bgra8>`
             found reference `&[Bgra8]`

```

Used to show as virtual text
```
mismatched types
```
with an error highlight,

But now shows just `try using a conversion method` with a non-error highlight

I've gone through all the settings but can't figure out how to get it working again.

Thanks

**Comment by fannheyward** [comment]
> This used to work fine

Do you mean the new release of coc-rust-analyzer breaks? Can you reproduce this with 0.21.0 ? Try `:CocInstall coc-rust-analyzer@0.21.0`.

**Comment by GopherJ** [comment]
@cloudhead it looks like an issue in your vim config, it works on my side

**Comment by cloudhead** [comment]
@GopherJ so you're seeing the error title as *virtual text*? It may be that there are no hints in the examples you tried?

What I'm seeing is that when there are multiple diagnostics for the same line of code, eg. in this case there's some hints, and also an error, it is showing the hint instead of the error, in the virtual text.

**Comment by GopherJ** [comment]
@cloudhead I believe rust-analyzer starts to show more hints & informations recently, you can try mine to see if it works for you: https://github.com/GopherJ/cfg/tree/master/coc

**Comment by cloudhead** [comment]
Thanks @GopherJ 

It appears that this fixed itself after the latest update to `coc-rust-analyzer` :man_shrugging: 

I'll re-open the issue if the problem re-surfaces. Thank you for the great plugin!
