### ISSUE TITLE
Failure with Latest Rust-Analyzer

### ISSUE THREAD

**Issue by willfindlay** [fannheyward/coc-rust-analyzer#532]
After updating to the December 21st version of rust-analyzer, I get the following:

```
[coc.nvim] The "rust-analyzer" server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

`:CocCommand rust-analyzer.serverVersion` returns `[coc.nvim] rust-analyzer 5e2935e`

Not really sure how to get any more useful info. If there is some other info that would be useful, feel free to ask.

**Comment by Iniesta8** [comment]
Same here.

Can I explicitly use an older (the second latest) version of rust-analyzer?

**Comment by mlodato517** [comment]
Not sure if this is useful but I ran `:CocCommand workspace.showOutput` and see
```
Failed to deserialize InitializeParams: missing field `changeAnnotationSupport`; # ...
```

**Comment by mnbbrown** [comment]
@Iniesta8  my workaround is to install an older release (i've done it via homebrew) and set a custom `serverPath` in `"~/.config/nvim/coc-settings.json"` via `:CocConfig`:

```
{
  "rust-analyzer.serverPath": "/usr/local/bin/rust-analyzer",
}
```

**Comment by willfindlay** [comment]
Thanks a lot for the workaround @mnbbrown.

**Comment by mnbbrown** [comment]
Looks like it has something to with incompatabilities between versions of the LSP... [https://github.com/rust-analyzer/rust-analyzer/pull/6779](https://github.com/rust-analyzer/rust-analyzer/pull/6779).

**Comment by dkvasnicka** [comment]
For Arch/Manjaro folks: `rust-analyzer 20201130-1` from the `community` repo + the above adjustment to the CoC config works as a workaround.

**Comment by nerdthatnoonelikes** [comment]
I've had no luck with this. I've tried downgrading my rust-analyzer but im still getting the same issues.

**Comment by willfindlay** [comment]
@nerdthatnoonelikes Make sure to double-check that the rust-analyzer at the path you put in your config is indeed a different/lower version. Mine works fine with the version from last week (December 14th instead of 21st).

**Comment by nerdthatnoonelikes** [comment]
@willfindlay how would I go about finding the path of the older rust-analyzer version.

**Comment by willfindlay** [comment]
> @willfindlay how would I go about finding the path of the older rust-analyzer version.

You would install it separately in a different path, then point to that in the coc.nvim config file. For example, I installed an older version in /usr/local/bin and then pointed to that.

**Comment by mpizenberg** [comment]
Here you can download the executable you need for the version of last week: https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-12-14

**Comment by Iniesta8** [comment]
You can also build it from source:

```
$ git clone https://github.com/rust-analyzer/rust-analyzer.git && cd rust-analyzer
$ git checkout tags/2020-12-14
$ cargo xtask install
```

It should build the rust-analyzer and install it to `~/.cargo/bin/rust-analyzer` by default.

Afterwards open your CocConfig (`:CocConfig`) and insert:
`
{ "rust-analyzer.serverPath": "~/.cargo/bin/rust-analyzer" }`

At last restart neovim!

**Comment by nerdthatnoonelikes** [comment]
> You can also build it from source:
> 
> ```
> $ git clone https://github.com/rust-analyzer/rust-analyzer.git && cd rust-analyzer
> $ git checkout tags/2020-12-14
> $ cargo xtask install
> ```
> 
> It should build the rust-analyzer and install it to `~/.cargo/bin/rust-analyzer` by default.
> 
> Afterwards open your CocConfig (`:CocConfig`) and insert:
> ` { "rust-analyzer.serverPath": "~/.cargo/bin/rust-analyzer" }`
> 
> At last, restart neovim!

Thank you. This finally worked for me.

**Comment by JBlackbeard** [comment]
I've opted to use the nightly version for the moment to get it working again by adding: 
`{"rust-analyzer.updates.channel": "nightly"}` 
to 
`"~/.config/nvim/coc-settings.json"`

Then run `CocCommand rust-analyzer.upgrade` to get the latest nightly version.

**Comment by dmaahs2017** [comment]
> I've opted to use the nightly version for the moment to get it working again by adding:
> `{"rust-analyzer.updates.channel": "nightly"}`
> to
> `"~/.config/nvim/coc-settings.json"`
> 
> Then run `CocCommand rust-analyzer.upgrade` to get the latest nightly version.

Thanks, this worked! 

Had to try a couple things like 
- restarting vim
-  `CocUninstall coc-rust-analyzer` then `CocInstall coc-rust-analyzer` 
then `CocCommand rust-analyzer.upgrade` worked.

**Comment by fannheyward** [comment]
Try v0.24.0

**Comment by tropxy** [comment]
> I've opted to use the nightly version for the moment to get it working again by adding:
> `{"rust-analyzer.updates.channel": "nightly"}`
> to
> `"~/.config/nvim/coc-settings.json"`
> 
> Then run `CocCommand rust-analyzer.upgrade` to get the latest nightly version.
> 
> Edit: Vim restart is required after modifying the json file!

As a tip you can edit the config settings by:
```shell
$ vim
:CocConfig
```
Which shall open the config settings directly

I have opted for the workaround of @JBlackbeard, but for the record, I also tried another alternative:

1. Uninstall coc-rust-analyzer -> :CocUninstall coc-rust-analyzer
2. Install previous stable version -> :CocInstall coc-rust-analyzer@0.23.0

This alternative also worked for me.

**Comment by MathieuDuponchelle** [comment]
@fannheyward I'm getting this exact same problem with 0.34.0 fwiw, I see that you've reverted the changes you made in the commit that fixed this in https://github.com/fannheyward/coc-rust-analyzer/commit/d85367b5aa481ac79381c81b4d4835f5c33c2ac5 , were they no longer necessary?

**Comment by fannheyward** [comment]
@MathieuDuponchelle yes, it's not necessary anymore.

**Comment by MathieuDuponchelle** [comment]
@fannheyward OK, any idea why I'm seeing the same output as reported in https://github.com/fannheyward/coc-rust-analyzer/issues/532#issuecomment-749010003 with 0.34.0? fwiw using 0.29.0 (the version immediately preceding the reversal), the crash no longer happens :)

**Comment by fannheyward** [comment]
@MathieuDuponchelle what's your rust-analyzer version? You can check it from `:CocCommand rust-analyzer.serverVersion`

**Comment by MathieuDuponchelle** [comment]
@fannheyward reupgraded to 0.34.0, `rust-analyzer 14de9e5`, but the creash no longer happens, how strange! Is it possible that the crash was preventing coc-rust-analyzer to upgrade its server?

**Comment by fannheyward** [comment]
@MathieuDuponchelle new release of `rust-analyzer` has fixed this issue. coc-rust-analyzer will try to fetch and upgrade to latest release of RA.

**Comment by MathieuDuponchelle** [comment]
@fannheyward ok gotcha, I'm simply wondering what could have caused CRA not to actually do that, I am quite sure that when I started looking at this, I had both `0.34.0` and the command you made me run returned the same hash as in https://github.com/fannheyward/coc-rust-analyzer/issues/532#issue-772209583 :)

I don't have any problem anymore (tnx), but maybe there's still a bug to fix where CRA won't do the upgrade if a "crash" is occurring in whatever version of RA is currently checked out :)
