### ISSUE TITLE
No way to disable "indexing" windows?

### ISSUE THREAD

**Issue by M0nenvoy** [fannheyward/coc-rust-analyzer#541]
![Capture](https://user-images.githubusercontent.com/75471030/103157132-bd1c9200-4764-11eb-8070-05dc21eaa73d.PNG)
"Indexing" window appears every time I type something, which is really annoying actually. I tried to disable this feature via CocConfig, but there is seemingly no such option..?

**Comment by fannheyward** [comment]
Upgrade your coc.nvim to latest release.
