### ISSUE TITLE
[Feature Request] Display cargo check progress, downloading & compiling crates etc

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#542]
RA needs to run `cargo check` first before starting indexing, and this can be very slow on a big project, and currently users are not notified what coc-rust-analyzer is doing.

Is it possible to add a status text for displaying `cargo check` progress like in vscode?
![image](https://user-images.githubusercontent.com/33961674/103181949-2f958b00-48a7-11eb-8cf1-815741d2cffc.png)

so that we know it's downloading and compiling the crate `autocfg`, RA doesn't start to do indexing yet.

**Comment by GopherJ** [comment]
the notification bar in https://github.com/neoclide/coc.nvim/pull/2689 looks good actually, what shall I do to activate it? (I would prefer having it only in statusline)

I checked `workspace.progressTarget`, it doesn't exist anymore

**Comment by GopherJ** [comment]
To reproduce:

1. git clone https://github.com/rust-lang/docs.rs/
2. cd docs.rs
3. vim src/lib

Then you'll find that RA doesn't start indexing, but if you check in `htop`, it's doing initiate `cargo check` and it'll take minutes.

**Comment by GopherJ** [comment]
![Peek 2020-12-28 01-01](https://user-images.githubusercontent.com/33961674/103182069-7e8ff000-48a8-11eb-9c72-65203c1a60e3.gif)

**Comment by fannheyward** [comment]
<img width="762" alt="截屏2020-12-28 09 47 38" src="https://user-images.githubusercontent.com/345274/103184185-c38c4480-48f1-11eb-8739-cfadab0893ed.png">

It's already supported.

**Comment by GopherJ** [comment]
@fannheyward but how can I have it? I didn't have it yet. https://github.com/GopherJ/cfg/blob/master/coc/coc-settings.json

**Comment by GopherJ** [comment]
@fannheyward Ok I find it, we are talking about different things actually. I do have `cargo check` notification if the first `cargo check` has been done, but if I first load an empty project, `cargo check` will run in background without any notification to frontend

**Comment by fannheyward** [comment]
@GopherJ rust-analyzer doesn't return any message/progress in this case, we can do nothing.

What you seen in VSCode is same as coc.

**Comment by GopherJ** [comment]
@fannheyward yes I thought like this, but when I try vscode, I'm surprised it's displaying the progress of the **first** `cargo check`

**Comment by fannheyward** [comment]
Tested with VSCode, can't reproduce. There is no notifications window shows, the output is same as coc:

```
[Trace - 上午10:56:42] Received response 'textDocument/hover - (19)' in 2ms. Request failed: Rust Analyzer is still loading... (-32801).
```

**Comment by GopherJ** [comment]
@fannheyward  it's the following one:
![DeepinScreenshot_select-area_20201228035916](https://user-images.githubusercontent.com/33961674/103186527-1ef20e80-48c1-11eb-8c60-d303c5423a37.png)

**Comment by fannheyward** [comment]
Yes, `cargo clean` first. 

There is no `cargo check xxx` status item.

<img width="1440" alt="截屏2020-12-28 11 06 32" src="https://user-images.githubusercontent.com/345274/103186753-c17bb300-48fc-11eb-8151-936661401622.png">

**Comment by fannheyward** [comment]
Maybe you have another rust related extension in VSCode?

**Comment by GopherJ** [comment]
I think if you  don't open the output window, it'll be there.

**Comment by fannheyward** [comment]
No.

**Comment by fannheyward** [comment]
Do you use `rust-lang.rust` or `matklad.rust-analyzer`?

**Comment by GopherJ** [comment]
ok then I'm not sure anymore, I always had it, strange

**Comment by GopherJ** [comment]
@fannheyward I use 
![image](https://user-images.githubusercontent.com/33961674/103186975-e7846180-48c2-11eb-85bc-1b2a3faf8665.png)

**Comment by fannheyward** [comment]
There is no such status bar item in my tests.

**Comment by GopherJ** [comment]
strange but thanks for the help, I'll debug to see if I can have other info.  vscode should have the status bar item according to:
https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/src/ctx.ts#L39

**Comment by fannheyward** [comment]
This is already supported in coc. The code is not what you seen in status bar item.

**Comment by fannheyward** [comment]
There are two status item: `rust-analyzer` and `indexing/cargo check`.

**Comment by GopherJ** [comment]
yes, is it because the first one wasn't handled explicitly?

**Comment by fannheyward** [comment]
ra.status is already handled: https://github.com/fannheyward/coc-rust-analyzer/blob/master/src/ctx.ts#L54

**Comment by fannheyward** [comment]
> the status bar item according to: https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/src/ctx.ts#L39

this is the `rust-analyzer` status item.

**Comment by fannheyward** [comment]
You can see the second status item, `cargo check x`, when rust-analyzer is Ready. Hover on `rust-analyzer` will show `Ready`.

After `cargo clean`, `code .` is not ready, there is no second status item.

**Comment by GopherJ** [comment]
@fannheyward actually I find that if I manually run `:w` after entering `src/lib`, then the status item starts to work

**Comment by GopherJ** [comment]
@fannheyward See: https://github.com/rust-analyzer/rust-analyzer/issues/7188, it's caused by RA's design, if `loadOutDirsFromCheck` is activated, then there is no `cargo check` status
