### ISSUE TITLE
Hangs on writes

### ISSUE THREAD

**Issue by zmitchell** [fannheyward/coc-rust-analyzer#55]
I'm new to `coc`, `coc-rust-analyzer` and `rust-analyzer` in general (I've been using IntelliJ Rust), so apologies if I'm missing something obvious.

I'm working an issue with `cargo` and I noticed that when I write the buffer my cursor disappears for at least a second until diagnostics are populated. It seems that something is blocking while either `rust-analyzer` or some other operation is executing.

Isn't this supposed to work asynchronously? I'm wondering if I've misconfigured something. Could you offer some suggestions?

Here are my `coc` settings:
```json
{
  "languageserver": {
    "rust": {
      "command": "ra_lsp_server",
      "filetypes": ["rust"],
      "rootPatterns": ["Cargo.toml"],
      "trace.server": "verbose"
    }
  },
  "rust-analyzer": {
      "enableCargoWatchOnStartup": "never"
  }
}
```

**Comment by fannheyward** [comment]
Remove RA config from coc `languageserver` if you’re using `coc-rust-analyzer`. Set `rust-analyzer.enableCargoWatchOnStartup` to `never`. Checkout README for more.

**Comment by zmitchell** [comment]
Sorry I didn't understand what the README was saying before, but following your suggestion made no difference. Can you provide some guidance on how I can debug this?

**Comment by fannheyward** [comment]
Try to remove all rust related configurations in `coc-settings.json`, and try again.

**Comment by zmitchell** [comment]
I figured it out, so I'll leave my solution here for anyone in the future that has the same problem. I still had the `rust-lang/rust.vim` and `syntastic` plugins active. I found that getting rid of just the `syntastic` plugin was enough to make things fast again. Thanks for your help!
