### ISSUE TITLE
indexing starts from scratch after reopening a file

### ISSUE THREAD

**Issue by MihirLuthra** [fannheyward/coc-rust-analyzer#553]
Everytime I open a file in my project, it starts indexing from scratch.
The project is built upon [substrate-node-template](https://github.com/substrate-developer-hub/substrate-node-template), so indexing takes quite a while.

I am using `NVIM v0.4.3` and coc.nvim v0.0.80. I have not changed any defaults.

**Comment by fannheyward** [comment]
It's rust-analyzer's behavior.
