### ISSUE TITLE
Is there a way to notify when coc-rust-analyzer was not run from the project root

### ISSUE THREAD

**Issue by EdmundsEcho** [fannheyward/coc-rust-analyzer#563]
Happy New Year!

I was working on Rust with `coc-rust-analyzer`.  I noticed nvim was not providing me the lints I was expecting.  My code was not compiling and I was using unfamiliar platform-dependent macros.  Being uncertain in general about what was going on :)), I attributed my not seeing lints with the limitations of what to expect.  I checked `CocInfo` and did not see any errors (nor lints); but no errors; the output supported my lazy (admittedly) way of thinking about what was going on.

After a day or so, I realized that I may not have been firing nvim up from the project root directory... which turned out to be the limiting factor. 

I have a message that displays when I have loaded (or not), the python environment.  This is an aside, but the message is a useful FYI.  I wonder if a similar message might be displayed to notify the user that the coc-rust-analyzer is not running from the root project.  In my use case, it would have been helpful and productive. 

Does that make sense?

\- E

**Comment by GopherJ** [comment]
@EdmundsEcho Hi I think it's important to provide some reproducible code examples if you can.

You can try to set this:

```
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true
```
 to see if it improves

**Comment by fannheyward** [comment]
coc will resolve workspaceFolder for current file with `coc_root_patterns`, default is `[".git", ".hg", ".projections.json"]`, coc-rust-analyzer will also add rootPatterns `Cargo.toml`.

When you open a rust file directly, coc will try to resolve the project root as workspaceFolder. You can check the rootPath in trace logs.
