### ISSUE TITLE
`checkOnSave` doesn't work with auto-save

### ISSUE THREAD

**Issue by Kestrer** [fannheyward/coc-rust-analyzer#584]
I have autosave configured in my init.nvim like so:

```rust
autocmd FileType * autocmd TextChanged,InsertLeave <buffer> if &readonly == 0 && filereadable(bufname('%')) | silent w | endif
```

However when the file is saved via this method it doesn't re-run `cargo check` - it requires a manual `:w`. Is there any way to support this?

**Comment by fannheyward** [comment]
Have no idea, I don't use auto-save.

**Comment by rlkandela** [comment]
You have to tell the autocmd that it’s nested, an autocmd does not propagate to more autocmd by default. Here is the code that I use and works for me.

`au FileType rust au InsertLeave,TextChanged <buffer> nested write`
