### ISSUE TITLE
Suggest unimported items

### ISSUE THREAD

**Issue by emigr2k1** [fannheyward/coc-rust-analyzer#585]
In VSCode if you type `Client`, you get suggestions that include unimported items like `reqwest::Client`. This seems to not be the case in coc.

I don't know if it's a bug or a not supported feature but if it's not supported, I would like to try and see if I can get it to work.

**Comment by fannheyward** [comment]
Try v0.30.0

**Comment by emigr2k1** [comment]
Awesome!
Thank you very much
