### ISSUE TITLE
Any way to auto import everything?

### ISSUE THREAD

**Issue by personinblack** [fannheyward/coc-rust-analyzer#586]
I get "Organize import action not found."  when I do `editor.action.organizeImport` but I can execute code actions and add imports one by one. This is not ideal with multiple imports and I couldn't find any better way to do it. Don't know if this is related to rust-analyzer or this, sorry if this is a rust-analyzer limitation.

**Comment by fannheyward** [comment]
Yes, rust-analyzer can do import codeAction one by one, but there is no `editor.action.organizeImport` AFAIK.
