### ISSUE TITLE
snippet's selected range is not in select mode

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#598]
Hi, I'm wondering if the selected range can be in select mode instead of visual. Like coc-snippets, currently it's a little bit complicate to do modification

![Peek 2021-02-03 14-54](https://user-images.githubusercontent.com/33961674/106709587-bae50780-662f-11eb-8053-5e29b039fe08.gif)

**Comment by GopherJ** [comment]
https://github.com/fannheyward/coc-rust-analyzer/blob/master/src/commands.ts#L500

**Comment by fannheyward** [comment]
> in select mode instead of visual

What do you mean select mode?

**Comment by GopherJ** [comment]
![Peek 2021-02-03 15-13](https://user-images.githubusercontent.com/33961674/106711383-65f6c080-6632-11eb-963b-fd008c5b3984.gif)

@fannheyward I mean this, when I type it directly enter insert mode, I dont need to hit `c` for mode switch

**Comment by fannheyward** [comment]
We can make coc into `SNIP` mode after apply edits, but we need to escape SNIP mode manually.

**Comment by GopherJ** [comment]
@fannheyward actually `c` `d` means the same thing here. I still think it's better to keep the same behaviour with coc-snippets. I'll check how coc-snippets did this.

**Comment by GopherJ** [comment]
Because in snippet case we only have two actions:

1. keep it    => `Esc`
2. modify it => `c` and `d` mean the same thing and it's completely unecessary

**Comment by fannheyward** [comment]
We can make it into `SNIP` mode, but this maybe break rust-analyzer snippetTextEdit feature.

> keep it => Esc

`esc` doesn't escape the SNIP mode.
