### ISSUE TITLE
Using clippy +  loadOutDirsFromCheck is not showing warnings 

### ISSUE THREAD

**Issue by augustocdias** [fannheyward/coc-rust-analyzer#606]
When I set the following configuration:

```
  "rust-analyzer.checkOnSave.command": "clippy",
  "rust-analyzer.checkOnSave.extraArgs": ["--tests"],
  "rust-analyzer.cargo.loadOutDirsFromCheck": true,
```

I'm not seeing warnings anymore... Is that correct? 

If I remove either the `command` or the `loadOutDirsFromCheck` I can see warnings again. Both together is not working.
Unrelated question: do I need to the `extraArgs` to also check the tests or it does by default?

**Comment by fannheyward** [comment]
Test your code by VSCode + https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer with same configurations, properly it's a rust-analyzer issue.
