### ISSUE TITLE
 unable to detect Cargo.toml crate's version change

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#611]
Hi @fannheyward Happy new year!

I came across an issue in coc-rust-analyzer recently, the description is:

> I was using reqwest@0.10.8 in one project, then I start to need `.tcp_keepalive` function which is in reqwest@0.10.10, so I changed version number in Cargo.toml and save it, but rust-analyzer still reports errors `missing .tcp_keepalive`

See: https://github.com/rust-analyzer/rust-analyzer/issues/7646

looks like it works in vscode

**Comment by GopherJ** [comment]
Reproduce code:

```rust
fn main() {
  reqwest::ClientBuilder::new().tcp_keepalive(std::time::Duration::from_secs(5)).build();
}
```

**Comment by fannheyward** [comment]
https://user-images.githubusercontent.com/345274/108337028-a4ce6e00-720f-11eb-9c80-ac2e28ec22c7.mov

**Comment by fannheyward** [comment]
Do you have disabled `rust-analyzer.cargo.autoreload`?
