### ISSUE TITLE
[feature request] Semantic Highlighting

### ISSUE THREAD

**Issue by HTG-YT** [fannheyward/coc-rust-analyzer#613]
It has come to my attention that semantic highlighting has *not* been implemented. To me, it would be quite sweet if semantic highlighting exists for this extension, as in: https://rust-analyzer.github.io/manual.html#semantic-syntax-highlighting

Not sure if it is in the scope of the extension or is it in the scope of Neovim itself; nonetheless semantic highlighting would be a great addition.

**Comment by GopherJ** [comment]
semantic highlight will land in coc nvim instead

**Comment by HTG-YT** [comment]
Yup, I found the pull request (https://github.com/neoclide/coc.nvim/pull/2756). Thank you.
