### ISSUE TITLE
Generating missing members are adding ${0:todo!()} where the cursor is supposed to be

### ISSUE THREAD

**Issue by augustocdias** [fannheyward/coc-rust-analyzer#619]
When I invoke the command to implement missing members from a trait, it is adding `${0:todo!()}` to the body of the first function (or to the type, if the trait has it). I believe this is where the cursor is supposed to be after adding.

I'd suggest either to as intended to set the cursor at the position or wipe this out and just output the expected `todo!()`.

**Comment by GopherJ** [comment]
I can reproduce this. Is it related to https://github.com/fannheyward/coc-rust-analyzer/commit/9cb715c3b7c2087e09de9a87baced3466b120494

**Comment by fannheyward** [comment]
How to reproduce this?

**Comment by GopherJ** [comment]
@fannheyward 

```rust
    trait Say {
        fn say_hi(&self);
    }

    struct Person;

    impl Say for Person {
      //cursor here: use leader + aw then choose implement missing members
    }
```

**Comment by fannheyward** [comment]
After the code action:

```
trait Say {
    fn say_hi(&self);
}

struct Person;

impl Say for Person {
    fn say_hi(&self) {
        todo!()
    }
    //cursor here: use leader + aw then choose implement missing members
}
```

**Comment by GopherJ** [comment]
@fannheyward which version are you on? I'm using coc-rust-analyzer@0.32.0

**Comment by fannheyward** [comment]
@GopherJ same, with `rust-analyzer 7435b9e`

**Comment by augustocdias** [comment]
Are you sure are you selecting `Implement missing members` and not the individual function in the list? In the latest versions, rust-analyzer started to suggest also individual functions and types for implementation. This issue doesn't happen for those. It happens only when you select to implement all missing members.

![Screen Recording 2021-02-18 at 09 21 58](https://user-images.githubusercontent.com/1080789/108327108-4c757d00-71cb-11eb-8e59-0e5aa0073ad6.gif)

**Comment by fannheyward** [comment]
https://user-images.githubusercontent.com/345274/108328450-90867300-7207-11eb-80d1-e91d084e6569.mov

What's your coc.nvim version?

**Comment by augustocdias** [comment]
vim version: NVIM v0.4.4
node version: v15.8.0
coc.nvim version: 0.0.80-6e5a2aaeb5

My settings can be seen here: https://github.com/augustocdias/personal-nvim/

off: @fannheyward what do you use to show the codelens for implementations and debug/run? mine shows only for types.

**Comment by fannheyward** [comment]
Reproduced with coc master, I'm using the feat/lsp-316 branch.

**Comment by fannheyward** [comment]
Try v0.33.0.
