### ISSUE TITLE
Virtual text diagnostics is missing

### ISSUE THREAD

**Issue by wisonye** [fannheyward/coc-rust-analyzer#624]
Plz have a look at the screenshot below, left-side is the source code without showing the virtual text diagnostics, on the right side is `cargo watch` result:

![screenshot](https://user-images.githubusercontent.com/3477321/108617107-87500d00-7478-11eb-8829-b09fb40883d2.png)

Here is the result of `:CocCommand rust-analyzer.serverVersion`:

![coc-rust-analzyer-server-version-result](https://user-images.githubusercontent.com/3477321/108617109-8dde8480-7478-11eb-883f-5af96d3180a8.png)

Here is the result of `:CocUpdate`:

![coc-update-result](https://user-images.githubusercontent.com/3477321/108617232-5c19ed80-7479-11eb-84a8-bf897678c319.png)

Here is my `:CocConfig`:

```json
{
    // make the completion automatically select the first completed item
    "suggest.noselect": false,

    // Hide the indicator as it looks weird
    "suggest.snippetIndicator": " ",

    // Not trigger completion on `string` and `comment`, but don't know why it doesn't work :(
    "coc.source.around.disableSyntaxes": [
        "string",
        "comment"
    ],

    // Auto update checking
    "coc.preferences.extensionUpdateCheck": "weekly",

    // Diagnostic settings
    "diagnostic.enable": true,                                
    "diagnostic.virtualText": true,                                
    "diagnostic.virtualTextCurrentLineOnly": false,                
    "diagnostic.checkCurrentLine": true,                           
    "diagnostic.messageTarget": "float",  

    // ----------------------------------------------------------------------------------------
    // `coc-rust-analyzer` related
    // ----------------------------------------------------------------------------------------
    "rust-analyzer.enable": true,
    "rust-analyzer.server.path": "/home/wison/my-shell/rust-analyzer",
    "rust-analyzer.updates.prompt": true,
    "rust-analyzer.diagnostics.enable": true,
    "rust-analyzer.cargo.loadOutDirsFromCheck": false,
    "rust-analyzer.inlayHints.enable": true,                    // Enable to show type hint on the right side
    "rust-analyzer.inlayHints.typeHints": true,                 // Enable to show variable type hint
    "rust-analyzer.inlayHints.typeHintsSeparator": ">> ",       // Variable type prefix symbol
    "rust-analyzer.inlayHints.chainingHints": true,             // Enable to show method chain type hint
    "rust-analyzer.inlayHints.chainingHintsSeparator": ">> ",   // Method chain type prefix symbol
    "rust-analyzer.procMacro.enable": false,
    "rust-analyzer.checkOnSave.enable": false,
    "rust-analyzer.checkOnSave.allTargets": true,
    "rust-analyzer.callInfo.full": true,                        // Show function name and docs in parameter hints
    "rust-analyzer.hoverActions.linksInHover": false,           // Show document links in hover
    "rust-analyzer.completion.addCallParenthesis": true,
    "rust-analyzer.completion.addCallArgumentSnippets": true,
    "rust-analyzer.completion.postfix.enable": true,

    // ----------------------------------------------------------------------------------------
    // `coc-tsserver` related
    // ----------------------------------------------------------------------------------------
    "typescript.format.enabled": true,
    "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true,
    "javascript.format.enabled": true,
    "javascript.suggestionActions.enabled": false
}
```
<hr>

And the funny thing is that it can show `mismatched-arg-count` error...and seems only can show this kind of the error:

![mismatched-arg-count-error](https://user-images.githubusercontent.com/3477321/108617169-f75e9300-7478-11eb-8926-ac03109d54d0.png)

`coc-rust-analyzer` and `rust-analyzer` both are the latest version, and it works before, totally have no idea what's happening. 

Also, the `diagnostics error` can show for another language like `TypeScript` etc, only doesn't work on `Rust`.....

**Comment by PabloMansanet** [comment]
:+1: , having the exact same problem after last update.

**Comment by fannheyward** [comment]
<img width="836" alt="截屏2021-02-22 15 44 34" src="https://user-images.githubusercontent.com/345274/108677611-df444d80-7524-11eb-90fb-035f702f1996.png">

`rust-analyzer 7435b9e`

**Comment by fannheyward** [comment]
Caused by `"rust-analyzer.checkOnSave.enable": false`.

**Comment by PabloMansanet** [comment]
Hmm, I don't know if that's the culprit. I don't have that option in my coc-config at all, and I have the exact same issue. Here are my relevant coc-config lines:

```
   "rust-analyzer.cargo.loadOutDirsFromCheck": true,
   "rust-analyzer.procMacro.enable": true,
   "rust-analyzer.inlayHints.chainingHints": false,
   "rust-analyzer.diagnostics.disabled": ["macro-error", "unresolved-proc-macro"],
   "rust-analyzer.inlayHints.typeHints": false,
   "rust-analyzer.inlayHints.enable": false,
   "rust-analyzer.enableCargoWatchOnStartup": true,
```

Not seeing any virtual text responses as reported by @wisonye

**Comment by wisonye** [comment]
> Hmm, I don't know if that's the culprit. I don't have that option in my coc-config at all, and I have the exact same issue. Here are my relevant coc-config lines:
> 
> ```
>    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
>    "rust-analyzer.procMacro.enable": true,
>    "rust-analyzer.inlayHints.chainingHints": false,
>    "rust-analyzer.diagnostics.disabled": ["macro-error", "unresolved-proc-macro"],
>    "rust-analyzer.inlayHints.typeHints": false,
>    "rust-analyzer.inlayHints.enable": false,
>    "rust-analyzer.enableCargoWatchOnStartup": true,
> ```
> 
> Not seeing any virtual text responses as reported by @wisonye
> 
> EDIT: Nevermind, seems to have resolved itself after a downgrade followed by a reinstall.

@PabloMansanet 
I just confirm that @fannheyward is right. if I re-enable the `"rust-analyzer.checkOnSave.enable": true`, it works exactly what I want, my problem had been solved already!!!

Btw, just wonder where you get that `"rust-analyzer.enableCargoWatchOnStartup": true,` setting from? As I didn't see that in the configuration doc:) Maybe try to remove or comment on it and see what will happen? :)


@fannheyward 
 Also, one more thing want to ask. The reason why I disable "rust-analyzer.checkOnSave.enable" is that I usually will run the "cargo watch --clear --exec run" in the separated terminal, as I want to see real-time change output.

But if do that, I found ...many times (especially the big project), both `coc-rust-analyzer` and `cargo watch` are running the `cargo check` at the same time, then one of them has to be `blocked & wait`. Sometimes even both are waiting for a few seconds. I just don't like that experience and have no idea how to solve that, that's why I disable the "rust-analyzer.checkOnSave.enable". Any idea or suggestion that can get around that `block & wait`? :)

Anyway, thanks for pointing out and solve my problem :) :+1:

**Comment by fannheyward** [comment]
> rust-analyzer.enableCargoWatchOnStartup

This is a very old configuration https://github.com/rust-analyzer/rust-analyzer/pull/2668/files#diff-00784dde03b1be151004f435a4ca74754cb674a9e789840e12760d8f3ac1728fL201

> Any idea or suggestion that can get around that block & wait

Have no idea about this, maybe you can ask rust-analyzer team, coc-rust-analyzer does same as vscode-rust-analyzer.
