### ISSUE TITLE
No automatic reload when Cargo.toml modified outside of Vim

### ISSUE THREAD

**Issue by JDuchniewicz** [fannheyward/coc-rust-analyzer#633]
When I add a crate using `cargo add` there is no update to the completion and I have to restart the editor for the changes to take place (or run `:CocCommand rustAnalyzer.reload`)

**Comment by fannheyward** [comment]
> add a crate using cargo add

What do you mean `cargo add`? If your `Cargo.toml` is changed, RA will detect the changes and request a reload.

**Comment by JDuchniewicz** [comment]
[This repo](https://github.com/killercup/cargo-edit) contains the Cargo extension, and it seems like it should modify the `Cargo.toml` but somehow did not trigger a reload in my case.

**Comment by fannheyward** [comment]
rust-analyzer will not detect Cargo.toml changed by now.

**Comment by fannheyward** [comment]
coc-rust-analyzer will watch Cargo.toml changes, then run `rust-analyzer.reloadWorkspace` to fetch metadata. You need to install https://facebook.github.io/watchman/.

**Comment by JDuchniewicz** [comment]
Amazing! Thanks for this 😁
