### ISSUE TITLE
Suggest crate to add and automate adding

### ISSUE THREAD

**Issue by JDuchniewicz** [fannheyward/coc-rust-analyzer#634]
This is just a feature suggestion. Typing in a `use bar;` could trigger a query across Cargo for a given crate if not found in deps.
I am not familiar with this project so I don't know the mileage of such change. 

Feel free to close it.

**Comment by fannheyward** [comment]
<img width="411" alt="截屏2021-02-26 14 03 21" src="https://user-images.githubusercontent.com/345274/109261801-64887480-783b-11eb-8a66-3a80bf77f234.png">

Trigger it by `<Plug>(coc-codeaction-cursor)`, check `:h coc-codeaction` for more.
