### ISSUE TITLE
CocList -I symbols does not see aliases

### ISSUE THREAD

**Issue by JDuchniewicz** [fannheyward/coc-rust-analyzer#636]
The problem is best illustrated as such:

We have a `struct Vec3;` and a `use Vec3 as Color` statement.
When running `CocList -I symbols` and searching for `Vec3` it finds it just fine but does not resolve `Color`.

 Is this a limitation imposed from the upstream or is it solvable in this project?

**Comment by fannheyward** [comment]
Probably it's rust-analyzer's limitation.
