### ISSUE TITLE
Running a quickfix (rename) does not rename all occurences

### ISSUE THREAD

**Issue by JDuchniewicz** [fannheyward/coc-rust-analyzer#637]
Don't know again if this is in scope of this project. 
When renaming variables using quickfix, not all of them are renamed. 
Example is:
```rust
const ASPECT_RATIO: f64 = 16.0 / 9.0;
const VIEWPORT_HEIGHT: f64 = 2.0;
const VIEWPORT_WIDTH: f64 = aspect_ratio * viewport_height;
```
when renamed (capitalized) the aspect_ratio, it did not rename the occurrence above, but renamed all other.

**Comment by fannheyward** [comment]
Looks like it's rust-analyzer's issue.

**Comment by JDuchniewicz** [comment]
I opened an [issue](https://github.com/rust-analyzer/rust-analyzer/issues/7936) there and I think that `coc-fix-current` misapplies the uppercase transformation in this case. It should do the whole-symbol rename and not just this one case.

**Comment by fannheyward** [comment]
<img width="503" alt="截屏2021-03-10 10 50 23" src="https://user-images.githubusercontent.com/345274/110568723-6d0f7200-818e-11eb-92f3-7f02f2f8903c.png">

`coc-fix-current` will use the _first_ quickfix, try `:CocFix`.

**Comment by JDuchniewicz** [comment]
Yes, it seems like the first fix will be removed as it is a subset of the second one (and not useful). Thanks for help!
