### ISSUE TITLE
Reduce flickering with inlayHints.refreshOnInsertMode

### ISSUE THREAD

**Issue by bagginslin** [fannheyward/coc-rust-analyzer#638]
When using `inlayHints.refreshOnInsertMode = true`, the hints flicker with every character inserted.
I can definitely see this being one of the major reasons why the default for this very useful option is `false`.

Looking at the code, this seems to happen because we first clear the hints, then wait for new hints to be fetched, and only then recreate. Is there any specific reason why the order is not fetch, clear, recreate?
If not, I'd be happy to provide a PR which changes this.

https://github.com/fannheyward/coc-rust-analyzer/blob/61ac4114e2d833a15b7d7496de4a1eaeedba9884/src/inlay_hints.ts#L47-L51
https://github.com/fannheyward/coc-rust-analyzer/blob/61ac4114e2d833a15b7d7496de4a1eaeedba9884/src/inlay_hints.ts#L95-L98

**Comment by fannheyward** [comment]
Try v0.36.0, feedbacks are welcome.

**Comment by bagginslin** [comment]
This fix works great, thanks for the fast response.

I'm not sure if this is intentional, but when `refreshOnInsertMode = false`, the hints no longer disappear when entering insert mode. I see this as a good change, but just making sure this is the behavior you wanted.
