### ISSUE TITLE
Completion popup menu showing the full documentation of matching items

### ISSUE THREAD

**Issue by sisoteuz** [fannheyward/coc-rust-analyzer#645]
Hi,

I'm using NeoVim with latest CoC and coc-rust-analyzer with no extra CoC config and below is my nvim configuration for the completion menu : 

```vim
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
```

As the title suggests each item in the completion popup menu shows the full documentation of the matching items as you can see in the screenshot below : 

![image](https://user-images.githubusercontent.com/3258514/109824549-d8a68c00-7c30-11eb-8b88-1e8070fbca99.png)

I couldn't find a CoC or coc-rust-analyzer configuration to change this behaviour and it makes the completion very impractical. Ideally I would like to just have the first line of documentation next to each matching items.

Hope that it makes and any help appreciated.
Thanks.

**Comment by fannheyward** [comment]
Are you using Neovim-QT? You need to turn off `GuiPopupmenu 0`, https://github.com/neoclide/coc.nvim/issues/903, https://github.com/neoclide/coc.nvim/issues/2782.

**Comment by sisoteuz** [comment]
Thanks a lot, it solved the issue.
