### ISSUE TITLE
Floating window syntax not respecting color commands

### ISSUE THREAD

**Issue by danjenson** [fannheyward/coc-rust-analyzer#649]
My floating window (regardless of background color) renders things like this:
![image](https://user-images.githubusercontent.com/4793438/110219920-f8c78c80-7e76-11eb-899f-427c6e3db447.png)
I'm using neovim-nightly-git on arch linux.

**Comment by fannheyward** [comment]
coc's markdown parses failed, should be fixed in https://github.com/neoclide/coc.nvim/pull/2953
