### ISSUE TITLE
Code actions only available in visual mode

### ISSUE THREAD

**Issue by hashset-of-future** [fannheyward/coc-rust-analyzer#650]
Hi,

I realised that since updating to the latest rust-analyzer-linux server binary and to the latest coc-rust-analyzer version I can only see all available code actions when switching from normal to visual mode. This is exactly the behaviour reported a while ago in #507. Before the update I was able to see the code actions in normal mode, as well.

Is it intended that they should only show up in visual mode or can this be considered a bug?

**Comment by fannheyward** [comment]
How do you fire code actions?

**Comment by hashset-of-future** [comment]
I'm using `<leader>a<CR>` which invokes `:set        operatorfunc=<SNR>17_CodeActionFromSelected`. If I use `:CocAction`, in normal mode I also only see the reduced set of actions.

**Comment by hashset-of-future** [comment]
Looks like it's working! Thank you.
