### ISSUE TITLE
Completion timeout after upgrading to latest version

### ISSUE THREAD

**Issue by JojiiOfficial** [fannheyward/coc-rust-analyzer#651]
After upgrading to the latest version of coc-rust-analyzer today, code completion doesn't work properly anymore. When the intellisense popup should show, in most cases nothing happens and after 5s I get the error 'source rust-analyzer-1 timeout after 5000ms'. Even with a timeout of 10s it doesn't work. I don't have any special coc configuration and with vscode it works flawlessly.

**Comment by fannheyward** [comment]
Can't reproduce. What's your `:CocCommand rust-analyzer.serverVersion`? The latest release is `rust-analyzer d54e115`.

**Comment by fannheyward** [comment]
Do you have set `rust-analyzer.cargo.loadOutDirsFromCheck`? This configuration has been renamed to `rust-analyzer.cargo.runBuildScripts` https://github.com/rust-analyzer/rust-analyzer/commit/3d80e0a15417ccf731a68e3100dfb4c7619c9274#diff-00784dde03b1be151004f435a4ca74754cb674a9e789840e12760d8f3ac1728f

**Comment by JojiiOfficial** [comment]
I'm using the latest release of rust-analyzer. I didn't set any of those two configurations. I gave it a shot without any coc configurations too, but I didn't experience any improvements. Sometimes it works, sometimes it doesn't. Is there a way I could get verbose logs from? Maybe there are some logs which can give the timeout an explanation.

**Comment by fannheyward** [comment]
Set `rust-analyzer.trace.server` to `verbose` to your coc-settings.json, you can get logs from `:CocCommand workspace.showOutput` - `Rust`.

**Comment by JojiiOfficial** [comment]
`:CocCommand workspace.showOutput` doesn't give any output, in fact it doesn't do anything. However `:CocOpenLog` does give the following output:
```
INFO (pid:168586) [services] - registered service "rust-analyzer"
INFO (pid:168586) [services] - Rust Analyzer Language Server state change: stopped => starting
INFO (pid:168586) [language-client-index] - Language server "rust-analyzer" started with 168601
INFO (pid:168586) [services] - Rust Analyzer Language Server state change: starting => running
INFO (pid:168586) [services] - service rust-analyzer started
INFO (pid:168586) [plugin] - coc.nvim 0.0.80-d09f35455b initialized with node: v15.11.0 after 535ms
INFO (pid:168586) [attach] - receive request: CocAutocmd [ 'BufWritePre', 3 ]
INFO (pid:168586) [attach] - receive request: CocAutocmd [ 'BufWritePre', 3 ]
INFO (pid:168586) [attach] - receive notification: highlight []
INFO (pid:168586) [completion-complete] - Results from: around,rust-analyzer-1
WARN (pid:168586) [handler-format] - onTypeFormat  provider not found!
INFO (pid:168586) [attach] - receive notification: highlight []
INFO (pid:168586) [attach] - receive notification: highlight []
INFO (pid:168586) [attach] - receive notification: openLog []
```

**Comment by fannheyward** [comment]
These logs are useless, do you have set `rust-analyzer.trace.server`?

**Comment by JojiiOfficial** [comment]
Yes. I reinstalled coc and coc-rust-analyzer, cleaned up all coc configs, set the this config only, and tried again. `:CocCommand workspace.showOutput` doesn't do anything and the issue still persists.

**Comment by fannheyward** [comment]
Run `:CocCommand workspace.showOutput` after you open a rust file in vim, do you still has nothing displayed?

**Comment by JojiiOfficial** [comment]
Yes, nothing happens at all.

**Comment by fannheyward** [comment]
Have no idea about this. What's your `:CocInfo`?
