### ISSUE TITLE
auto unload expand macro result

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#665]
Hi, recently I found it's useful to use `RA expand macro`, I'm wondering if it's possible to make it automatically unload the buffer like coc-git.

for example when I expand a substrate macro, it's shown like this:
![image](https://user-images.githubusercontent.com/33961674/111284136-d275ce00-867a-11eb-8595-08652b3f309b.png)

often we need this to be able to understand what does this macro do, but we don't want to save it to a file, but currently if I switch back to my code, this buffer stays there and if I quit vim, it asks if I'd like to save this buffer as `Untitled`

**Comment by GopherJ** [comment]
coc-git will automatially unload the buffer if we don't view it anymore

**Comment by fannheyward** [comment]
Which coc-git command or view will auto unload?

**Comment by GopherJ** [comment]
@fannheyward it happens when we switch between buffers
