### ISSUE TITLE
option to disable rust-analyzer.completion.autoimport.enable

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#668]
rust-analyzer supports auto import but it's still not very stable and most of the time I just want to import things manually by calling code actions. This completion can also unexpected behavior, it's annoying to see something unexpected to be imported accidently.

I'm wondering if this can be disabled like described here: https://rust-analyzer.github.io/manual.html#configuration

by putting: `rust-analyzer.completion.autoimport.enable: false`

**Comment by fannheyward** [comment]
`rust-analyzer.completion.autoimport.enable` is already available: 

https://github.com/fannheyward/coc-rust-analyzer/blob/master/package.json#L332-L336

**Comment by GopherJ** [comment]
@fannheyward ah ok I didn't find it in README.md
