### ISSUE TITLE
Not getting any errors displayed in the nvim editor.

### ISSUE THREAD

**Issue by Tandolf** [fannheyward/coc-rust-analyzer#679]
Im sorry for asking here, i have tried googling a lot but i cant find any info.

Im running debian, nvim, coc and fish, and installed this extension. But the problem is i do get inlayHints, etc but strangely im not getting any syntax errors in the nvim editor. Even after i save. So no red arrows at the side, and no error mssages.

I have no idea how to troubleshoot this. I have Checked `CocInfo`, and cant se any errors, or `CocCommand rust-analyzer.analyzerStatus`.

My understanding is that this extension downloads the `rust-analyzer` for me so i dont have to do it by myself.

**Comment by fannheyward** [comment]
Yes, coc-rust-analyzer will download rust-analyzer automatically.

Does inlayHints, goto definition/references/implementation works for you?

**Comment by Tandolf** [comment]
yes inlayHints works, goto definition/references/implementations also works. Im also getting intellisense/code completion. 

Its just that if i write something that is syntactically "wrong" and then save the file, i see that vim is running cargo, something in my airline toolbar, so it is analyzing something. But then i get no red arrows on the left, or any error message. I need to run `cargo build` to actually find out what is wrong. Im suspecting it might be because im running older versions of nvim (0.3.x) since im on debian.

But im not sure. Im mostly seeking for some way to troubleshoot this.

**Comment by fannheyward** [comment]
Try to use a new release of nvim, v0.4+.

**Comment by martinfridrich** [comment]
I have the same problem with versions >=0.39.0 . 0.38.0 is the latest that works for me. 
vim version: NVIM v0.4.3 
node version: v15.12.0 
coc.nvim version: 0.0.80-2dbe0ae611

**Comment by fannheyward** [comment]
@martinfridrich  From v0.39.0, proc-macros is enabled by default, https://github.com/rust-analyzer/rust-analyzer/pull/8032 . What's your rust-analyzer version? Maybe this is related.

**Comment by fannheyward** [comment]
@martinfridrich do you have any rust-analyzer configurations in your coc-settings.json? I still can't reproduce this.

**Comment by martinfridrich** [comment]
coc-settings.json was empty. I've added configurations after I was able to make it work.

**Comment by fannheyward** [comment]
@martinfridrich can't reproduce, can you test your codes with VSCode + rust-analyzer?

**Comment by Tandolf** [comment]
i have no updated to latest vim and i can confirm that the vim version was the issue. Im on debian and their latest version is 0.3.4, upgrading to 0.4.4 gave me compilation errors in the editor when writing rust.
