### ISSUE TITLE
go definition can only jump in current file,can't go other file.

### ISSUE THREAD

**Issue by Jackkakaya** [fannheyward/coc-rust-analyzer#694]
go definition can only jump in current file,can't go other file.

NVIM v0.5.0-dev+1236-g1b030f889
node v14.16.
coc-vim + coc-rust-analyzer

**Comment by Jackkakaya** [comment]
using this conifg all work.
`nmap <silent> <leader>d <Plug>(coc-definition)
nmap <silent> <leader>y <Plug>(coc-type-definition)
nmap <silent> <leader>i <Plug>(coc-implementation)
nmap <silent> <leader>r <Plug>(coc-references)`

but when i change it to
`nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)`

the coc-definition only  jump in current file , others ok.

**Comment by fannheyward** [comment]
What's the output of `:verbose map gd`?

**Comment by Jackkakaya** [comment]
`last set from ~/.vim/plugged/vim-slash/plugin/slash.vim`
oh! thanks!! got it!
