### ISSUE TITLE
Compile errors on startup cause a cycle of error messages

### ISSUE THREAD

**Issue by Luminiscental** [fannheyward/coc-rust-analyzer#699]
When opening a project that doesn't compile on startup, the output of `cargo check` pops up as an error message:
![Image Of Error Message](https://i.imgur.com/e5UPQno.png)
moreover the plugin immediately tries to recompile and pops up the same message in a continuous loop until disabled. Leaving the errors repeating and editing the code to remove the compile error then triggering the onSave recompile does result in breaking the loop.

If I open a project that does compile on startup, and after the initial `cargo check` completes add code that causes a compile error then trigger a recompile using the onSave feature, no error message pops up and things work as they did in previous releases: the compile error is reported through coc diagnostics. So I guess the issue is specific to the startup case where you don't have some kind of build cached.

The setup I'm getting this behaviour on has entirely default settings in `coc-settings.json` using latest stable rust toolchain.

**Comment by flodiebold** [comment]
This should be fixed in rust-analyzer master.

**Comment by fannheyward** [comment]
coc-rust-analyzer 0.42.0 has improved the error handler, similar to VSCode.
 
<img width="1301" alt="截屏2021-04-13 下午6 06 07" src="https://user-images.githubusercontent.com/345274/114535725-ee24c200-9c82-11eb-9558-8f9937e01634.png">
<img width="1283" alt="截屏2021-04-13 下午6 06 37" src="https://user-images.githubusercontent.com/345274/114535792-00066500-9c83-11eb-93fe-6eb2a6f1cca4.png">
