### ISSUE TITLE
Add support for `useClientWatching`

### ISSUE THREAD

**Issue by JeanMertz** [fannheyward/coc-rust-analyzer#7]
There's a bug in a dependency of RA that can cause 100% CPU usage in some projects.

A [workaround was implemented](https://github.com/rust-analyzer/rust-analyzer/pull/1780) that requires setting the `useClientWatching` flag. It would be nice if coc-rust-analyzer added support for that.

I'm not sure if coc supports the watching part of the LSP protocol though, so I'm not even sure this can work.

**Comment by fannheyward** [comment]
done 2e92868eebe6b4cd7a174ef75294bee1b1cd53ff. Try and see if it works.

**Comment by JeanMertz** [comment]
Seems to be working as advertised. Awesome, and thank you for the quick turnaround 👍.

**Comment by fannheyward** [comment]
@JeanMertz Would you like to review this PR https://github.com/rust-analyzer/rust-analyzer/pull/1755 ? I just add `coc-rust-analyzer` to rust-analyzer user doc.

**Comment by Addisonbean** [comment]
Is this still implemented? I'm running into this issue but coc doesn't recognize the setting `rust-analyzer.useClientWatching`
