### ISSUE TITLE
Completion with Standard Library?

### ISSUE THREAD

**Issue by coffeebe4code** [fannheyward/coc-rust-analyzer#700]
I have this string declared.
```
    let buf = "Hello from asm!\n";
```
I installed `coc-rust-analyzer`
`:CocInfo` looks good. I was able to get completion suggestions for both the word `feature` and `asm` in this line 
```
#![feature(asm)]
```

However, things which I think are in the standard library, or just general string methods such as.
```
    buf.as_ptr();
```
I get no completion after typing `buf.` for any string operations.

Is there some other configuration I need to provide?

Full code below, in case the asm syntax could be throwing off the analyzer.
```
fn main() {
    let buf = "Hello from asm!\n";
    let ret: i32;
    unsafe {
        asm!(
        "syscall",
        in("rax") 1,
        in("rdi") 1,
        in("rsi") buf., // <- no completion here
        in("rdx") buf.len(), // <- no completion for len either
        out("rcx") _,
        out("r11") _,
        lateout("rax") ret
        );
    }
    println!("write returned: {}", ret);
}
```

**Comment by fannheyward** [comment]
Can't reproduce, what's your rust-analyzer version? `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --version`.

`md5 ~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer` is `1312653e4dd5d1e81a033e2976b0aae5`.

<img width="423" alt="截屏2021-04-13 上午10 42 03" src="https://user-images.githubusercontent.com/345274/114488980-e47c6980-9c44-11eb-9264-364855dc02ac.png">

**Comment by coffeebe4code** [comment]
I was able to confirm this issue only appears in the `asm!(` block.

Also, how do i disable your extension, or get it to stop endlessly failing in a cycle on startup if the project doesn't compile.

![image](https://user-images.githubusercontent.com/78776922/114645158-7d8b9e80-9c9e-11eb-93a1-c08bce8ec226.png)

Every time I hit enter, it just keeps showing this message.

**Comment by fannheyward** [comment]
@coffeebe4code https://github.com/fannheyward/coc-rust-analyzer/issues/699#issuecomment-818618633

**Comment by coffeebe4code** [comment]
@fannheyward you are a lifesaver. Ran `rustup update`, uninstalled this extension, and works perfectly.

There is no intellisense in asm blocks, but I can live with that. Afterall, Rust's asm is the best asm.
