### ISSUE TITLE
How to use RunSingle and RunDebug commands

### ISSUE THREAD

**Issue by benediktsatalia** [fannheyward/coc-rust-analyzer#701]
I cannot figure out how to use the RunSingle and RunDebug. The comment in the code says that they are internal, but I assume they must be somehow used by something? 

I am looking for a way to have a shortcut to run/debug a unit test directly from the source code.

**Comment by fannheyward** [comment]
For example:

```rust
fn main() {
     println!("Hello world");
}
```

Put your cursor on `main`, fire `<Plug>(coc-codelens-action)`, you'll get this:

<img width="147" alt="截屏2021-04-14 下午2 00 34" src="https://user-images.githubusercontent.com/345274/114661549-c9cff080-9d29-11eb-9075-9bba67173777.png">
