### ISSUE TITLE
how to disallow the error pane infinitely

### ISSUE THREAD

**Issue by lichuan6** [fannheyward/coc-rust-analyzer#705]
Hi,

When opening a rust file with compiling error, neovim will prompt compiling error pane infinitely, is there a way to remove this error message?

![Screen Shot 2021-04-22 at 5 19 05 PM](https://user-images.githubusercontent.com/74223747/115690407-9cb9b880-a38f-11eb-92c3-edc4532edc18.png)

Thanks

**Comment by fannheyward** [comment]
`:CocUpdate` to latest coc-rust-analyzer release.
