### ISSUE TITLE
Confused about In-line hints.

### ISSUE THREAD

**Issue by KarlWithK** [fannheyward/coc-rust-analyzer#709]
Alright, so I was casually testing out doom emacs's lsp mode with Rust-analyzer and I was confused about the difference I saw between the two since coc-rust-analyzer didn't display the same. To illustrate of what I'm talking about here is a screenshot from doom emacs and their lsp mode: 
![2021-04-24_18-13](https://user-images.githubusercontent.com/31679231/115974165-db36ab00-a528-11eb-8e6a-7a4da64145f4.png)

And here is Neovim (running nightly with treesitter) and using Coc-rust-analyzer:
![image](https://user-images.githubusercontent.com/31679231/115974183-002b1e00-a529-11eb-8e86-411783bd1f7f.png)

From my understanding, the "light-bulbs" on doom emacs are code actions, but I also had the notion that they were code hints. However, coc doesnt mark the line as a hint. Is there any way to get similar behavior ( showing what code-actions there are) in neovim?

Thanks.

**Comment by fannheyward** [comment]
It's code action, fire `<Plug>(coc-codeaction-cursor)`, check `:h n_coc-codeaction`.

**Comment by KarlWithK** [comment]
Yea, I  read through the docs and got that. However, I was wondering if there was a way to get those options inline? Like some virtual text.

**Comment by fannheyward** [comment]
> if there was a way to get those options inline

No.
