### ISSUE TITLE
How do I expand an inlay type hint?

### ISSUE THREAD

**Issue by cowlicks** [fannheyward/coc-rust-analyzer#718]
I'm using neovim. I'd like to expand the `...` in the type hint.

![image](https://user-images.githubusercontent.com/598099/116745445-b0cd6d80-a9c0-11eb-9b86-7f7b137f9513.png)

**Comment by x37v** [comment]
Are you talking about `add_explicit_type` from: https://rust-analyzer.github.io/manual.html#assists-code-actions

I'm trying to figure that out..

**Comment by x37v** [comment]
I just figured *something* out.. though not exactly what I wanted..

I put my cursor on the var that I wanted to expand the type for, then i typed `:CocAction` which gave me only 1 thing to select, `Extract into function` .. but, that actually exposed the type I cared about so I was able to grab the type then undo the function expansion.

**Comment by cowlicks** [comment]
@x37v that is helpful!
