### ISSUE TITLE
codelens debug OR run are not stable

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#721]
I've posted this bug long time ago IIRC, it still happens on latest coc-nvim & coc-rust-analyzer.

sometimes there is no lens run & debug, especially on small projects

<img width="856" alt="image" src="https://user-images.githubusercontent.com/33961674/116874243-94913100-ac4b-11eb-8af0-dc00c5024da8.png">

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/issues/2923
