### ISSUE TITLE
rust-analyzer exited with code: null 

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#733]
I start to have this issue after upgrading coc.nvim & coc-rust-analyzer & rust-analyzer to latest

**Comment by GopherJ** [comment]
the code looks quite simple, and it happened when I try to impl `From` trait for a newType:


<img width="395" alt="image" src="https://user-images.githubusercontent.com/33961674/118073776-19fcaa00-b3df-11eb-943f-a0b0e4bbe9d3.png">

**Comment by GopherJ** [comment]
the RA's version is `2021-05-10`

**Comment by fannheyward** [comment]
Tested with `rust-analyzer fd109fb58 2021-05-10 stable`, can't reproduce.

**Comment by GopherJ** [comment]
@fannheyward have you tried multiple times, sometimes I don't have this issue but sometimes I do

**Comment by fannheyward** [comment]
Is there any panic logs in outputChannel?

**Comment by GopherJ** [comment]
@fannheyward 

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/33961674/118074196-0aca2c00-b3e0-11eb-9367-bdcf5e589364.png">

**Comment by GopherJ** [comment]
I've found an issue which is:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/33961674/118074366-55e43f00-b3e0-11eb-8c24-994154c9089b.png">


it looks my neovim is pretty old

**Comment by fannheyward** [comment]
You're using RA ngintly and it crashed.

**Comment by GopherJ** [comment]
@fannheyward thanks, I re-installed rust-analyzer & upgraded nvim and now it looks better

**Comment by GopherJ** [comment]
@fannheyward hi, sorry I still cannot make coc-rust-analyzer works with latest rust-analyzer@2021-05-10, do you have an idea on what it can be ?
