### ISSUE TITLE
implment missing members is strange

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#734]
```rust
pub struct APR(pub u32);

impl From<u32> for APR {
// cursor position
}

fn main() {
    println!("Hello, world!");
}
```

I'd like to have a list of missing memebers of the `From` trait so that it can be easier to write, but the problem is, if I don't enter a `space`, it gives me:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/33961674/118073906-7233ac00-b3df-11eb-8908-d4a3eec5657c.png">

then if I type a space at the beginning  of the line and call `coc-action-selected` on that space, I finally get the thing that I want:

pub struct APR(pub u32);

impl From<u32> for APR {
    // cursor on the space
}

fn main() {
    println!("Hello, world!");
}

<img width="323" alt="image" src="https://user-images.githubusercontent.com/33961674/118073953-91cad480-b3df-11eb-94fe-7ba7572cead4.png">

**Comment by fannheyward** [comment]
<img width="402" alt="截屏2021-05-13 下午12 04 02" src="https://user-images.githubusercontent.com/345274/118075775-516d5580-b3e3-11eb-952c-52e5179d2493.png">

Can't reproduce, put cursor on line 4, there is no space line, code actions as expected.

**Comment by GopherJ** [comment]
@fannheyward because you didn't put empty line there

**Comment by fannheyward** [comment]
They're came from RA with different position. Try `<Plug>(coc-codeaction-cursor)`.
