### ISSUE TITLE
coc-rust-analyzer doesn't work well with RA@2021-04-05 and RA@2021-05-10 anymore

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#737]
Hi, recently I did some upgrades on my coc.nvim & coc-rust-analyzer stack. If found that:

- coc-rust-analyzer doesn't work with RA@2021-04-05 anymore:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/33961674/118390032-9f8e8d00-b65f-11eb-8980-33ce8a072875.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/33961674/118390056-ae753f80-b65f-11eb-91ab-eacb994cd13b.png">

- coc-rust-analyzer doesn't work with RA@2021-05-10, it still crashes but just not frequently

<img width="671" alt="image" src="https://user-images.githubusercontent.com/33961674/118424619-1e380880-b6fa-11eb-96e1-6f910828b468.png">

**Comment by fannheyward** [comment]
The server crashed, client can do nothing about it. Does this happen on VSCode+RA?

**Comment by fannheyward** [comment]
Tested with rust nightly-aarch64-apple-darwin + rust-analyzer b82458818 2021-05-17 stable with parallel code base, no crashes.
