### ISSUE TITLE
Option to disable automatic RA update

### ISSUE THREAD

**Issue by YuhanLiin** [fannheyward/coc-rust-analyzer#741]
Currently the plugin will always prompt the user to update Rust-Analyzer whenever they open Vim if a new version is available. It would be convenient to have a configuration option that disables automatic RA updates, making it easier to pin a version of Rust-Analyzer.

**Comment by GopherJ** [comment]
You can use `serverPath`

**Comment by fannheyward** [comment]
You can pin a version of rust-analyzer by `rust-analyzer.serverPath` to the custom rust-analyzer you want.
