### ISSUE TITLE
thiserror crate's documentation looks strange

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#743]
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/33961674/118794579-4aa37e80-b8cc-11eb-902c-ea6aaf1210fe.png">

reproduce steps:

```
cargo new test-thiserror
cd test-thiserror
vim src/main.rs
```

then type:
```rust
use thi
```

it gives the above ugly link and unparsed `&ensp;` `<br/>`

**Comment by GopherJ** [comment]
also maybe the comment part in documentation should be using gray color:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/33961674/118794868-96eebe80-b8cc-11eb-8fed-3cbb81c2fd42.png">

**Comment by fannheyward** [comment]
Improved in coc.nvim https://github.com/neoclide/coc.nvim/pull/3100
