### ISSUE TITLE
terminal height configuration

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#745]
currently the `codelens - run` terminal is a little bit small:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33961674/118914125-43788100-b95d-11eb-8af1-be46cb73bbb0.png">

which makes it hard to use. I'm wondering if we can have a configuration for the height, I'd like to set it to half of the screen by default

**Comment by fannheyward** [comment]
We can't by now, the terminal size is hardcoded in coc https://github.com/neoclide/coc.nvim/blob/971c5f81b4564bbcb1f3d34e23149bd070dff127/src/model/terminal.ts#L45

You can use something like `autocmd User CocTerminalOpen :resize 20` to resize the terminal when it opens.
