### ISSUE TITLE
request: Improve inline hints

### ISSUE THREAD

**Issue by D1mon** [fannheyward/coc-rust-analyzer#758]
vscode inline hints:
![vscode](https://user-images.githubusercontent.com/3872485/120077074-3f610780-c0b1-11eb-8695-7a23d944e70d.png)

nvim inline hints:
![nvim](https://user-images.githubusercontent.com/3872485/120077100-5869b880-c0b1-11eb-9e22-55783d6f61d3.png)

**Comment by GopherJ** [comment]
it's probably the return value

**Comment by D1mon** [comment]
Now, same result as vscode. Maybe i was have old version of coc-rust-analyzer!?
