### ISSUE TITLE
Install instructions in README.md incomplete?

### ISSUE THREAD

**Issue by schnippl0r** [fannheyward/coc-rust-analyzer#759]
Please have a look at the text in the "Install" section in README.md, because the sentence seems incomplete:

> remove `rust-analyzer` config from `coc-settings.json` if you set

Is there some text missing after "if you set"?

**Comment by GopherJ** [comment]
@schnippl0r could you make a PR to fix it

**Comment by fannheyward** [comment]
@schnippl0r there're two ways to set rust-analyzer with coc.nvim

1. use coc-rust-analyzer
2. set rust-analyzer in your coc-settings.json https://github.com/neoclide/coc.nvim/wiki/Language-servers#rust

If you're using coc-rust-analyzer, you don't and shouldn't set rust-analyzer in your coc-settings.json. This is why the installation text in README.

Maybe the grammar  should be `remove xxx if you've set`.
