### ISSUE TITLE
improve error notificaton

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#763]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/33961674/120314533-ec37c080-c30d-11eb-8be4-9c5aa83cd31c.png">

**Comment by GopherJ** [comment]
upstream issue: https://github.com/rust-analyzer/rust-analyzer/issues/9096

**Comment by GopherJ** [comment]
I'm using coc'nvim's feat/lsp-316 branch btw

**Comment by fannheyward** [comment]
Any suggestions on how to improve it? https://github.com/fannheyward/coc-rust-analyzer/issues/699

**Comment by GopherJ** [comment]
@fannheyward I think maybe RA can give a configuration to filter out such errors
