### ISSUE TITLE
disagnostic.refreshOnInsertMode doesn't seem to work in certain cases

### ISSUE THREAD

**Issue by jamesmcl113** [fannheyward/coc-rust-analyzer#766]
![out](https://user-images.githubusercontent.com/29102582/120894565-05dc4f00-c611-11eb-8969-a86aa47b4b50.gif)
(Essentially what I'm doing is changing the name of a function, and then correcting that function call in another file)

I get the correct error when I change the function definition and then return to the calling code, however when I go to change the calling line, coc does give me the correct name of the function in the auto-complete dropdown, but the error does not disappear as expected, instead I have to write to the buffer before it refreshes. I have "disagnostic.refreshOnInsertMode" set to true in my coc config, however leaving insert mode or inserting more characters doesn't make the error disappear either.
I'm unsure if this is just a limitation or an actual bug, since some errors do disappear once I type out the correct code, without needing to leave insert mode or needing to save.

**Comment by fannheyward** [comment]
<img width="575" alt="截屏2021-06-07 上午11 56 38" src="https://user-images.githubusercontent.com/345274/120956999-6db4a600-c787-11eb-996f-f63c9c736aec.png">

Looks like it's a rust-analyzer's issue, reproduced with VSCode+rust-analyzer. The error was shown and after I changed the error, it won't disappear without saving, I need to do saving to make it work.
