### ISSUE TITLE
still reporting formatSelect: formatRange provider not found

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#767]
I still got this even have:

```
  67      "rust-analyzer.rustfmt.enableRangeFormatting": false,
```

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/33961674/120958278-e288df80-c789-11eb-9fb3-9042f9b0529f.png">

**Comment by fannheyward** [comment]
Because r-a doesn't support range formatting. You need to enable `rust-analyzer.rustfmt.enableRangeFormatting`.
