### ISSUE TITLE
 Bug of format on type

### ISSUE THREAD

**Issue by iamcco** [fannheyward/coc-rust-analyzer#780]
Enable format on type: ` "coc.preferences.formatOnType": true`

main.rs

```
use std::io;

use rand::Rng;

fn main() {
    println!("The secret_number is: |")

    let mut guess = String::new();
}
```

`|` is cursor position, type `{` then the code will become:

```
use std::io;

use rand::Rng;

fn main() {
    println!("The secret_number is: {}")

    let }mut guess = String::new();
}
```

It will insert `}` in the line  ` let mut guess = String::new();` => ` let }mut guess = String::new();`

log:

```
[Trace - 下午9:39:16] Sending request 'textDocument/onTypeFormatting - (8)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/aioiyuuko/develop/test/hello-rust/src/main.rs",
        "version": 4
    },
    "position": {
        "line": 5,
        "character": 37
    },
    "ch": "{",
    "options": {
        "tabSize": 4,
        "insertSpaces": true
    }
}

[Trace - 下午9:39:16] Received response 'textDocument/onTypeFormatting - (8)' in 4ms.
Result: [
    {
        "range": {
            "start": {
                "line": 7,
                "character": 8
            },
            "end": {
                "line": 7,
                "character": 8
            }
        },
        "newText": "}"
    }
]

```

seems like issue of language server?

**Comment by fannheyward** [comment]
1. `;` is missing at the end of `println!("The secret_number is: |")`
2. looks like LS analyzes and makes this line and next line as a whole line to format.
3. if you put `;`, the format on typing is working as expected.

**Comment by iamcco** [comment]
Seems like it's not the issue of `;`, if change `secret_number` to other words like `number` and it works fine. will report issue to rust-analyzer later

**Comment by iamcco** [comment]
Refer: https://github.com/rust-analyzer/rust-analyzer/pull/9355
