### ISSUE TITLE
`rust-analyzer.expandMacro` does nothing

### ISSUE THREAD

**Issue by davidpdrsn** [fannheyward/coc-rust-analyzer#781]
With a simple macro like:

```rust
#![allow(warnings)]

macro_rules! foo {
    () => {
        struct Foo {
            one: i32,
            two: i32,
        }
    };
}

foo!();
```

If I put the cursor on `foo!();` and run `rust-analyzer.expandMacro` nothing happens.

Video:

https://user-images.githubusercontent.com/718941/122820224-adc56e00-d2db-11eb-98b3-50ce2fd222de.mov

What could be causing this? It works fine in vscode.

I'm on the latest version of RA, coc, and coc-rust-analyzer.

**Comment by fannheyward** [comment]
rust-analyzer's issue, put your cursor on `f`, there's no `expandMacro` result, put your cursor on first or second `o`, works as expected. Same as vscode+rust-analyzer.

**Comment by davidpdrsn** [comment]
Ah right. Thanks!

Filed in RA issue https://github.com/rust-analyzer/rust-analyzer/issues/9366
