### ISSUE TITLE
Recent update breaks syntax highlighting

### ISSUE THREAD

**Issue by ryanw** [fannheyward/coc-rust-analyzer#803]
Hi

I recently updated coc-rust-analyzer and since then my syntax highlighting is messed up. It changes once my code has been analyzed, with a lot of things there were different colours now appearing as the same orange colour.

Is this a new feature? Can I turn it off as it's making my code a lot harder to read?

https://user-images.githubusercontent.com/3372/125138393-aa970280-e162-11eb-84d1-86bf1b8d48dd.mp4

**Comment by KarlWithK** [comment]
I temporarily fixed(?) this problem by putting this: `  "coc.preferences.semanticTokensHighlights": false,
` in my `coc-settings.json` due to it overriding treesitter. However, I'm not sure what implications this will have.

**Comment by fannheyward** [comment]
Yes, it's the new semanticTokens feature, https://microsoft.github.io/language-server-protocol/specification#textDocument_semanticTokens.

coc haș enabled this in recently release, there's a default highlight group, check `:h CocSem` for more info. You can use `:call CocActionAsync('showSemanticHighlightInfo')` to show current buffer's highlight groups.
