### ISSUE TITLE
how can i change snippets priority?

### ISSUE THREAD

**Issue by kN1e1ght** [fannheyward/coc-rust-analyzer#808]
I want to lower the language server's priority

**Comment by mwcz** [comment]
I'm wondering the same thing.  In my case, I'd like to hide snippets entirely, but lowering their priority would be just fine instead.  Here's an example, `Scenes` is a module with three public functions, but the snippet `let` appears above the functions, and in general none of the snippets belong at the cursor position.

![Screenshot from 2021-07-13 16-09-07](https://user-images.githubusercontent.com/364615/125518082-5c3dcfd4-2435-4ae7-a826-3ce62cd1da2f.png)

**Comment by willfindlay** [comment]
I would also like to know this

**Comment by fannheyward** [comment]
The snippets sort order is came from rust-analyzer side, for example completion items from `Scenes`:

```
{
      label: 'let',
      kind: 14,
      deprecated: false,
      sortText: 'ffffffff',
      filterText: 'let',
      insertTextFormat: 2,
      textEdit: [Object],
      additionalTextEdits: []
    },
    {
      label: 'random_scene',
      kind: 9,
      documentation: [Object],
      deprecated: false,
      sortText: 'ffffffff',
      filterText: 'random_scene',
      textEdit: [Object],
      additionalTextEdits: []
    },
```

The first is a snippet, the second is the function, they both have the same sortText. This needs rust-analzyer side to improve.
