### ISSUE TITLE
Extension has started messing with my highlighting

### ISSUE THREAD

**Issue by willfindlay** [fannheyward/coc-rust-analyzer#811]
I recently updated this extension after about 4 months or so. After updating, it seems that it has started messing with my highlighting in weird ways. See the following screenshots:

With extension disabled:
![07-16_21:01:14](https://user-images.githubusercontent.com/24983811/126020745-d0aa45c3-3977-4541-aa0d-aef701f033cf.png)

With extension enabled:
![07-16_20:58:19](https://user-images.githubusercontent.com/24983811/126020718-3d254150-84ba-46fd-bfb8-8f793eb29aec.png)

I'd like to know which specific setting to disable so that I can stop the extension from changing my highlighting. Would you be able to assist with this?

**Comment by fannheyward** [comment]
Checkout `:h CocSem` and upgrade your coc.nvim.

**Comment by willfindlay** [comment]
Thanks so much, that does the trick.
