### ISSUE TITLE
Run lens flickers on cursor movement

### ISSUE THREAD

**Issue by oblitum** [fannheyward/coc-rust-analyzer#819]
Well, I've made this gif but for this it's useless, the flicker can't be seen due to framerate. But the problem is, the Run lens text flickers a bit, it seems it happens on cursorhold, the same doesn't happen to inlay hints.

![gif-2021-07-22-203347](https://user-images.githubusercontent.com/1269815/126721673-b2466b23-f45c-4c32-b4e3-0f4bb6a1c003.gif)

**Comment by fannheyward** [comment]
Yes, coc will re-fetch codeLens on CursorHold, https://github.com/neoclide/coc.nvim/blob/master/src/handler/codelens/index.ts#L41, but I can't reproduce the flickers, with this mini.vim

```vim
set nocompatible
set runtimepath^=~/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden

set runtimepath^=~/src/coc-rust-analyzer
```

**Comment by oblitum** [comment]
I believe this may be highly dependent on system maybe. Like refresh rate, etc... In my case the thing is that the flickers happens very fast, so for some people it maybe be unnoticeable, but for me it's quite disturbing.

**Comment by oblitum** [comment]
Despite that, I wonder when CursorHold is a good place to refresh this, since cursor movement won't trigger any code change, so such Run lens won't change either, so there's no reason to keep refreshing them?

**Comment by oblitum** [comment]
FWIW, the inlay hints also have the same flicker, but it just happen less often, because it's not triggered on hold, just when text changes.

**Comment by fannheyward** [comment]
CodeLens will be re-fetch on CursorMoved and CursorHold, because https://github.com/neoclide/coc.nvim/issues/2923 https://github.com/neoclide/coc.nvim/issues/2887.

**Comment by oblitum** [comment]
Well, if that means it's necessary, then fine...
