### ISSUE TITLE
How to disable hover documentation?

### ISSUE THREAD

**Issue by ChiangYintso** [fannheyward/coc-rust-analyzer#827]
The documentation is large so I don't want to show documentation when I hover the cursor.
Is there a configuration like `"rust-analyzer.hover.documentation": false`?
![](https://user-images.githubusercontent.com/40995042/127744764-774e7689-c3c6-4657-a8c0-dd4a9bc1840c.png)

**Comment by memoryruins** [comment]
> Is there a configuration like `"rust-analyzer.hover.documentation": false`?

Yep! that is the exact configuration.
```
rust-analyzer.hover.documentation (default: true)
    Whether to show documentation on hover.
```
More options in https://rust-analyzer.github.io/manual.html#configuration which includes a few other hover options.

**Comment by ChiangYintso** [comment]
Here is my ~/.vim/coc-settings.json
I set `rust-analyzer.hover.documentation` to false but it has no effect.
```
{ 
  "hover.target": "echo",
  "clangd.enabled": false,
  "diagnostic.displayByAle": true,
  "coc.preferences.formatOnSaveFiletypes": [
    "cpp",
    "c",
    "go",
    "rust",
    "python",
    "java"
  ],
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": [
        "c",
        "cpp",
        "cuda",
        "objc",
        "objcpp"
      ],
      "rootPatterns": [
        ".ccls-root",
        "compile_commands.json"
      ],
      "initializationOptions": {
        "cache": {
          "directory": ".ccls-cache"
        },
        "client": {
          "snippetSupport": true
        }
      }
    }
  },
  "rust-analyzer.server.path": "/usr/bin/rust-analyzer",
  "rust-analyzer.hover.documentation": false
}
```

**Comment by ChiangYintso** [comment]
It is my fault. I have also installed "YouCompleteMe" plugin and it is ycm shows the doc.
I add the following configuration to my `.vimrc`  and it works well.
```
let g:ycm_auto_hover=''
nmap <leader>D <plug>(YCMHover)
```
