### ISSUE TITLE
Support for standalone files (no Cargo.toml)

### ISSUE THREAD

**Issue by bagginslin** [fannheyward/coc-rust-analyzer#828]
Currently, when editing a standalone .rs file, the code isn't analyzed and the only diagnostic shown is "file not included in module tree". rust-analyzer seems to have support for standalone files (https://github.com/rust-analyzer/rust-analyzer/pull/8955) but this requires client support as well. It would be great if this feature worked using neovim as well.

**Comment by fannheyward** [comment]
Upgrade your coc-rust-analyzer please, this has been supported already.

**Comment by bagginslin** [comment]
I am on version 0.47.3, which coc says is the newest one, but I still only get the "file not included in module tree" warning.

**Comment by fannheyward** [comment]
The standalone file support has been added in v0.46, https://github.com/fannheyward/coc-rust-analyzer/commit/19d3afdce147df1e8cb61c8b818e5cc5a3d58c1f

**Comment by bagginslin** [comment]
I've reinstalled both coc and rust-analyzer and this still doesn't work, however I have managed to find the code you linked.

When I open a file using `nvim test.rs` in `/tmp`, `workspace.workspaceFolders` is actually equal to `[ { uri: 'file:///tmp', name: 'tmp' } ]` so the `length` is 1 and this code isn't even activated - it works correctly if I patch the if statement. I'm not sure why this happens but I imagine this behavior is unintended.

**Comment by fannheyward** [comment]
coc changed the workspace behavior, will look into this.

**Comment by fannheyward** [comment]
Try v0.48.0

**Comment by bagginslin** [comment]
Works great now, thanks.

**Comment by oblitum** [comment]
Should `detachedFiles` eventually be supported in coc.nvim or should it just be left as coc-rust-analyzer-only?

https://github.com/rust-analyzer/rust-analyzer/pull/8955#issuecomment-916107441

**Comment by fannheyward** [comment]
@oblitum the `detachedFiles` is rust-analyzer only.

**Comment by oblitum** [comment]
okay.. I don't see much a reason for it to exist then, given null workspaces could be used instead.

**Comment by SuperNici** [comment]
I am getting the same `[rust-analyzer unlinked-file] [H] file not included in module tree` (Im doing the [rustlings course](https://github.com/rust-lang/rustlings) for context).
Is this extension not supposed to work out of the box for standalone files? 

I must be missing something.
![image](https://user-images.githubusercontent.com/51826257/175567955-a8bd21b1-95c0-40da-91ea-11f34c287733.png)

- [x] It is on the latest version (0.64.0)
- [x] Autocomplete works flawlessly with rust files that are in an actual project. 

![image](https://user-images.githubusercontent.com/51826257/175569881-83f01abd-193e-4a8e-886a-5083393670e8.png)

**Comment by oblitum** [comment]
@SuperNici rust-analyzer only supports in on its initial load, by means of a needless (from what I can tell) LSP extension, which is covered here. This means that, if you open the editor, open some some standalone file, then open another, it should in fact not work for the second (unless the LSP client is figuring out a "fake" project root on its own and reporting standalone files as non standalone to the LSP server, forcing them to work as non standalone). This is explained in the referred issue's thread.

**Comment by SuperNici** [comment]
Alright i tried opening just one standalone file and even that did not work. I made sure to ask some friends to try it too and its not just a problem for me.

![image](https://user-images.githubusercontent.com/51826257/177217560-830ffad6-8477-4f2c-bb06-6ae1658bbf53.png)

I will be reopening an issue shortly :+1:
