### ISSUE TITLE
Clippy as command leads to no diagnostics

### ISSUE THREAD

**Issue by augustocdias** [fannheyward/coc-rust-analyzer#833]
If I set the setting `rust-analyzer.checkOnSave.command` to `clippy` I'm getting no diagnostics (on multi project workspaces) since last week's rust-analyzer update. Is this an issue with coc or rust-analyzer?

**Comment by fannheyward** [comment]
Can you reproduce this with VSCode+rust-analyzer with same configurations?

**Comment by augustocdias** [comment]
Yes. Same issue happens. I'll report there. Thanks
