### ISSUE TITLE
Triggering rustfmt through rust-analyzer

### ISSUE THREAD

**Issue by spamwax** [fannheyward/coc-rust-analyzer#837]
What's the best way of telling rust-analyzer to format the code?
I've been using `vim-autoformat` plugin but since rust-analyzer has builtin support I wanted to take advantage of it.

Do I need to explicitly set the `rust-analyzer.rustfmt.overrideCommand`?

**Comment by fannheyward** [comment]
Add `rust` into `coc.preferences.formatOnSaveFiletypes`, this will make rust-analyzer runs formatting on save with rustfmt.
