### ISSUE TITLE
Rust analyzer latest version appears incorrect

### ISSUE THREAD

**Issue by rocurley** [fannheyward/coc-rust-analyzer#845]
Rust analyzer believes it is up to date:
```
:CocCommand rust-analyzer.upgrade
[coc.nvim] Your Rust Analyzer release is updated
````
However, the version is shows me is 5b86ff3, which appears to be the release from [2021-01-04](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-01-04) (the latest non-nightly release appears to be [2021-08-16](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-08-16)).
```
:CocCommand rust-analyzer.serverVersion 
[coc.nvim] rust-analyzer 5b86ff3
```

I was actually prompted to update rust analyzer this morning, which I did. Unfortunately I didn't record what version it thought I was upgrading to.

For context: I'm trying to fix what appears to be [this issue](https://github.com/rust-analyzer/rust-analyzer/issues/8686), which should be fixed in the current release.

**Comment by fannheyward** [comment]
1. what's your coc-rust-analyzer version?
2. search `rust-analyzeer` in `~/.config/coc/memos.json`, what's the `release` value?

**Comment by rocurley** [comment]
```
{
  "coc-rust-analyzer|global": {
    "release": "2021-08-16"
  }
}
```

**Comment by fannheyward** [comment]
The `release` value shows that you're using the latest version, do you have another rust-analyzer in your PATH?

**Comment by rocurley** [comment]
```
which rust-analyzer 
/home/roger/.local/bin/rust-analyzer
```
I don't actually know where `coc-rust-analyzer` puts its `rust-analyzer`, so I'm not sure if this is another one or not.

**Comment by fannheyward** [comment]
`coc-rust-analyzer` will download and put rust-analyzer to `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer`.

What's the output of:

1. `/home/roger/.local/bin/rust-analyzer --version`
2. `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --version`

`:CocCommand rust-analyzer.serverVersion` should use `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --version`.

**Comment by rocurley** [comment]
These are, indeed, different:
```
$ /home/roger/.local/bin/rust-analyzer --version
rust-analyzer 7a9ba16
(2020-04-27)
$ ~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --version
rust-analyzer 5b86ff3
(2021-01-04)
```
Neither of these is actually up to date.

**Comment by fannheyward** [comment]
1. do you have `rust-analyzer.server.path` in your coc-settings.json?
2. open a rust project in vim, `ps auxf | grep rust-analyzer` to make sure which rust-analyzer bin are you using.

**Comment by rocurley** [comment]
1: no, I don't have anything rust-analyzer related in `coc-settings.json`.
2: `/home/roger/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer`

**Comment by fannheyward** [comment]
What's the output of `CocCommand rust-analyzer.upgrade` and `:CocCommand rust-analyzer.serverVersion` now?

Have no idea about this, I can't reproduce this.

**Comment by fannheyward** [comment]
Close for now.
