### ISSUE TITLE
#828 breaks bazel / rust-project.json workspaces

### ISSUE THREAD

**Issue by GregBowyer** [fannheyward/coc-rust-analyzer#846]
Hi there, I am using this with `rust-project.json` files.

When standalone code fires it configures rust-analyzer to only use `std` / `core` / `alloc` etc. However thats wrong for my project.

I can work around it for now by commenting out the standalone check.

I am thinking that a config option or checking for rust-project.json could fix this properly

**Comment by fannheyward** [comment]
Can you post a `rust-project.json` project struct? I don't use this, does it like this?

```
- HelloWorld
  - rust-project.json
  - code.rs
```

**Comment by GopherJ** [comment]
curious question: what is `rust-project.json` for?

**Comment by GregBowyer** [comment]
`rust-project.json` is at the top of the tree like this

```
.
├── BUILD
├── README.md
├── WORKSPACE
├── rust
│   ├── BUILD
│   ├── client
│   │   ├── BUILD
│   │   └── src
│   │       └── main.rs
│   └── server
│       ├── BUILD
│       └── src
│           └── main.rs
├── ...
└── rust-project.json
```

The contents are like so
[rust-project.json](https://github.com/fannheyward/coc-rust-analyzer/files/7035287/rust-project.txt)

**Comment by GregBowyer** [comment]
> curious question: what is `rust-project.json` for?

Its used for people who dont have Cargo but want rust-analyzer to do autocomplete and similar

**Comment by fannheyward** [comment]
@GregBowyer I just publish coc-rust-analyzer v0.50.0, please give it a try and feedbacks are welcome, thank you.

**Comment by fannheyward** [comment]
Close for now.
