### ISSUE TITLE
codeLensAction doesn't work anymore

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#847]
it just shows:

![image](https://user-images.githubusercontent.com/33961674/130185781-f86965f4-9b6f-444b-83f5-1129d9ed5153.png)

but didn't do anything, are there any changes on this?

**Comment by GopherJ** [comment]
my config is:
```
nmap <leader>la  <Plug>(coc-codelens-action)
```

**Comment by fannheyward** [comment]
```rust
fn main() {
    println!("Hello, world!");
}
```

You need to put your cursor on the function name line, `main`, to fire codeLensAction. coc has changed this behavior.

**Comment by GopherJ** [comment]
ok I'll try it
