### ISSUE TITLE
Error on "codeLensAction": Could not find executable

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#848]
I'm trying to debug https://github.com/parallel-finance/parallel/blob/master/pallets/liquid-staking-v2/src/tests.rs#L21 this test function using vimspector and this config: https://github.com/GopherJ/cfg/blob/master/vimspector/.vimspector.json#L3-L18

but then it throws out:
![image](https://user-images.githubusercontent.com/33961674/130309872-b36a7e5d-d94f-492c-ad8b-80782387a1ae.png)

**Comment by GopherJ** [comment]
is it rust-analyzer's issue? I'll try to debug with vscode

**Comment by GopherJ** [comment]
ok I have some changes... which has broken the compilation

**Comment by jalcine** [comment]
@GopherJ Do you mind highlighting what exactly was the issue?
