### ISSUE TITLE
Rust Analyzer is not found, download from GitHub release?

### ISSUE THREAD

**Issue by Morganamilo** [fannheyward/coc-rust-analyzer#853]
I have rust analyser installed system wide in `/usr/bin`. That dir does not appear to be checked.

**Comment by Morganamilo** [comment]
I know `rust-analyzer.server.path` exists but `PATH` should probably be checked by default.

**Comment by fannheyward** [comment]
You can set `rust-analyzer.server.path` to use custom rust-analyzer release, PATH will not be checked to use.

**Comment by Morganamilo** [comment]
Is there a reason it won't be checked? Would be nicer if it just worked out of the box.

**Comment by fannheyward** [comment]
1. rust-analyzer is in a very quick/active development, will publish a new release every week. It's better to use newer version of RA, but system installed version maybe outdated. 
2. coc-rust-analyzer will check and download RA from GitHub release, it also works out of box.

**Comment by Morganamilo** [comment]
1. Makes sense but It's still nice to have the option. I'm also on arch linux so the version in the repo's is always up to date.
2. Yes that's nice for those who use it but I'd rather not have a copy of RA for everything that wants to use it.

**Comment by fannheyward** [comment]
>  It's still nice to have the option

Even if I added this configuration to use system rust-analyzer, I prefer to make it be disabled by default. So If you want to use system RA, set `rust-analyzer.server.path`, this will also disable the update checking.
