### ISSUE TITLE
Selecting ra.cargo.target coc-settings.json hides errors

### ISSUE THREAD

**Issue by koivunej** [fannheyward/coc-rust-analyzer#854]
Hi there! Just noticed using the latest coc-rust-analyzer, coc.nvim, if I enable setting 

```
"rust-analyzer.cargo.target": "wasm32-unknown-unknown"
```

It removes all of the errors I currently have with the code while:

- `cargo check --workspace --all-targets` shows the errors
- `cargo check --workspace --all-targets --target wasm32-unknown-unknown` shows the errors
- removing setting `rust-analyzer.cargo.target` re-enables the errors

Could you have some tips to triangulate if this is a coc-rust-analyzer bug or rust-analyzer bug, or perhaps you are aware of some recent regression in `rust-analyzer` for which I just couldn't find an issue?

## versions

From `:CocInfo`, `:CocCommand rust-analyzer.serverVersion`, rustup:

- vim version: NVIM v0.4.4
- node version: v14.17.5
- coc.nvim version: 0.0.80-3086844413
- `[coc.nvim] rust-analyzer 996300f4a 2021-08-23 stable` (stable channel through automatic update of coc-rust-analyzer)
- rust toolchain has been installed through rustup, stable channel, x86_64: `rustc 1.54.0 (a178d0322 2021-07-26)`

**Comment by fannheyward** [comment]
Can you reproduce this with VSCode+rust-analyzer? Looks like it's RA's issue.

**Comment by koivunej** [comment]
It looks like it reproduces in VSCode+rust-analyzer now that I managed to set it up, apologies for the noise!
