### ISSUE TITLE
crategraph in v0.51.1 is much slower than the one in v0.51.0

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#862]
it takes more than 10 seconds to open the browser and display it, but in v0.51.0 it was fast it just opens a new tab.

**Comment by GopherJ** [comment]
also I'm using firefox as default browser, not sure why it launches chrome though.

**Comment by fannheyward** [comment]
coc-rust-analyzer will call `coc#util#open_url` to open the graph file, which uses `xdg-open` on Linux, have no idea why it's slow and uses Chrome.

**Comment by GopherJ** [comment]
@fannheyward FYI, I need to run:
```
 xdg-mime default firefox.desktop 'text/html'
```

to fix this

**Comment by GopherJ** [comment]
also `viewFullCrateGraph` seems not working
