### ISSUE TITLE
Still sometimes no codelens

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#870]
This one has been there for one year I think, I raised also issue in coc.nvim, it seems still not fixed yet.

The problem is that codelens nearly always worked for big projects which need time to index, but for small projects sometimes it just doesn't work

Like the following, there is no `Run | Debug` on main function, in this case even if I want to debug it won't work
![image](https://user-images.githubusercontent.com/33961674/132669768-7dca6d38-bf1c-4451-9f75-899cc0064c2e.png)

If I manually run `:e src/main.rs`, it starts to display codelens actions, I can then debug OR run:
![image](https://user-images.githubusercontent.com/33961674/132670021-8d98adf1-17cb-4da3-b0df-e68f1750096e.png)

but `:e src/main.rs` doesn't always work

**Comment by GopherJ** [comment]
This is actually very important thing to be fixed because when we run tests, we need this one, even if I didn't enter this problem that much in big projects, but it does happen time to time

**Comment by GopherJ** [comment]
#562 #721 #847

**Comment by fannheyward** [comment]
As you said, it's not easy to reproduce. IMO there're two options for this issue:

1. r-a is not ready when client to fetch codeLens
2. the client didn't request codeLens in time, didn't re-fetch in time

For 1, client side has no idea about this. For 2, coc.nvim will fetch codeLens on vim open, and force fetch on `CursorHold` event.

When do you think the client should do fetching?

**Comment by GopherJ** [comment]
I think 1 is happening, and 2 yes it didn't re-fetch, I'm not sure why it didn't though
