### ISSUE TITLE
How to switch this hint type feature? 

### ISSUE THREAD

**Issue by AlanAxp** [fannheyward/coc-rust-analyzer#875]
![image](https://user-images.githubusercontent.com/47508166/133174704-36b4f187-788a-4939-b373-5f68d35688b7.png)

I just updated the rust analyzer, but I got this new feature where I have like a hints type, how I can chose to remove it?

**Comment by fannheyward** [comment]
Set `rust-analyzer.inlayHints.enable` to `false` in your coc-settings.json to disable it.

**Comment by AlanAxp** [comment]
Where can I find such file? And thanks btw

**Comment by fannheyward** [comment]
`:CocConfig`, check `:h coc-configuration`.
