### ISSUE TITLE
Rust-analyzer drastically increases Neovim save time

### ISSUE THREAD

**Issue by RedDocMD** [fannheyward/coc-rust-analyzer#879]
After making changes to a Rust file in Neovim (v0.4.4, using CoC), and hitting `:w`, there is a considerable pause before the file actually saves (in the order of 2 seconds). This problem is only occurring with rust-analyzer - the other language-servers I use (also through CoC) or when I don't have any language-server (for that language), this delay does not occur. Completions appear at the same rate as before. The only slow down seems to be during file saving.
This problem has started recently, about 2 weeks ago.
OS info: Pop OS 21.04, Linux 5.13.0-7614-generic

**Comment by fannheyward** [comment]
1. what's your rust-analyzer version? You can get it by `:CocCommand rust-analyzer.serverVersion`.
2. do you enabled formatOnSave for rust? Do you have `coc.preferences.formatOnSaveFiletypes` in your coc-settings.json with rust?

**Comment by RedDocMD** [comment]
> 1. what's your rust-analyzer version? You can get it by `:CocCommand rust-analyzer.serverVersion`.
> 2. do you enabled formatOnSave for rust? Do you have `coc.preferences.formatOnSaveFiletypes` in your coc-settings.json with rust?

1. rust-analyzer f1d7f98ed 2021-09-20 stable
2.  I don't have `coc.preferences.formatOnSaveFiletypes` set in `coc-settings.json` but I do have `let g:rustfmt_autosave=1` in my `init.vim`, which I guess has the same effect.

**Comment by fannheyward** [comment]
> which I guess has the same effect.

No. `coc.preferences.formatOnSaveFiletypes` will do format-on-save by LS, here is rust-analyzer. You're using rust.vim, which runs `rustfmt` to stdout, parses the result and write back to file. The slow issue is not related to coc/rust-analyzer.
