### ISSUE TITLE
Autocmd issues

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [fannheyward/coc-rust-analyzer#90]
I am using minpac to manage my coc-extensions and using to autocmds to load them on filetype. I am loading them like this.

```vim
call minpac#add('neoclide/coc.nvim', {'do': {-> system('yarn install --frozen-lockfile') }})
if executable('ra_lsp_server')
	call minpac#add('fannheyward/coc-rust-analyzer', {'type': 'opt'}, {'do': {-> system('yarn install --frozen-lockfile') }})
elseif executable('rls')
	call minpac#add('neoclide/coc-rls', {'type': 'opt'}, {'do': {-> system('yarn install --frozen-lockfile') }})
endif
if executable('ra_lsp_server')
	autocmd! FileType rust					packadd coc-rust-analyzer | silent CocRestart 
elseif executable('rls')
	autocmd! FileType rust					packadd coc-rls | silent CocRestart 
endif
```

Running `:CocList extensions` shows

`* coc-rust-analyzer [RTP] 0.0.22 ~/.cache/vim/pack/minpac/opt/coc-rust-analyzer`

But I don't get prompted to start Cargo Watch and `rust-analyzer.analyzerStatus` returns
`E492: Not and editor command: rust-analyzer.analyzerStatus`

Also if coc-rust-analyzer is run without restarting coc.nvim Running `:CocList extensions` shows

`? coc-rust-analyzer [RTP] 0.0.22 ~/.cache/vim/pack/minpac/opt/coc-rust-analyzer`

and cannot be started via enabling or reloading in CocList

**Comment by fannheyward** [comment]
Do you have `lib` folder in `~/.cache/vim/pack/minpac/opt/coc-rust-analyzer` ? There will be two files under lib folder:

```
❯ l lib
total 512
-rw-r--r--  1 fannheyward  staff   248K Dec 25 22:32 index.js
-rwxr-xr-x  1 fannheyward  staff   184B Dec 25 22:32 terminateProcess.sh*
```

**Comment by Th3Whit3Wolf** [comment]
There is no lib folder.
```sh
ls ~/.cache/vim/pack/minpac/opt/coc-rust-analyzer
LICENSE  package.json  README.md   src   tsconfig.json   webpack.config.js  yarn.lock
```

**Comment by fannheyward** [comment]
No lib and node_modules folder means `yarn install` is not run after installed.

I have tested with this: 
`call minpac#add('fannheyward/coc-rust-analyzer', {'do': {-> system('yarn install') }})`
just remove `type` section, `yarn install` will run to build.

Are you sure `do` will work with `{'type': 'opt'}` ?

**Comment by fannheyward** [comment]
Just checked https://github.com/k-takata/minpac/blob/master/doc/minpac.txt , and all `do` hooks example are woking without `type`.

**Comment by Th3Whit3Wolf** [comment]
Hm interesting. I removed the opt and it works exactly as expected. It looks like minpac is unable to to build plugins that aren't started on vim start.
