### ISSUE TITLE
Auto detect variable type for rust

### ISSUE THREAD

**Issue by HungPham3112** [fannheyward/coc-rust-analyzer#900]
I saw some videos on Youtube and they had `explicit type` in VSCode when they use rust-analyzer

![image](https://user-images.githubusercontent.com/75968004/142196606-20f62af9-99e2-4cbf-b962-fc42ec7de69e.png)

Does `coc-rust-analyzer` have this?

**Comment by fannheyward** [comment]
It's called params inlay hints, but we can't add this because we can't put text inline text. https://github.com/fannheyward/coc-rust-analyzer/issues/224 https://github.com/fannheyward/coc-rust-analyzer/issues/177
