### ISSUE TITLE
unresolved import depending how you open the file

### ISSUE THREAD

**Issue by Ricky12Awesome** [fannheyward/coc-rust-analyzer#901]
**rust-analyzer**: rust-analyzer fdd49b971 2021-11-17 dev
**rustc**: rustc 1.58.0-nightly (c9c4b5d72 2021-11-17)

**nvim and coc settings**: https://gitlab.com/Ricky12Awesome/dotfiles/-/tree/main/.config/nvim
**project I've tested this on**: https://github.com/Ricky12Awesome/sysusage

**Related to**: #898  

When opening the project directory and you select the file you want to edit, it will give you this error
but, if you open the directory but select `Cargo.toml` first, it doesn't give you the error

this seems to be an issue when it starts rust-analyzer, since if you just open the directory and do `CocInfo`, it isn't started yet
but when you select a file (like Cargo.toml) then it gets started

so one way to fix this is if you open a directory that contains `Cargo.toml` then it should start the RA server

could also just be an issue with my vim config and nerdtree

https://user-images.githubusercontent.com/29931568/142352252-3a754ee6-6e6b-4d45-8e05-21779ee4060f.mp4

**Comment by Ricky12Awesome** [comment]
another thing I just found out

if you `cd` into the directory first and do `vim .` it works as expected. 

this only happens when you do `vim path/to/project` for some reason

**Comment by fannheyward** [comment]
Yes, you should goto the project first.

**Comment by Ricky12Awesome** [comment]
isn't `vim path/to/project` the same as doing `cd path/to/prject && vim .`?

**Comment by fannheyward** [comment]
The rust-analyzer needs a workspace root to work. If you do `vim path/to/project`, the workspace root is your cwd. After you `cd path/to/project`, the workspace root will be resolved to `path/to/project`.

**Comment by Ricky12Awesome** [comment]
could I change the workspace root in the vim config, so I can have it work when you do `vim path/to/project`?

**Comment by fannheyward** [comment]
I did a test:

1. `cd /tmp`
2. `git clone https://github.com/Ricky12Awesome/sysusage.git`
3. `vim sysusage/src/main.rs`

It's working.

**Comment by Ricky12Awesome** [comment]
this seems to be an issue with coc since now I know what's causing this

thanks for your help

**Comment by fannheyward** [comment]
> an issue with coc since now I know what's causing this

What do you mean this? What's causing this?

**Comment by Ricky12Awesome** [comment]
if you open a directory using vim, and then do `CocList folders` it will give no results

**Comment by fannheyward** [comment]
My tests:

1. same steps as above
2. `vim sysusage`, this will open the project in Netrw
3. `:CocList foders` results `/private/tmp`
4. enter on `src` and enter to open main.ts, everything is working as expected.

**Comment by Ricky12Awesome** [comment]
https://user-images.githubusercontent.com/29931568/142360092-46f68438-b967-42e6-91a0-054a00bc403b.mp4

**Comment by fannheyward** [comment]
Looks like this is caused by NERDTree. Disable it and try again.

It's recommended to goto project root first, because vim didn't have a better workspace support, coc.nvim will try to resolve the project base on root patterns.

**Comment by Ricky12Awesome** [comment]
think I figured out the cause of this, if you change directory with in your vim config, it seems to not be reflected to coc and it's workspaces, but if you change it manually (make sure anything that changes cd is commented out in vim config), it works fine

I switch from NERDTree to coc-explorer, but this should apply to both

this is how I'm launching explorer, with this, the explorer starts fine, but it's whatever directory you execute the command in
```vim
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists('s:std_in') |
  \ exe join(['cd '.argv()[0], 'CocCommand explorer'], ' | ') | wincmd p | enew | endif
```
if you comment that out and just do it manually, it works fine no problem
but for don't comment it out, and try and do this, it doesn't work for some reason
```vim
cd path/to/directory | CocCommand explorer
```
