### ISSUE TITLE
Filling match arms leaves you in visual mode

### ISSUE THREAD

**Issue by Masterhigure** [fannheyward/coc-rust-analyzer#903]
The code action that fills match arms for you leaves you in visual mode. If the action is called from insert mode, it leaves you in visual insert mode. I find this change jarring and mystifying. I have tried activating a few other code actions, such as adding import statements and changing integer literals to binary / octal / hex, and they make no such mode change.

With a .vimrc line like `nmap <leader>a <Plug>(coc-codeaction-cursor)`, the process looks something like this:

Missing match arms located.
![2021-11-26_20-09](https://user-images.githubusercontent.com/41048478/143622620-a0b93a24-11a7-475e-9b9f-6203aa833273.png)

Typing `\a` to bring up the action popup menu:
![2021-11-26_20-09_1](https://user-images.githubusercontent.com/41048478/143622621-575f7630-1e28-480c-8d8d-d69936cb851d.png)

Pressing enter to choose the suitable action:
![2021-11-26_20-10](https://user-images.githubusercontent.com/41048478/143622622-9f8648e9-2d00-4b27-8d0d-438f62ef1992.png)

Note how in the final screenshot I'm in Visual mode. I have tried adding a few simple commands  like `<ESC>` at the end of the `.vimrc` line, but that hasn't helped. Presumably because those are fired between screenshots 1 and 2, and the visual mode change happens between screenshots 2 and 3.

In fact, typing out `:call CocActionAsync('codeAction', 'cursor')` directly rather than going through a keybinding still leaves me in insert mode after filling in the match arms.

I'm on Coc verstion 0.80 and coc-rust-analyzer version 0.56.0.

**Comment by fannheyward** [comment]
> If the action is called from insert mode

How do you fire the code action in insert mode?

**Comment by Masterhigure** [comment]
> > If the action is called from insert mode
> 
> How do you fire the code action in insert mode? I can fire it from normal mode.

That was extremely poorly worded on my part. I had an `imap` to fire it from insert mode, and I wanted to get back to insert mode. To emulate an autocompletion. I of course had to start that command with `<Esc>` to get to normal mode. What did happen, however, was that I naively inserted an `a` after the command. So I had `imap <c-p> <ESC><Plug>(coc-codeaction-cursor)a`. This had the effect of being in insert mode while the popup was open, and then ending up in insert visual mode afterwards. Not regular insert mode.

**Comment by fannheyward** [comment]
No such support.
