### ISSUE TITLE
after adding a new dependency to cargo.toml i need to restart nvim to not get errors

### ISSUE THREAD

**Issue by CheeseOnGithub** [fannheyward/coc-rust-analyzer#904]
im using neovide (the gui client) so that may be the problem

after adding rand to cargo.toml and going into main.rs and adding **_use rand::Rng_** it gives me an error

![image](https://user-images.githubusercontent.com/92813629/143677076-900c4998-199e-4cb7-9c02-ea656e2af34c.png)

it stays like this until i restart nvim, any fixes?

**Comment by fannheyward** [comment]
Try `:CocCommand rust-analyzer.reloadWorkspace`.
