### ISSUE TITLE
Setting chainingHints to false has no effect

### ISSUE THREAD

**Issue by Icelain** [fannheyward/coc-rust-analyzer#913]
**What's the output of `:CocInfo`**

## versions

vim version: NVIM v0.6.0
node version: v17.1.0
coc.nvim version: 0.0.80-19a630de32
coc.nvim directory: /home/icelain/.vim/plugged/coc.nvim
term: undefined
platform: linux

## Log of coc.nvim

2021-12-04T14:55:23.977 INFO (pid:6131) [plugin] - coc.nvim 0.0.80-19a630de32 initialized with node: v17.1.0 after 181ms
2021-12-04T14:55:30.631 INFO (pid:6131) [attach]

**What's the output of `:CocCommand rust-analyzer.serverVersion`**
It shows that there is no such command

Setting `rust-analyzer.inlayHints.chainingHints: false` has no effect and chaining hints are still shown.
![Screenshot](https://i.imgur.com/GhXjx4m.png)

**Comment by fannheyward** [comment]
> It shows that there is no such command

Upgrade your coc-rust-analyzer please. Can't reproduce this issue

**Comment by Icelain** [comment]
I tried again by opening a rust file and got this output -

[coc.nvim] rust-analyzer d9b2291f5 2021-11-29 stable

**Comment by fannheyward** [comment]
@Icelain try disable `rust-analyzer.inlayHints.typeHints`.

**Comment by Icelain** [comment]
I did and restart coc.nvim but still getting them
![](https://imgur.com/3CNw0OU.png)

**Comment by fannheyward** [comment]
Try to disable `rust-analyzer.inlayHints.enable`.

**Comment by Icelain** [comment]
I tried 

> Try to disable `rust-analyzer.inlayHints.enable`.

Tried it, didn't work either

**Comment by fannheyward** [comment]
@Icelain disable `rust-analyzer.inlayHints.enable` will disable all the inlay hints from rust-analyzer, try minimal vimrc.

**Comment by Icelain** [comment]
@fannheyward only disabling `rust-analyzer.inlayHints.enable` and removing everything else from coc-settings.json worked. Thanks for helping me out!
