### ISSUE TITLE
Support rust-project.json in parent directory

### ISSUE THREAD

**Issue by tweksteen** [fannheyward/coc-rust-analyzer#917]
In d4201b3, a new detection was added for the `rust-project.json` file. In the [current implementation](https://github.com/rust-analyzer/rust-analyzer/blob/77f2d349306f137acb296561d10ff745fcf6fed9/crates/project_model/src/lib.rs#L85) of `rust-analyzer`, `rust-project.json` may be in a distant parent directory (e.g., in AOSP, it [will be](https://source.android.com/setup/build/rust/building-rust-modules/rust-ide-setup) at the root of the repository). This change broke the automatic detection of `rust-project.json`. 

If possible, the detection of the workspace location should be left to `rust-analyzer`.

**Comment by fannheyward** [comment]
The d4201b3 is used for standalone rust project, if there's a `rust-project.json` file, the project is not a standalone project, rust-analyzer will check by itself. I don't know what detection is broken.

**Comment by tweksteen** [comment]
That's right, this change was not the cause for the issue. To reproduce: 
- Download Android source (https://source.android.com/setup/build/downloading)
- `. build/envsetup.sh`
- `lunch aosp_bramble-userdebug`
- `SOONG_GEN_RUST_PROJECT=1 m nothing`
- `ln -s $ANDROID_BUILD_TOP/out/soong/rust-project.json $ANDROID_BUILD_TOP`
- `cd system/security/keystore2`
- `nvim src/lib.rs`

It appears that the issue was related to how `coc` discovers the workplaceFolders (see #918).
