### ISSUE TITLE
How to scroll the documentation page in the inlay view?

### ISSUE THREAD

**Issue by glubbfreund** [fannheyward/coc-rust-analyzer#922]
Hi! 

im to silly to know how to scroll down the page. 

![image](https://user-images.githubusercontent.com/17342644/145970654-38456db4-23f1-4c9f-98cb-b3cb82e59504.png)

Sorry for that stupid question but couldnt find an answer anywhere. Thanks in advance.

**Comment by fannheyward** [comment]
Check `:h coc#float#has_scroll`.
