### ISSUE TITLE
Weird highlight after entering code inside braces 

### ISSUE THREAD

**Issue by Warkanlock** [fannheyward/coc-rust-analyzer#947]
After installing ``coc-rust-analyzer`` on my neovim I started to experience highlight inside bracket matching. You can see that after entering a scope, I get this weird yellow highlight. 

![weird-hovering](https://user-images.githubusercontent.com/13340320/153713236-ce2010b1-2815-4467-9ade-cf4bcb6cdc23.gif)

This is a clean installation of neovim and I have tried everything related to [highlight](https://rust-analyzer.github.io/manual.html#highlight-related) in the user manual but it seems to have no effect

Any insights?

**Comment by fannheyward** [comment]
> after entering a scope

Can'r reproduce, I don't think this related to coc.

**Comment by Warkanlock** [comment]
> > after entering a scope
> 
> Can'r reproduce, I don't think this related to coc.

If I disable ``coc-rust-analyzer`` highlight is gone, does this plugin use other dependencies that I'm not seeing?

**Comment by fannheyward** [comment]
Can't reproduce, try minimal vimrc.
