### ISSUE TITLE
Enable procMacro by default?

### ISSUE THREAD

**Issue by hgomersall** [fannheyward/coc-rust-analyzer#950]
In upstream, proc macros are now [enabled by default](https://github.com/rust-analyzer/rust-analyzer/issues/6448), but I needed to enable them explicitly to `coc-settings.json`, as in https://github.com/rust-analyzer/rust-analyzer/issues/7497.

It would be good if the default could reflect upstream.

**Comment by fannheyward** [comment]
`rust-analyzer.procMacro.enable` is enabled now, you didn't need to set it in coc-settings.json. README is outdated, I'll improve it.

https://github.com/fannheyward/coc-rust-analyzer/blob/143ed8e7fb0c49fb54b44ff56fa25c6b59a97b4a/package.json#L654-L658
