### ISSUE TITLE
rust-analyzer.expandMacro can't work in v0.60.1

### ISSUE THREAD

**Issue by youjiali1995** [fannheyward/coc-rust-analyzer#960]
I downgraded `coc-rust-analzyer` to v0.59.1 and it works again.

**Comment by fannheyward** [comment]
Try `v0.60.2`.

**Comment by youjiali1995** [comment]
Not work.

**Comment by fannheyward** [comment]
Can you post an example code? In my tests, expandMacro works as expected.
