### ISSUE TITLE
Disable gray highlight for unused variable hints

### ISSUE THREAD

**Issue by matheusfillipe** [fannheyward/coc-rust-analyzer#963]
**Problem**
On my color scheme gray text becomes practically invisible. I would like to fully disable any coloring this extension would try to make since I believe TreeSitter is already enough for me.

![image](https://user-images.githubusercontent.com/24435787/160908022-2cec9085-c411-47ec-9357-6d38892350e5.png)

**What have I tried**

I've checked multiple color values like `CocWarningSign`, `CocErrorSign`, `CocHintSign`, etc, by running `:hi CocWhatever` and none of them seemed to match the gray for the warnings.

I've switched to multiple different colorschemes but it would be still the same gray for warnings.

I also tried adding: `"coc.preferences.semanticTokensHighlights": false,` to my coc-settings.json but didn't help.

When I disable Treesitter with `TSDisableAll highlight` the function comes back to it's normal color when I hover it but it still with the gray when the cursor is away.
![image](https://user-images.githubusercontent.com/24435787/160908703-675b365a-15da-4efc-8fc8-69c91f187698.png)

![image](https://user-images.githubusercontent.com/24435787/160908677-7d2f1b9a-3e53-4506-9e3a-07ad7ed25917.png)

This doesn't happen when TS highlight is enabled.

I tried checking what is the highlight group on the function with:
```vim
function! <SID>SynStack()
    if !exists("*synstack")
        return
    endif
    echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc
```
But it shows an empty list with TS enabled and `rustFuncName` with TS disabled. rustFuncName links to Func and is m default nice pinkish `ctermfg=169 gui=bold guifg=#bc6ec5. `

**What's the output of `:CocInfo`**
```
## versions

vim version: NVIM v0.6.1
node version: v17.8.0
coc.nvim version: 0.0.80-d0ba54c9 2022-03-30 18:45:24 +0800
coc.nvim directory: /home/matheus/.local/share/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**
```
[coc.nvim] rust-analyzer bc08b8eff 2022-03-28 stable
```

**Comment by fannheyward** [comment]
Can't reproduce, looks like your unused function `repl` is marked grey by some plugins.

Do you enable `semanticTokens.filetypes` in your coc-settings.json? Put your cursor on `repl` and fire `:CocCommand semanticTokens.inspect`, what's the output?

Try minimal vimrc.

**Comment by matheusfillipe** [comment]
If I run `:CocCommand semanticTokens.inspect` Over it I don't get anything
I reduced my config to this:

```vim
function! Cond(cond, ...)
  let opts = get(a:000, 0, {})
  return a:cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction
call plug#begin()
Plug 'neoclide/coc.nvim', Cond(!exists('g:vscode'), {'branch': 'release'})
if has('nvim-0.5') && !exists('g:vscode')
endif
call plug#end()
if empty(glob("~/.config/nvim/plugged")) && empty(glob('~/.vim/autoload/plug.vim'))
    PlugInstall
endif
```
Sorry about the unnecessary if's and vscode bullshit. Well it still displays as this:

![image](https://user-images.githubusercontent.com/24435787/160968425-1dcc4e25-c564-4644-b2fc-7dbb1b0ee15e.png)

For some reason it became a gray highlight foreground, still annoying.

This is my coc-settings: https://gist.github.com/matheusfillipe/ce175711ff76db109630a526bea68c68

There is nothing really about rust there. 

This problem only started after I installed coc-rust-analyzer. From the moment i remove it is back to normal:
![image](https://user-images.githubusercontent.com/24435787/160969072-fd9b5216-1502-4fab-a09a-e624846e445f.png)

**Comment by fannheyward** [comment]
What's your colorscheme?

When you enabled coc-rust-analyzer, rust-analyzer will check your code and find diagnostics on `Type`, it's properly `CocHintSign`.

Can you share a code example for this?

**Comment by matheusfillipe** [comment]
Well I tried switching colorschemes they will all end up having the same gray. On the screenshots I am using `space-vim-dark`. Anyway this doesn't matter, I've just created a minimal config like:

```vim
call plug#begin()
Plug 'neoclide/coc.nvim'
call plug#end()
```

Launched neovim like: `nvim -nu minimal.vim src/main.rs`

And I still have the gray thing.

`CocHintSign` Is changing the color for the line number gutter or whatever it is called, not the gray thing at all. Also the virtual text for telling the Type of variables.
![image](https://user-images.githubusercontent.com/24435787/160978106-aecec93d-ff25-4826-8b4c-6e86c751fe3f.png)

I tried moving away files from ` /usr/share/nvim/runtime` just to make sure it wasn't one of the OS plugins (Arch neovim installation does provide https://github.com/rust-lang/rust.vim) but no... in the cases coc would load the gray problem would still show up.


> Can you share a code example for this?

Sorry, example of what?

**Comment by fannheyward** [comment]
> Can you share a code example for this?

I mean the `main.rs` code to reproduce this issue. Have no idea about the gray thing, tested with this code, still can't reproduce the gray:

```rs
enum Type {
    Int,
    String,
    Stack,
    Null,
}
struct Value {
    type_: Type,
    val: String,
}

fn main() {
    print!("Hello, world!");
}
```

**Comment by matheusfillipe** [comment]
Here is how that looks to me with minimal config, the gray problem is there
![image](https://user-images.githubusercontent.com/24435787/160980921-94c1a0b8-4d3f-472b-8cff-c640c127ff5c.png)

This only happens when the file is on a valid cargo project

If I disable coc:
![image](https://user-images.githubusercontent.com/24435787/160981079-71b7cb05-640b-4112-8ef5-013c5970667f.png)
It looks normal

Same results with neovim nightly. 

I moved `~/.config/coc/extensions ` to `~/.config/coc/extensions_bak` and let coc recreate it and installed only coc-rust-analyzer. Still, the gray thing is there.

**Comment by matheusfillipe** [comment]
Also as a sanity check I've just tried another terminal emulators (konsole, kitty and xterm) and this same effect exist on all of them.

I don't know if this helps but I am also able to reproduce this on a remote ubuntu vps:

![image](https://user-images.githubusercontent.com/24435787/160984779-9063ef85-ccea-472c-bcd0-84880b6eae65.png)

That is xterm sshing to the remote vps and using my minimal.vim

```
## versions

vim version: NVIM v0.7.0-dev
node version: v17.7.2
coc.nvim version: 0.0.80-7ca312f3e4
coc.nvim directory: /home/mattf/.config/nvim/plugged/coc.nvim
term: screen-256color
platform: linux

[coc.nvim] rust-analyzer bc08b8eff 2022-03-28 stable
```

**Comment by fannheyward** [comment]
Reproduced the gray background on `Type` and `Value`.

These two are unused, coc will highlight them with `CocDiagnostic` group. You can set `diagnostic.showUnused` to `false`.

**Comment by matheusfillipe** [comment]
That was really it! I don't see the gray on nothing anymore after adding `"diagnostic.showUnused": false,` to coc-settings.json. But that also gets rid for the gutter on the left side anymore.

I don't have a CocDiagnostic group but I've found which one is it! It is `CocUnusedHighlight`. It ends up linking to `Conceal`:

![image](https://user-images.githubusercontent.com/24435787/161112125-bf1e5368-fd1e-4ed0-b51b-de7a8e2540ea.png)
![image](https://user-images.githubusercontent.com/24435787/161112180-a3725166-ad89-42c0-8356-cfac4396c26c.png)

This is still kinda annoying for me though, but it is much better already. Is there a way to disable changing the just color changing for the text but leave the gutter there?

Anyway thanks for the support!

**Comment by fannheyward** [comment]
Yes it's `CocUnusedHighlight`.

You can set `diagnostic.signLevel` to `error` to only display error sign on signcolumn.
