### ISSUE TITLE
Syntax- and nvim highlighting of variables in format! macro

### ISSUE THREAD

**Issue by Icelk** [fannheyward/coc-rust-analyzer#972]
Rust 1.58 introduced a new syntax, `format!("Info: {variable:?}")`.
This isn't syntax highlighted nor seen as a variable when highlighting / renaming the variable.

<details>
<pre>
[coc.nvim] rust-analyzer bc08b8eff 2022-03-28 stable

vim version: NVIM v0.6.1
node version: v17.8.0
coc.nvim version: 0.0.80-12d84da5 2022-03-21 18:11:22 +0800
coc.nvim directory: /home/icelk/.local/share/nvim/plugged/coc.nvim
term: xterm-kitty
platform: linux</pre>
</details>

**Comment by fannheyward** [comment]
It's rust-analyzer's issue, tested with VS Code + rust-analyzer, same issue.

**Comment by Icelk** [comment]
In a release of rust-analyzer published a few months ago, this does not seem to be the case with VS Code:
https://rust-analyzer.github.io/thisweek/2022/02/07/changelog-115.html

**Comment by fannheyward** [comment]
1. format string completion is working as expected in coc/coc-rust-analyzer.
2. coc-rust-analyzer doesn't provide highlighting, can do nothing about this
3. the rename function is rust-analyzer's issue.

**Comment by Icelk** [comment]
Thanks for the clarification!

**Comment by fannheyward** [comment]
@Icelk for the highlighting issue, you can add `rust` to `semanticTokens.filetypes` in your coc-settings.json, this will use semantic highlighting.

**Comment by Icelk** [comment]
Thanks so much. The issue is resolved now.
