### ISSUE TITLE
Uncaught exception: RangeError: Invalid string length

### ISSUE THREAD

**Issue by MarkSwanson** [fannheyward/coc-rust-analyzer#98]
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 20 2019 13:24:40)
I installed coc and coc-rust-analyzer. I'm using the latest master branch of rust-analyzer.
When I load my Rust sample project, ra_lsp_server runs for 35 seconds and the error message pasted at the end of this issue infinitely loops in the vim window.

I tried two versions of coc:
  Plug 'neoclide/coc.nvim', {'branch': 'master'}
and
  Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}

The exact same thing happens no matter what Rust project/source I attempt to load.

  [coc.nvim] error: Uncaught exception: RangeError: Invalid string length
  [coc.nvim] error:     at BufferChannel.append (/home/mswanson/.vim/plugged/coc.nvim/lib/model/outputChannel.js:44:26)
  [coc.nvim] error:     at LanguageClient.appendOutput (/home/mswanson/.vim/plugged/coc.nvim/lib/language-client/index.js:420:28)
  [coc.nvim] error:     at Socket.<anonymous> (/home/mswanson/.vim/plugged/coc.nvim/lib/language-client/index.js:370:58)
  [coc.nvim] error:     at Socket.emit (events.js:210:5)
  [coc.nvim] error:     at addChunk (_stream_readable.js:309:12)
  [coc.nvim] error:     at readableAddChunk (_stream_readable.js:290:11)
  [coc.nvim] error:     at Socket.Readable.push (_stream_readable.js:224:10)
  [coc.nvim] error:     at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)

**Comment by fannheyward** [comment]
How do you installed `coc-rust-analyzer`? Using `:CocInstall` or by `coc-settings.json`?

**Comment by MarkSwanson** [comment]
:CocInstall

**Comment by fannheyward** [comment]
Please provide a mini vimrc to reproduce this issue.

**Comment by MarkSwanson** [comment]
Here you go:
$ cat .vimrc
call plug#begin('~/.vim/plugged')

" *** Conquer of Completion
Plug 'neoclide/coc.nvim', {'branch': 'release'}
"Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}

call plug#end()

-----
Note that I'm running node: v12.13.1
vim: version 8.2.24
rust-analyzer: latest master from github.

**Comment by MarkSwanson** [comment]
Also note, I did a :PlugClean to ensure my environment was pretty much empty.
.vim/autoload contains: pathogen and plug

**Comment by fannheyward** [comment]
Sorry, but I still can't reproduce this issue. Please provide your `coc-settings.json` and `:CocOpenlog`.

**Comment by fannheyward** [comment]
@MarkSwanson do you still have this issue?

**Comment by MarkSwanson** [comment]
Sorry for the slow response. I've left the [neo]vim ecosystem for VSCode.

**Comment by nimrodashkenazy** [comment]
I have the same issue in neovim.

**Comment by fannheyward** [comment]
@nimrodashkenazy Please provide your coc-settings.json and `:CocOpenlog`.

**Comment by phijor** [comment]
I too encounter this issue from time to time but had a hard time reproducing it. It might be caused by a component that logs just _too_ much. I can reliably reproduce it like this (in the directory of a moderately sized project):

```sh
$ RUST_LOG=debug nvim src/main.rs
```

Just write some code for a bit, at some point CoC will start throwing the exceptions saying that it tried to construct a string that is too large (nodejs/help#1061 I guess?).
