### ISSUE TITLE
invalid config values

### ISSUE THREAD

**Issue by yingmanwumen** [fannheyward/coc-rust-analyzer#989]
**What's the output of `:CocInfo`**

```
vim version: NVIM v0.6.1
node version: v17.7.2
coc.nvim version: 0.0.80-0480cbd997
coc.nvim directory: /home/yingmanwumen/.config/nvim/pack/coc.nvim/start/coc.nvim
term: alacritty
platform: linux
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

```
[coc.nvim] rust-analyzer 5d5bbec 2022-05-20 dev
```

**What's the version of coc-rust-anlyzer**

```
0.62.1
```

**What's the problem**

After opening a rust file with vim/nvim, there are some messages:

![Screenshot_20220521_161007](https://user-images.githubusercontent.com/58961385/169642491-f4c8f004-8098-4eaa-a76b-7ffc1864fd3f.png)

My `coc-setteings.json` is:
```json
{
...
   "rust-analyzer.server.path": "~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer",
    "rust-analyzer.lru.capacity": 512,
    "rust-analyzer.cargo.autoreload": true,

    "rust-analyzer.lens.references.method.enable": true,
    "rust-analyzer.diagnostics.enable": true,

    "rust-analyzer.inlayHints.refreshOnInsertMode": true,
    "rust-analyzer.inlayHints.enable": true,
    "rust-analyzer.inlayHints.maxLength": 25,
    "rust-analyzer.inlayHints.typeHints.enable": true,
    "rust-analyzer.inlayHints.renderColons": true,
    "rust-analyzer.inlayHints.chainingHints.enable": true,
    "rust-analyzer.inlayHints.typeHintsSeparator": "» ",
    "rust-analyzer.inlayHints.chainingHintsSeparator": "» ",
    "rust-analyzer.inlayHints.closureReturnTypeHints.enable": true
...
}
```

I am thinking of maybe the version of my `rust-analyzer` is too new...

**Comment by fannheyward** [comment]
Tested with `rust-analyzer 118238722 2022-05-21 nightly`, can't reproduce this error.

**Comment by fannheyward** [comment]
> rust-analyzer 5d5bbec 2022-05-20 dev

Your rust-analyzer is too old, https://github.com/rust-lang/rust-analyzer/commit/5d5bbec is 14 days ago.

**Comment by yingmanwumen** [comment]
> > rust-analyzer 5d5bbec 2022-05-20 dev
> 
> Your rust-analyzer is too old, [rust-lang/rust-analyzer@5d5bbec](https://github.com/rust-lang/rust-analyzer/commit/5d5bbec) is 14 days ago.

Thanks vary much! Have a nice day!
