### ISSUE TITLE
Check on change (without save)

### ISSUE THREAD

**Issue by T0maas** [fannheyward/coc-rust-analyzer#999]
Is there any option how to enable check on change (not only rust-analyzer.checkOnSave.enable)
I cant find something like `rust-analyzer.checkOnChange.enable`.
Because when I open file that contains some error (typo or bad syntax) and remove the typo, I still see error marked on that line even if line is correct. Mark dissapear only after save.

**Comment by T0maas** [comment]
Im, sorry, problem was on my side, I had an old version pf coc, CocUpdate helped, but some errors do not appear even though they should
```
 let c = MiniCocoon::from_key(&key, &iv ); ‣MiniCocoon
 let enc =  c.wrap(b"hello world"); ‣Result<Vec<u8>, Error>
 println!("{}",enc); // there should be shown error  `Result<Vec<u8>, cocoon::Error>` cannot be formatted with the default formatter
```
The error shows on very short time when I open file, but after ~1s it disapears.

**Comment by fannheyward** [comment]
> The error shows on very short time when I open file, but after ~1s it disapears.

Try minimal vimrc, looks like there're some autocmds to clear the diagnostics.

**Comment by Vycton** [comment]
I have the same issue. If I open a python file (while using coc-python), go into insert mode, type a faulty line, then press escape, the error immediately shows up. Whenever I'm in a Rust file, errors are only shown/removed once I save the file. CocUpdate did not help in my case.

**Comment by fannheyward** [comment]
> errors are only shown/removed once I save the file

@Vycton rust-analyzer can only run check on saving. https://github.com/fannheyward/coc-rust-analyzer/issues/486
